"use client";
import {useId,useState} from "react";
import {motion,useReducedMotion} from "framer-motion";
import {CheckCircle2,GitBranch,LockKeyhole,Timer} from "lucide-react";
import {useWalkthrough} from "@/components/walkthrough-controls";
import {dagChoices,dagTrace,stateLabels,taskReason,taskVisualState,visualStateLabels} from "@/lib/airflow-lab-model";
import type {AirflowLesson} from "@/lib/airflow-lessons";
import type {ExecutionScenario} from "@/lib/airflow-execution";
import {CodeSync,LabControls,Prediction,ScenarioSwitcher,VisualWorkspace} from "./airflow-lab-primitives";
export function DagGraph({trace,step,selected,onSelect,mapping=false,showEligibility=false}:{trace:ExecutionScenario;step:number;selected:string;onSelect:(id:string)=>void;mapping?:boolean;showEligibility?:boolean}){
 const reduce=useReducedMotion(),marker=useId().replace(/:/g,"");
 const frame=trace.frames[step],columns=Math.max(...trace.nodes.map(n=>n.row))+1,fork=trace.nodes.some(n=>n.column!==1),rows=fork?3:1;
 const expanded=!mapping||frame.states.list_files==="success";
 const position=(id:string)=>{const n=trace.nodes.find(n=>n.id===id)!;return {x:(n.row+.5)/columns*1000,y:((fork?n.column:0)+.5)/rows*270};};
 return <div className="af-graph-scroll"><div className={"af-graph"+(fork?" af-fork":"")} style={{gridTemplateColumns:`repeat(${columns},minmax(0,1fr))`,gridTemplateRows:`repeat(${rows},1fr)`}} aria-label="Interactive DAG task states"><svg viewBox="0 0 1000 270" preserveAspectRatio="none" aria-hidden="true"><defs><marker id={marker} markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7Z" fill="currentColor"/></marker></defs>{trace.edges.map(([from,to])=>{const a=position(from),b=position(to),complete=frame.states[from]==="success",active=frame.focus===to&&complete,x1=a.x+360/columns,x2=b.x-360/columns;return <motion.path key={from+to} d={`M${x1},${a.y} C${(x1+x2)/2},${a.y} ${(x1+x2)/2},${b.y} ${x2},${b.y}`} fill="none" strokeWidth={active?3:2} stroke={complete?"#10a779":"#c7d2e6"} style={{color:complete?"#10a779":"#c7d2e6"}} markerEnd={`url(#${marker})`} initial={false} animate={{pathLength:1,opacity:expanded?1:.35}} transition={{duration:reduce?0:.3}}/>;})}</svg>{trace.nodes.map(n=>{const state=frame.states[n.id],visualState=showEligibility?taskVisualState(trace,step,n.id):state,hidden=mapping&&n.id.startsWith("process_")&&!expanded;return <motion.button key={n.id} className={`af-task af-state-${visualState}${frame.focus===n.id?" af-task-active":""}`} style={{gridColumn:n.row+1,gridRow:(fork?n.column:0)+1}} aria-pressed={selected===n.id} onClick={()=>onSelect(n.id)} initial={false} animate={{opacity:hidden?.45:1,scale:frame.focus===n.id&&!reduce?1.025:1}} transition={{duration:reduce?0:.2}}><span>{state==="success"?<CheckCircle2 size={17}/>:visualState==="none"?<LockKeyhole size={16}/>:<GitBranch size={16}/>}</span><strong>{hidden?"Mapped template":n.id.replace("process_","process[")+(n.id.startsWith("process_")?"]":"")}</strong><small>{hidden?"Not expanded yet":showEligibility?visualStateLabels[visualState]:stateLabels[state]}</small></motion.button>;})}</div></div>;
}
function DagSession({lesson,variant}:{lesson:AirflowLesson;variant:string}){
 const trace=dagTrace(lesson,variant),sensor=lesson.id==="sensors";
 const [fileExists,setFileExists]=useState(false),[selected,setSelected]=useState<string|null>(null),[resetId,setResetId]=useState(0);
 const waitAt=trace.frames.findIndex(f=>f.states.wait_file==="up_for_reschedule");
 const controls=useWalkthrough(sensor&&!fileExists?waitAt+1:trace.frames.length),frame=trace.frames[controls.step];
 const node=selected??frame.focus,complete=controls.step===trace.frames.length-1,waiting=sensor&&!fileExists&&controls.step===waitAt;
 const code=trace.code.split("\n"),highlight=Math.max(0,code.findIndex(line=>line.includes(frame.focus)));
 const seenStates=trace.frames.slice(0,controls.step+1).map(f=>f.states[node]).filter((s,i,arr)=>i===0||arr[i-1]!==s);
 function reset(){controls.change(0);setSelected(null);setFileExists(false);setResetId(id=>id+1);}
 return <VisualWorkspace title="Watch Execution" controls={<LabControls state={controls} onReset={reset} blocked={waiting}/>}><div className="af-run-strip"><span><i className={complete?"af-dot-success":""}/> DAG run · {complete?(Object.values(frame.states).includes("failed")?"failed":"success"):"educational trace"}</span><span>{lesson.id==="taskflow"?"Definition → task references → runtime":"Why can this task run now?"}</span>{sensor&&<label><input type="checkbox" checked={fileExists} onChange={e=>{setFileExists(e.target.checked);controls.change(Math.min(controls.step,waitAt));}}/>File exists: {fileExists?"ON":"OFF"}</label>}</div><DagGraph trace={trace} step={controls.step} selected={node} onSelect={setSelected} mapping={lesson.id==="dynamic-mapping"}/><div className="af-event" role="status" aria-live={controls.auto?"off":"polite"}><b>{controls.step+1}</b><div><strong>{frame.title}</strong><p>{frame.explanation}</p></div><span>{frame.actor}</span></div>{waiting&&<p className="af-wait"><Timer size={16}/>Waiting for the file. Worker slot released; load stays blocked. Turn File exists ON to continue the next check.</p>}<div className="af-support"><CodeSync lines={code} active={highlight} label={lesson.id==="taskflow"?"TaskFlow · authoring fragment":"Python · dependency / policy sketch"}/><section className="af-inspector"><header><strong>{node} · why this state?</strong>{selected&&<button onClick={()=>setSelected(null)}>Follow active task</button>}</header><p>{taskReason(trace,controls.step,node)}</p><div className="af-state-timeline" aria-label={`${node} state history`}>{seenStates.map((state,i)=><span className={`af-state-${state}`} key={i}>{stateLabels[state]}</span>)}</div></section></div>{["dags-dependencies","trigger-rules","retries","sensors"].includes(lesson.id)&&<Prediction key={resetId} question={lesson.decision.question} options={lesson.decision.options} correct={lesson.decision.correct} explanation={lesson.decision.explanation} revealed={complete||waiting}/>}<p className="af-caveat">Airflow 3.1 · deterministic educational trace, not a running scheduler. One possible execution order; timing and concurrency are simplified. {lesson.id==="dynamic-mapping"?"Two input files expand to two mapped instances; their execution order is not guaranteed.":lesson.id==="sensors"?"This example uses reschedule mode, not a deferrable operator.":"Dependency arrows represent eligibility, not bulk data transfer."}</p></VisualWorkspace>;
}
export function AirflowDagLab({lesson}:{lesson:AirflowLesson}){const choices=dagChoices[lesson.id]??["Default scenario"],[variant,setVariant]=useState(choices[0]);return <>{choices.length>1&&<ScenarioSwitcher choices={choices} value={variant} onChange={setVariant}/>}<DagSession key={`${lesson.id}:${variant}`} lesson={lesson} variant={variant}/></>;}
