"use client";
import {useState} from "react";
import {ArchitectureServices,IntervalTimeline} from "./airflow-lesson-details";
import {motion,useReducedMotion} from "framer-motion";
import {ArrowRight,CheckCircle2,Database,GitBranch} from "lucide-react";
import {useWalkthrough} from "@/components/walkthrough-controls";
import {flowChoices,flowStory} from "@/lib/airflow-lab-model";
import type {AirflowLesson} from "@/lib/airflow-lessons";
import {CodeSync,LabControls,Prediction,ScenarioSwitcher,VisualWorkspace} from "./airflow-lab-primitives";
function FlowSession({lesson,choice}:{lesson:AirflowLesson;choice:string}){
 const story=flowStory(lesson.id,choice),controls=useWalkthrough(story.steps.length),frame=story.steps[controls.step],reduce=useReducedMotion();
 const [selected,setSelected]=useState<number|null>(null),[resetId,setResetId]=useState(0),active=selected??frame.node;
 return <VisualWorkspace title={lesson.id==="monitoring"?"Watch Diagnosis":"Watch Execution"} controls={<LabControls state={controls} onReset={()=>{controls.change(0);setSelected(null);setResetId(id=>id+1);}}/>}><div className="af-run-strip"><span><i/>{lesson.id==="architecture"?"Conceptual control path":"Deterministic teaching flow"}</span><span>{choice}</span></div>{lesson.id==="scheduling"&&<IntervalTimeline choice={choice} step={controls.step}/>}<div className="af-flow" style={{gridTemplateColumns:`repeat(${story.nodes.length},minmax(0,1fr))`}}>{story.nodes.map((node,i)=><div key={node.label} className="af-flow-item"><motion.button className={"af-flow-node"+(frame.node===i?" af-flow-active":"")+(i<frame.node?" af-flow-done":"")} aria-pressed={active===i} onClick={()=>setSelected(i)} initial={false} animate={{y:frame.node===i&&!reduce?-3:0}} transition={{duration:reduce?0:.2}}><span>{i<frame.node?<CheckCircle2 size={25}/>:lesson.id==="xcom"&&i===3?<Database size={25}/>:<GitBranch size={25}/>}</span><strong>{node.label}</strong><small>{node.detail}</small></motion.button>{i<story.nodes.length-1&&<ArrowRight className={i<frame.node?"af-edge-done":""} size={19}/>}</div>)}</div><div className={"af-payload"+(frame.danger?" af-payload-warning":"")}><span>{lesson.id==="xcom"?"Message / reference":lesson.id==="monitoring"?"Evidence":"Current result"}</span><motion.code key={frame.value} initial={reduce?false:{opacity:0,x:12}} animate={{opacity:1,x:0}} transition={{duration:reduce?0:.2}}>{frame.value}</motion.code></div><div className="af-event" role="status" aria-live={controls.auto?"off":"polite"}><b>{controls.step+1}</b><div><strong>{frame.title}</strong><p>{frame.explanation}</p></div></div>{lesson.id==="architecture"&&<ArchitectureServices/>}<div className="af-support"><CodeSync lines={story.code} active={frame.line} label={lesson.id==="monitoring"?"Mock logs · educational evidence":lesson.id==="architecture"?"Component responsibility sketch":"Python / configuration · teaching fragment"}/><section className="af-inspector"><header><strong>{story.nodes[active].label}</strong>{selected!==null&&<button onClick={()=>setSelected(null)}>Follow active step</button>}</header><p>{story.steps.find(s=>s.node===active)?.explanation??story.nodes[active].detail}</p><div className="af-flow-history">{story.steps.slice(0,controls.step+1).map((s,i)=><span key={i}><CheckCircle2 size={13}/>{s.title}</span>)}</div></section></div>{["scheduling","xcom","production"].includes(lesson.id)&&<Prediction key={resetId} question={lesson.decision.question} options={lesson.decision.options} correct={lesson.decision.correct} explanation={lesson.decision.explanation} revealed={controls.step===story.steps.length-1}/>}<p className="af-caveat">Green flow cards mean visited steps, not successful task states. {story.caveat}</p></VisualWorkspace>;
}
export function AirflowFlowLab({lesson}:{lesson:AirflowLesson}){const choices=flowChoices[lesson.id],[choice,setChoice]=useState(choices[0]);return <><ScenarioSwitcher choices={choices} value={choice} onChange={setChoice}/><FlowSession key={`${lesson.id}:${choice}`} lesson={lesson} choice={choice}/></>;}
