"use client";
import {cloudPracticeScenarios} from "@/lib/cloud-practice-scenarios";
import {useState} from "react";
import type {SparkLesson} from "@/lib/spark-lessons";
type Props={lesson:SparkLesson;active:string;notes:string;draft:string;saveNotes:(value:string)=>void;saveDraft:(value:string)=>void;storageError:boolean};
export function CloudStudyTabs({lesson,active,notes,draft,saveNotes,saveDraft,storageError}:Props){
 const [choices,setChoices]=useState<Record<number,number>>({});const [submitted,setSubmitted]=useState(false);
 const scenario=cloudPracticeScenarios[lesson.id];
 const [setting,setSetting]=useState(0),[prediction,setPrediction]=useState(""),[result,setResult]=useState<number|null>(null);
 const score=lesson.quiz.filter((q,i)=>choices[i]===q.correct).length;
 return <section className="cloud-study"><header className="cloud-study-head"><span>{active} · {lesson.title}</span><h2>{({Examples:"Follow the data. Explain each decision.","Hands-on":"Build your own explanation of the flow.","Interview Qs":"Understand it. Then say it clearly.","Common Mistakes":"Spot the fault before it reaches production.",Quiz:"Can you predict what happens next?",Notes:"Make this lesson yours."} as Record<string,string>)[active]}</h2><p>Use the service behaviour you saw in the simulation to reason about the same workload.</p></header>
 {scenario&&(active==="Examples"||active==="Hands-on")&&<article className="cloud-study-card cloud-scenario"><span className="cloud-study-number">{active==="Hands-on"?"Predict → run → compare":"Concrete lesson scenario"}</span><h3>{scenario.title}</h3><p>{scenario.input}</p>{active==="Hands-on"?<><label htmlFor="cloud-scenario-setting">{scenario.control}</label><select id="cloud-scenario-setting" value={setting} onChange={e=>{setSetting(Number(e.target.value));setResult(null);}}>{scenario.options.map((option,i)=><option key={option} value={i}>{option}</option>)}</select><label htmlFor="cloud-scenario-prediction">What do you expect to happen?</label><input id="cloud-scenario-prediction" value={prediction} onChange={e=>setPrediction(e.target.value)} placeholder="Predict the result before running"/><button onClick={()=>setResult(setting)} disabled={!prediction.trim()}>Run scenario</button>{result!==null&&<div className={result===scenario.correct?"cloud-study-right":"cloud-study-wrong"} role="status"><h4>Simulated outcome</h4><p>{scenario.outcomes[result]}</p><p>Your prediction: {prediction}</p><strong>{scenario.principle}</strong><small>Local teaching model; no cloud resources are executed. Try another choice to compare.</small></div>}</>:<><p><strong>Choice:</strong> {scenario.options[scenario.correct]}</p><p><strong>Result:</strong> {scenario.outcomes[scenario.correct]}</p><p>{scenario.principle}</p></>}</article>}
 {active==="Examples"&&<><div className="cloud-study-flow">{lesson.flow.map((stage,i)=><div key={stage}><small>{String(i+1).padStart(2,"0")}</small><strong>{stage}</strong></div>)}</div><div className="cloud-study-columns"><article className="cloud-study-card"><h3>Worked architecture</h3><pre>{lesson.example.code}</pre><h4>Expected outcome</h4><p>{lesson.example.output}</p></article><article className="cloud-study-card"><h3>What happens and why</h3><ol>{lesson.example.walkthrough.map(text=><li key={text}>{text}</li>)}</ol><h4>Explain the boundary</h4><p>At each arrow, name what moves, which service acts on it, and whether the source changes.</p></article></div></>}
 {active==="Hands-on"&&<div className="cloud-study-columns"><article className="cloud-study-card"><h3>Your brief</h3><p>{lesson.practice.task}</p><h4>Acceptance checks</h4><ul><li>Name the input and expected output.</li><li>Assign each operation to a service responsibility.</li><li>Explain permissions, failure behaviour and how you would verify the result.</li></ul><label htmlFor="cloud-design-draft">Your design and reasoning</label><textarea id="cloud-design-draft" value={draft} onChange={e=>saveDraft(e.target.value)} placeholder="Input → service → operation → output. What might fail? What evidence would confirm success?"/><small>{storageError?"Device storage unavailable.":"Draft saved on this device. This exercise does not provision cloud resources."}</small></article><article className="cloud-study-card"><h3>Support when you need it</h3><details><summary>Give me a hint</summary><p>{lesson.practice.hint}</p></details><details><summary>Compare with a reference design</summary><pre>{lesson.practice.solution}</pre><h4>Expected result</h4><p>{lesson.practice.output}</p><p>Other designs can be valid if you justify their behaviour and trade-offs.</p></details><h4>Defend your choice</h4><p>Which requirement would make you change this design? What happens if the same input is retried?</p></article></div>}
 {active==="Interview Qs"&&<div className="cloud-study-stack">{lesson.interview.map((item,i)=><article className="cloud-study-card" key={item.question}><span className="cloud-study-number">{i<2?"Foundations":i<4?"Practical application":"Troubleshooting"} · Question {i+1}</span><h3>{item.question}</h3><div className="cloud-study-columns"><div><h4>Say it briefly</h4><p>{item.answer.split(/(?<=[.!?])\s+/).slice(0,2).join(" ")}</p><h4>Detailed reasoning</h4><p>{item.answer}</p></div><div className="cloud-study-recall"><h4>Go one level deeper</h4><p>{item.followup}</p><small>Answer aloud first. Support your explanation with a concrete step from the lesson flow.</small></div></div></article>)}</div>}
 {active==="Common Mistakes"&&<div className="cloud-study-stack">{lesson.mistakes.map(item=><article className="cloud-study-card" key={item.title}><h3>{item.title}</h3><p>{item.why}</p><div className="cloud-study-columns"><div className="cloud-study-wrong"><h4>Broken flow / symptom</h4><pre>{item.before}</pre></div><div className="cloud-study-right"><h4>Corrected behaviour</h4><pre>{item.after}</pre><p>{item.better}</p></div></div></article>)}</div>}
 {active==="Quiz"&&<><p className="cloud-study-status" role="status">{submitted?`${score} / ${lesson.quiz.length} correct · review the reasoning below`:`${Object.keys(choices).length} / ${lesson.quiz.length} answered`}</p><div className="cloud-study-stack">{lesson.quiz.map((q,i)=><fieldset className="cloud-study-card" key={q.question}><legend>{i+1}. {q.question}</legend>{q.options.map((option,j)=><label className="cloud-study-option" key={option}><input type="radio" name={`cloud-quiz-${i}`} checked={choices[i]===j} onChange={()=>{setChoices(prev=>({...prev,[i]:j}));setSubmitted(false);}}/>{option}</label>)}{submitted&&<div className={choices[i]===q.correct?"cloud-study-right":"cloud-study-wrong"}><strong>{choices[i]===q.correct?"Correct":"Review this answer"}</strong><p>{q.explanation}</p>{q.optionExplanations&&<ul>{q.options.map((option,j)=><li key={option}><strong>{option}:</strong> {q.optionExplanations?.[j]}</li>)}</ul>}{choices[i]!==q.correct&&<p>Correct answer: {q.options[q.correct]}</p>}</div>}</fieldset>)}</div><button disabled={Object.keys(choices).length!==lesson.quiz.length} onClick={()=>setSubmitted(true)}>Check my understanding</button></>}
 {active==="Notes"&&<div className="cloud-study-columns"><article className="cloud-study-card"><h3>Recall sheet</h3>{lesson.concepts.map(([title,body])=><div key={title}><h4>{title}</h4><p>{body}</p></div>)}</article><article className="cloud-study-card"><h3>Your explanation</h3><button onClick={()=>saveNotes((notes?notes+"\n\n":"")+"Definition:\nInput → operation → output:\nPractical example:\nTrade-off:\nCommon mistake:\nMy interview answer:\n")}>Add recall template</button><p>Define the service in one sentence. Describe what enters, what happens inside, what leaves, and one mistake to avoid.</p><label htmlFor="cloud-personal-notes">Personal lesson notes</label><textarea id="cloud-personal-notes" value={notes} onChange={e=>saveNotes(e.target.value)} placeholder="In my own words…
Example I can explain…
Trade-off to remember…
Question I still have…"/><small role="status">{storageError?"Not saved: device storage unavailable.":"Automatically saved on this device for this lesson."}</small><h4>Interview recall</h4><p>{lesson.interview[0]?.question}</p></article></div>}
 </section>;
}
