"use client";
import { useState } from "react";
import { GlossaryText } from "@/components/glossary";
import { SimpleExplanation } from "@/components/simple-explanation";

const questions = [
  { question: "When would you choose an RDD over a DataFrame?", difficulty: "Intermediate", hint: "Think about the control you need, and what Spark can optimize.", answer: "I normally start with a DataFrame for structured transformations because Spark can optimize column expressions. I choose an RDD when I need low-level processing of custom objects or partition behavior that is awkward to express with structured APIs. Unstructured input alone is not enough reason to choose an RDD: it may be parsed into a DataFrame.", simple: "A DataFrame tells Spark what result you want using columns. An RDD lets you describe more of the processing yourself, but Spark has less information to improve that work.", example: "Use a DataFrame to group sales by customer. Consider an RDD for a specialized algorithm over custom objects that cannot be expressed conveniently with column operations.", checks: ["Started with DataFrames for typical structured work", "Explained the control-versus-optimization tradeoff", "Gave a specific reason for using an RDD"], follow: "Would reading a text file always require an RDD?", followAnswer: "No. Spark can read text into a DataFrame and parse it into columns. Choose the API based on the processing required.", terms: ["Low-level API", "Catalyst optimized"] },
  { question: "Why can a DataFrame be faster than an RDD?", difficulty: "Intermediate", hint: "Consider how named columns and expressions help Spark understand a query.", answer: "DataFrame expressions give the Catalyst Optimizer a logical description of the work. Spark can simplify expressions, remove unused columns, push eligible filters toward the source, and select physical strategies. Arbitrary RDD functions do not expose the same structure. DataFrames are often faster for table-based work, but performance depends on the workload and execution plan.", simple: "Spark can see the steps in a column calculation and look for shortcuts. With custom RDD code, many of those details are hidden from its query optimizer.", example: "If a query needs two columns out of fifty, a suitable columnar source can avoid reading the unused columns.", checks: ["Mentioned Catalyst and structured expressions", "Named a concrete optimization", "Avoided claiming DataFrames are always faster"], follow: "Will every filter be pushed into the data source?", followAnswer: "No. It depends on the source and the expression. Inspect the execution plan to see what was pushed down.", terms: ["Catalyst Optimizer", "Physical Plan"] },
  { question: "What does lazy evaluation mean in Spark?", difficulty: "Beginner", hint: "Separate describing a transformation from requesting a result.", answer: "Transformations describe new datasets without immediately calculating all their records. An action such as collect(), count(), or a write triggers the necessary computation. This lets Spark plan the work before running it. Some operations can still perform metadata or schema-related work earlier.", simple: "Writing the recipe is different from cooking the meal. Transformations describe the recipe; an action asks Spark to produce the result.", example: "Calling rdd.map(lambda x: x * 2) describes a calculation. Calling collect() on that new RDD requests its values.", checks: ["Distinguished transformations from actions", "Named an action", "Explained the planning benefit"], follow: "Does creating a transformed RDD change the original?", followAnswer: "No. It creates a new RDD description while leaving the original unchanged.", terms: ["Transformations", "Actions", "Immutable collection"] },
  { question: "Why is collect() risky on a large dataset?", difficulty: "Beginner", hint: "Where do all the returned records end up?", answer: "collect() brings all result records into the driver process. A large result can exhaust driver memory and fail the application. I use bounded previews for inspection and distributed writes for large outputs. I only collect when the result is known to fit safely in memory.", simple: "A group of computers may hold far more data than your main program can store. collect() tries to bring that result into the main program at once.", example: "Inspect a few DataFrame rows with show(5), or write a large result to storage instead of collecting it.", checks: ["Identified driver memory as the risk", "Suggested a bounded preview or distributed write", "Explained when collecting is reasonable"], follow: "Does show(5) always make the entire query cheap?", followAnswer: "No. It bounds the displayed result, but upstream joins, sorting, or aggregations may still require substantial work.", terms: ["Actions"] },
  { question: "What causes a Shuffle, and why does it matter?", difficulty: "Intermediate", hint: "Think about records with the same key needing to meet on one worker.", answer: "A shuffle redistributes data across partitions. Key-based aggregations, many joins, and repartitioning can require it. Network transfer, serialization, disk I/O, and uneven keys can make it expensive. I inspect the plan and task metrics before choosing an appropriate partition strategy or join approach.", simple: "Imagine sorting cards held by several people so matching cards end up together. Moving those cards takes time, especially if one person receives most of them.", example: "Grouping sales by customer can move records so all sales for a customer can be combined. A very large customer may create uneven work.", checks: ["Explained movement across partitions", "Named an operation that may shuffle", "Mentioned cost or uneven key distribution"], follow: "Does every join need to shuffle both sides?", followAnswer: "No. A suitable broadcast join can avoid shuffling the large side, and existing partitioning can also influence the chosen plan.", terms: ["Partitioning", "execution plan"] },
  { question: "How would you compare an RDD and DataFrame implementation fairly?", difficulty: "Advanced", hint: "Keep the result, input, environment, and execution conditions comparable.", answer: "I use equivalent input and logic, verify matching results, and trigger actual execution with comparable actions. I control resource settings, cache state, and warm-up effects, repeat measurements, and inspect plans and task metrics. I avoid drawing conclusions from timing only transformation definitions or from a tiny toy dataset.", simple: "Compare two ways of doing the same job under similar conditions. Time the completed job, not just writing down its instructions.", example: "Compare equivalent aggregations on representative data, verify the outputs, then measure repeated runs with a documented caching policy.", checks: ["Required equivalent logic and correct results", "Triggered execution with actions", "Controlled conditions and repeated measurements"], follow: "Why can timing map() alone be misleading?", followAnswer: "Because map() usually describes a lazy transformation. The expensive processing is triggered later by an action.", terms: ["execution plan", "Actions"] },
];

type Attempt = {draft:string; hint:boolean; answer:boolean; follow:boolean; checks:boolean[]};
export function InterviewPractice() {
  const [index,setIndex]=useState(0);
  const [attempts,setAttempts]=useState<Attempt[]>(()=>questions.map(q=>({draft:"",hint:false,answer:false,follow:false,checks:q.checks.map(()=>false)})));
  const question=questions[index]; const attempt=attempts[index];
  function update(patch:Partial<Attempt>){setAttempts(previous=>previous.map((value,i)=>i===index?{...value,...patch}:value));}
  return <div className="interview-practice">
    <div className="interview-meta"><span>Question {index+1} of {questions.length}</span><span>{question.difficulty}</span></div>
    <h3 className="interview-question"><GlossaryText>{question.question}</GlossaryText></h3>
    <p className="interview-caption">Try answering aloud or write a draft before revealing the model answer.</p>
    <label htmlFor="interview-draft" className="interview-label">Your answer <span>(optional)</span></label>
    <textarea id="interview-draft" value={attempt.draft} onChange={event=>update({draft:event.target.value})} placeholder="Start with your choice, explain why, then give an example…"/>
    <p className="interview-caption">Drafts stay while you move between these questions; refreshing the page clears them.</p>
    <div className="interview-actions"><button aria-expanded={attempt.hint} onClick={()=>update({hint:!attempt.hint})}>{attempt.hint?"Hide hint":"Give me a hint"}</button><button className="interview-primary" aria-expanded={attempt.answer} onClick={()=>update({answer:!attempt.answer})}>{attempt.answer?"Hide model answer":"Show model answer"}</button></div>
    {attempt.hint&&<p className="interview-hint">{question.hint}</p>}
    {attempt.answer&&<div className="interview-answer">
      <section><h4>Interview-ready answer</h4><p><GlossaryText>{question.answer}</GlossaryText></p></section>
      <section><h4>In simple words</h4><p>{question.simple}</p></section>
      <section><h4>A concrete example</h4><p><GlossaryText>{question.example}</GlossaryText></p></section>
      <div className="interview-terms">Hover for a simple explanation: {question.terms.map(term=><SimpleExplanation key={term} label={term}/>)}</div>
      <fieldset><legend>Check your own answer</legend><p className="interview-caption">These are reflection prompts, not an automatic grade.</p>{question.checks.map((check,i)=><label key={check}><input type="checkbox" checked={attempt.checks[i]} onChange={event=>update({checks:attempt.checks.map((value,j)=>j===i?event.target.checked:value)})}/>{check}</label>)}</fieldset>
      <section className="interview-follow"><h4>Interviewer follow-up</h4><p><GlossaryText>{question.follow}</GlossaryText></p><button aria-expanded={attempt.follow} onClick={()=>update({follow:!attempt.follow})}>{attempt.follow?"Hide explanation":"Reveal explanation"}</button>{attempt.follow&&<p><GlossaryText>{question.followAnswer}</GlossaryText></p>}</section>
    </div>}
    <nav className="interview-navigation" aria-label="Interview questions"><button disabled={index===0} onClick={()=>setIndex(index-1)}>← Previous question</button><span aria-live="polite">{index+1} / {questions.length}</span><button disabled={index===questions.length-1} onClick={()=>setIndex(index+1)}>Next question →</button></nav>
    {index===questions.length-1&&<p className="interview-caption">You’ve reached the last question. Use Previous to revisit your drafts and self-checks.</p>}
  </div>;
}
