"use client";
import { useState, type ReactNode } from "react";
import { ArrowDown, ArrowRight, BookOpen, Database, Eye, Network, Send, Users } from "lucide-react";
import { GlossaryText } from "@/components/glossary";
import { KafkaArchitectureReviewLab } from "@/components/kafka-architecture-review-lab";
import { useWalkthrough, WalkthroughControls } from "@/components/walkthrough-controls";
import { assignPartitions, eventSnapshot, keyRoutes, lag, orderEvent, recoveryTrace, replicaSnapshot, streamTotals, teachingPartition, type DeliveryMode } from "@/lib/kafka-model";
import type { KafkaLesson } from "@/lib/kafka-lessons";

function Card({title,children,active=false}:{title:string;children:ReactNode;active?:boolean}){return <div className={"topic-box kafka-object"+(active?" kafka-active":"")}><h4>{title}</h4>{children}</div>;}
function Flow({items}:{items:string[]}){return <div className="kafka-flow">{items.map((item,i)=><div key={item}><span>{item}</span>{i<items.length-1&&<ArrowRight size={17} aria-hidden="true"/>}</div>)}</div>;}
function PartitionLog({partition,offsets,highlight,selected,onSelect}:{partition:number;offsets:number[];highlight?:number;selected?:number;onSelect?:(offset:number)=>void}){
  return <div className="kafka-partition"><strong>P{partition}</strong><div className="kafka-records">{offsets.map(offset=>onSelect?<button key={offset} aria-label={`Inspect orders partition ${partition} offset ${offset}`} aria-pressed={selected===offset} className={offset===highlight?"kafka-event-highlight":""} onClick={()=>onSelect(offset)}><small>offset</small>{offset}</button>:<span key={offset} className={offset===highlight?"kafka-event-highlight":""}><small>offset</small>{offset}</span>)}</div></div>;
}
const eventNarration=[
  ["Create an event","Checkout records OrderCreated with a stable event identity. Nothing is in the partition yet."],
  ["Send to orders","The producer serializes the value and sends it to the topic. Consumer processing has not begun."],
  ["Choose P1","For this fixed teaching example, the configured partitioner routes customer 77 to P1. This is not a default-hash calculator."],
  ["Append at P1:211","The leader appends the record at the next position in P1. P0 and P2 have independent offset spaces."],
  ["Consumer reads 211","The assigned group member fetches the record. Reading does not delete it or prove that its effect completed."],
  ["Process the order","The application completes its effect. The durable group commit is still 211; a crash here could cause replay."],
  ["Commit next offset 212","The group records 212 for P1. A normal restart resumes there if the offset is still valid and retained."],
];
function FollowEvent(){const controls=useWalkthrough(7);const state=eventSnapshot(controls.step);return <>
  <p className="spark-caption">Fixed teaching trace · no cluster connected · replication is explored separately.</p>
  <div className="kafka-event-layout"><div className="kafka-event-path"><Card title="Producer · checkout" active={controls.step<3}><div className="kafka-event"><Send size={16}/><strong>evt-1042 · OrderCreated</strong><span>key: customer 77 · amount: 499</span><small>{controls.step===0?"Created locally":controls.step===1?"Sent to orders":`Routed to P${state.partition}`}</small></div></Card><ArrowDown className="topic-down" size={18}/><Card title="Topic: orders · broker log" active={controls.step===3}>{state.logs.map((offsets,p)=><PartitionLog key={p} partition={p} offsets={offsets} highlight={p===1?state.offset??undefined:undefined}/>)}</Card><ArrowDown className="topic-down" size={18}/><Card title="Group: analytics · Consumer B owns P1" active={state.read}><p>{!state.read?"Waiting to fetch the new event":!state.processed?"Fetched evt-1042 · not processed": "Processed evt-1042 · one effect"}</p><div className="kafka-metrics"><span>Committed next <strong>{state.committed}</strong></span><span>Record retained <strong>{state.offset===null?"Not appended":"Yes"}</strong></span></div></Card></div><div className="kafka-explanation"><span className="spark-index">{controls.step+1}/7</span><h3>{eventNarration[controls.step][0]}</h3><p aria-live="polite">{eventNarration[controls.step][1]}</p><pre className="spark-output">{JSON.stringify(orderEvent,null,2)}</pre></div></div><WalkthroughControls state={controls} stableNavigation/>
  </>;}
function Intro(){return <><div className="kafka-flow"><Card title="Producers"><p>Checkout · payments · shipping</p></Card><ArrowRight aria-hidden="true"/><Card title="Kafka"><p>Retained event streams</p></Card><ArrowRight aria-hidden="true"/><Card title="Independent consumers"><p>Fulfillment · analytics · fraud</p></Card></div><Flow items={["Event","Producer","Topic","Partition","Consumer"]}/><p className="topic-note">Consumers pull at their own pace. A slow consumer still needs enough retention and capacity to recover.</p></>;}
function Partitions(){const [count,setCount]=useState(3);const [record,setRecord]=useState({p:0,o:0});return <><div className="spark-actions">{[1,3].map(n=><button key={n} aria-pressed={count===n} onClick={()=>{setCount(n);setRecord({p:0,o:0});}}>{n} {n===1?"partition":"partitions"}</button>)}</div><p className="spark-caption">Two separate teaching layouts, not an online topic-resize operation. Click any record.</p>{Array.from({length:count},(_,p)=><PartitionLog key={p} partition={p} offsets={[0,1,2]} selected={record.p===p?record.o:undefined} onSelect={o=>setRecord({p,o})}/>)}<p className="spark-answer" aria-live="polite">Selected coordinate: <strong>orders / P{record.p} / offset {record.o}</strong>. {count} {count===1?"partition permits at most one active owning member":"partitions permit up to three active owning members"} in an ordinary consumer group. Real offset sequences may contain gaps.</p></>;}
function Brokers(){const [broker,setBroker]=useState(1);return <><div className="kafka-three">{[1,2,3].map(b=><button className="topic-box" aria-pressed={broker===b} key={b} onClick={()=>setBroker(b)}><Database size={22}/><strong>Broker {b}</strong><span>orders P{b-1} · leader</span></button>)}</div><p className="spark-answer">Broker {broker} hosts the leader for orders P{broker-1} in this placement sketch. A broker can host many replicas from many topics.</p><Flow items={["Producer finds leader","Broker serves partition","Consumer fetches"]}/><p className="topic-note">Only leader placement is shown. Replication adds copies across brokers, not new logical partition IDs. KRaft controllers manage metadata.</p></>;}
function Keys(){const [key,setKey]=useState("101");const [events,setEvents]=useState<{key:string;p:number}[]>([]);const p=teachingPartition(key)!;return <><p>Explicit classroom routing: 101 → P2 · 205 → P0 · 330 → P1. Stable routes for this example only.</p><div className="spark-actions"><label>Customer key <select value={key} onChange={e=>setKey(e.target.value)}>{Object.keys(keyRoutes).map(k=><option key={k}>{k}</option>)}</select></label><button disabled={events.length>=8} onClick={()=>setEvents(rows=>[...rows,{key,p}])}>Append teaching event</button><button disabled={!events.length} onClick={()=>setEvents([])}>Reset</button></div><Flow items={[`key: ${key}`,"Teaching routing table",`Partition ${p}`]}/>{[0,1,2].map(partition=><div className="kafka-partition" key={partition}><strong>P{partition}</strong><div className="kafka-records">{events.filter(e=>e.p===partition).map((e,offset)=><span key={offset}><small>offset {offset}</small>key {e.key}</span>)}{!events.some(e=>e.p===partition)&&<small>Empty</small>}</div></div>)}<p role="status" className="spark-caption">{events.length}/8 teaching records. Same-key records share a partition under this fixed mapping. Kafka clients use configured partitioning behavior; key serialization and partition count matter.</p></>;}
function Groups(){const [members,setMembers]=useState(["A","B","C"]);const [failed,setFailed]=useState(false);const assignments=assignPartitions(members);return <><p className="spark-caption">Ordinary consumer group · three partitions · deterministic teaching assignment, not a real assignor prediction.</p><div className="spark-actions"><button disabled={members.includes("D")||failed} onClick={()=>setMembers(m=>[...m,"D"])}>Add Consumer D</button><button disabled={!members.includes("B")||failed} onClick={()=>setFailed(true)}>Consumer B crashes</button><button disabled={!failed} onClick={()=>{setMembers(m=>m.filter(x=>x!=="B"));setFailed(false);}}>Complete reassignment</button><button onClick={()=>{setMembers(["A","B","C"]);setFailed(false);}}>Reset</button></div><div className="kafka-members">{members.map(m=><Card key={m} title={`Consumer ${m}`} active={m==="B"&&failed}><Users size={20}/><p>{m==="B"&&failed?"Failed · affected partitions await reassignment":assignments[m].length?assignments[m].map(p=>`P${p}`).join(" + "):"Idle · no partition assigned"}</p></Card>)}</div><p className="spark-answer" role="status">{failed?"B stopped processing. Failure detection and group coordination take time. Use Complete reassignment to inspect one possible stable assignment.":"Each partition has exactly one owner in this group’s stable assignment. Another group has its own independent owners and progress."}</p><p className="topic-note">Reassignment can replay work not safely committed. Exact transitions depend on the group protocol and assignor.</p></>;}
function OffsetSuccess(){const controls=useWalkthrough(5);const commit=controls.step>=3?212:211;const descriptions=["Start: group committed-next is 211.","Fetch P1:211. Fetching is not processing.","Process 211 successfully; durable commit remains 211.","Commit 212, the next offset to process.","Restart: read from committed-next 212 (assuming still valid)."];
return <><PartitionLog partition={1} offsets={[210,211,212,213]} highlight={controls.step===4?212:211}/><div className="kafka-metrics"><span>Processed through <strong>{controls.step>=2?211:210}</strong></span><span>Committed next <strong>{commit}</strong></span><span>On restart <strong>{commit}</strong></span></div><p className="kafka-step-description" aria-live="polite">{descriptions[controls.step]}</p><WalkthroughControls state={controls} stableNavigation/></>;}
function Replicas(){const controls=useWalkthrough(5);const state=replicaSnapshot(controls.step);const descriptions=["P0 leader is on Broker 1. Three replicas are initially in sync; the new event has not been appended.","The new record is appended on the leader. In this trace the acknowledgement is still pending.","Both followers have copied the record. All three current ISR members have it; acks=all completes.","Broker 1 fails. The two surviving copies have the acknowledged record; writes pause while leadership is coordinated.","Broker 2 becomes the eligible leader in this example. Clients refresh metadata. Two ISR members satisfy min.insync.replicas=2."];return <><p className="spark-caption">One partition · RF=3 · min ISR=2 · acks=all · illustrative failure sequence.</p><div className="kafka-three">{[1,2,3].map(b=><Card key={b} title={`Broker ${b}`} active={state.leader===b&&state.failed!==b}><p>{state.failed===b?"✕ Offline":state.leader===b?"P0 · leader":"P0 · follower"}</p><div className="kafka-records"><span className={state.copies[b-1]?"kafka-event-highlight":""}>{state.copies[b-1]?"evt-1042 copied":"New event absent"}</span></div></Card>)}</div><div className="kafka-metrics"><span>Producer acknowledgement <strong>{state.acknowledged?"Received":"Pending"}</strong></span><span>Leadership <strong>{state.available?`Broker ${state.leader}`:"Election pending"}</strong></span></div><p className="kafka-step-description" aria-live="polite">{descriptions[controls.step]}</p><WalkthroughControls state={controls} stableNavigation/></>;}
function Recovery({mode}:{mode:DeliveryMode}){const frames=recoveryTrace(mode);const controls=useWalkthrough(frames.length);const frame=frames[controls.step];return <><PartitionLog partition={1} offsets={[210,211,212]} highlight={frame.next}/><div className="kafka-metrics"><span>Committed next <strong>{frame.committed}</strong></span><span>External effects <strong>{frame.effects}</strong></span><span>Application next <strong>{frame.next}</strong></span></div><div className="kafka-step-description" aria-live="polite"><strong>{frame.title}</strong><p>{frame.note}</p></div><WalkthroughControls state={controls} stableNavigation/></>;}
function Delivery(){const [mode,setMode]=useState<DeliveryMode>("at-least-once");return <><div className="spark-actions">{(["at-least-once","at-most-once"] as const).map(m=><button key={m} aria-pressed={mode===m} onClick={()=>setMode(m)}>{m}</button>)}</div><p className="spark-caption">Compare an illustrative crash window with naive external effects. Not a transaction simulator.</p><Recovery key={mode} mode={mode}/><details><summary>What about exactly-once?</summary><p>Kafka transactions can coordinate Kafka output records and input offsets with correctly configured readers. An external payment, email or database write is not automatically included. Use destination-supported idempotency or coordinated transactions where appropriate.</p></details><Flow items={["P0: A → B → C","No global ordering relation","P1: D → E → F"]}/></>;}
function Schema(){const [breaking,setBreaking]=useState(false);const value=breaking?{order_id:1042,amount:{value:499}}:{order_id:1042,amount:499,currency:"INR"};const encoded=JSON.stringify(value);return <><div className="spark-actions"><button aria-pressed={!breaking} onClick={()=>setBreaking(false)}>Add optional currency</button><button aria-pressed={breaking} onClick={()=>setBreaking(true)}>Change amount type</button></div><Flow items={["Object","UTF-8 JSON bytes","Existing reader"]}/><pre className="spark-output">{encoded}</pre><p className={breaking?"spark-warning":"spark-answer"} role="status">{breaking?"Reader validation fails: expected numeric amount, received an object.":"This example reader accepts numeric amount and ignores unknown currency. Other readers/formats may reject the addition."}</p><div className="kafka-three"><Card title="JSON"><p>Text representation; agree on validation and meaning.</p></Card><Card title="Avro"><p>Writer/reader schemas and resolution rules.</p></Card><Card title="Protobuf"><p>Field identifiers, types and evolution rules.</p></Card></div></>;}
function Connect(){const [side,setSide]=useState("source");return <><Flow items={["PostgreSQL","Source connector","Kafka orders","Sink connector","Warehouse"]}/><div className="spark-actions"><button aria-pressed={side==="source"} onClick={()=>setSide("source")}>Inspect source</button><button aria-pressed={side==="sink"} onClick={()=>setSide("sink")}>Inspect sink</button></div><p className="spark-answer">{side==="source"?"Source responsibilities: capture/poll changes, maintain source progress, map keys and values, handle snapshots and deletes according to plugin capabilities.":"Sink responsibilities: read Kafka records, apply destination writes, coordinate progress, handle retries and duplicate delivery according to the sink contract."}</p><p className="topic-note">Architecture illustration only. Installed plugins, converters, approved credentials and a Connect deployment are required.</p></>;}
function Streams(){const controls=useWalkthrough(4);const rows=[["IN",499],["US",200],["IN",-1],["IN",101]] as const;return <><Flow items={["orders","filter amount > 0","group by region","aggregate","sales_by_region"]}/><div className="kafka-two"><Card title={controls.step===0?"Input events":"Accepted events"}><table className="kafka-table"><thead><tr><th>Region</th><th>Amount</th><th>Status</th></tr></thead><tbody>{rows.map(([region,amount],i)=><tr key={i} className={controls.step>0&&amount<0?"kafka-rejected":""}><td>{region}</td><td>{amount}</td><td>{controls.step>0?(amount>0?"Keep":"Filtered"):"Input"}</td></tr>)}</tbody></table></Card><Card title={controls.step>=3?"Updated totals":"Processing state"}>{controls.step===0?<p>No processing yet.</p>:controls.step===1?<p>Three positive-value events remain.</p>:controls.step===2?<p>IN: 499 + 101<br/>US: 200</p>:Object.entries(streamTotals()).map(([region,total])=><p key={region}><strong>{region}: {total}</strong></p>)}</Card></div><p className="kafka-step-description" aria-live="polite">{["Start with four input events.","Apply the positive-amount teaching rule.","Bring equal region keys together. A real topology may repartition here.","Update per-region state. Define output update semantics, recovery and time policy in a real application."][controls.step]}</p><WalkthroughControls state={controls} stableNavigation/></>;}
function Production(){const [commit,setCommit]=useState(104);const [failure,setFailure]=useState("poison");return <><label>Committed next: {commit}<input aria-label="Committed next offset" type="range" min={100} max={106} value={commit} onChange={e=>setCommit(Number(e.target.value))}/></label><div className="kafka-metrics"><span>Log end <strong>106</strong></span><span>Committed next <strong>{commit}</strong></span><span>Offset gap <strong>{lag(106,commit)}</strong></span></div><p className="spark-caption">Changing this slider changes only the teaching model. It does not process events or commit to Kafka.</p><div className="spark-actions"><button aria-pressed={failure==="poison"} onClick={()=>setFailure("poison")}>Invalid schema</button><button aria-pressed={failure==="network"} onClick={()=>setFailure("network")}>Temporary network failure</button></div><p className="spark-answer">{failure==="poison"?"Repeated decoding failure: investigate the record contract. Use an approved durable quarantine/replay policy; do not silently commit past the record.":"Transient failure: use bounded retries with backoff and monitor availability. A timeout may hide a successful write, so replay-safe effects still matter."}</p></>;}
export function KafkaConcept({lesson,onTab}:{lesson:KafkaLesson;onTab?:(tab:string)=>void}){const visual=lesson.visual;if(lesson.id==="architecture-review")return <KafkaArchitectureReviewLab/>;return <>
  <h2><BookOpen size={22}/>{lesson.title}</h2><p><GlossaryText>{lesson.concepts[0][1]}</GlossaryText></p>
  <section className="topic-visual kafka-visual"><h3>{visual==="event"||visual==="review"?<Eye size={20}/>:<Network size={20}/>} {visual==="event"||visual==="review"?"Follow the Event":visual==="groups"?"Scale the consumer group":visual==="replicas"?"Follow the replicas": "See the mental model"}</h3>
  {visual==="intro"?<Intro/>:visual==="event"?<FollowEvent/>:visual==="partitions"?<Partitions/>:visual==="brokers"?<Brokers/>:visual==="keys"?<Keys/>:visual==="groups"?<Groups/>:visual==="offsets"?<OffsetSuccess/>:visual==="replicas"?<Replicas/>:visual==="delivery"?<Delivery/>:visual==="schema"?<Schema/>:visual==="connect"?<Connect/>:visual==="streams"?<Streams/>:visual==="production"?<Production/>:<><FollowEvent/><details><summary>Inspect broker placement and replication contract</summary><Brokers/><p>Use an intentional replica/ISR policy and eligible leader election. These controls do not run infrastructure.</p></details><details><summary>Inspect application boundaries</summary><Flow items={["orders topic","analytics-v1 + fulfillment-v1","Separate progress and sink contracts"]}/><p>Use order_id to group an order’s events; event_id to identify replays. Independent groups each need the stream.</p></details></>}
  </section><div className="spark-concepts">{lesson.concepts.slice(1).map(([title,body])=><article key={title}><h3>{title}</h3><p><GlossaryText>{body}</GlossaryText></p></article>)}</div><p className="spark-answer"><strong>Key takeaway: </strong><GlossaryText>{lesson.takeaway}</GlossaryText></p><button className="spark-primary" onClick={()=>onTab?.("Examples")}>Explore the matching example →</button>
  </>;}
