"use client";
import { useState } from "react";
import { Eye, ArrowRight, Lightbulb, MessageSquare } from "lucide-react";
import { motion, useReducedMotion } from "framer-motion";
import { DarkCodeCard } from "@/components/rdd-dataframe-experience";
import { useWalkthrough, WalkthroughControls } from "@/components/walkthrough-controls";
import { evaluateFilter, filterModes, filterQuery, filterReason, filterRows, predicate, type FilterMode } from "@/lib/where-lab";

export function WhereLearningLab(){
  const [mode,setMode]=useState<FilterMode>("age"),[age,setAge]=useState(25);
  const [prediction,setPrediction]=useState<number[]>([]),[checked,setChecked]=useState(false);
  const [draft,setDraft]=useState(""),[showAnswer,setShowAnswer]=useState(false),[rubric,setRubric]=useState<boolean[]>([false,false,false]);
  const [challenge,setChallenge]=useState(false);
  const steps=useWalkthrough(filterRows.length+1),reduced=useReducedMotion();
  const correct=filterRows.filter(r=>evaluateFilter(r,mode,age)==="TRUE").map(r=>r.id);
  const mismatches=filterRows.filter(r=>prediction.includes(r.id)!==correct.includes(r.id)).length;
  const current=checked&&steps.step>0?filterRows[steps.step-1]:null;
  const passed=checked?filterRows.slice(0,steps.step).filter(r=>correct.includes(r.id)):[];
  function reset(nextMode=mode,nextAge=age){setMode(nextMode);setAge(nextAge);setChecked(false);setPrediction([]);steps.change(0);setShowAnswer(false);setChallenge(false);}
  return <div className="where-lab">
    <header className="where-heading"><span><Eye size={23}/></span><div><small>LEARN BY DOING · WHERE</small><h2>Who gets invited?</h2><p>Your team needs a customer list. Make a prediction, then watch each row face the condition.</p></div></header>
    <div className="where-mission"><strong>01 · Set the rule</strong><div className="where-rule"><label>Filter <select value={mode} onChange={e=>reset(e.target.value as FilterMode)}>{filterModes.map(m=><option value={m.id} key={m.id}>{m.label}</option>)}</select></label>{mode==="age"&&<label>Age greater than <input type="number" min={0} max={100} value={age} onChange={e=>{const value=Number(e.target.value);reset(mode,Math.max(0,Math.min(100,Number.isFinite(value)?value:0)));}}/></label>}<code>{predicate(mode,age)}</code></div><p>Start with customers older than 25. Later, change the rule and explore missing city values.</p></div>
    <div className="where-workspace">
      <section className="where-source"><h3>02 · Predict the result</h3><p>Select everyone you expect to pass. Select nobody if you expect an empty result.</p><div className="where-table-scroll"><table><caption>customers · source data (never modified)</caption><thead><tr><th>Keep?</th><th>Name</th><th>City</th><th>Age</th><th>Test</th></tr></thead><tbody>{filterRows.map((r,i)=>{const evaluated=checked&&i<steps.step,result=evaluateFilter(r,mode,age);return <tr key={r.id} className={current?.id===r.id?"where-row-current":evaluated?(result==="TRUE"?"where-row-pass":"where-row-out"):""}><td><input type="checkbox" aria-label={`Predict ${r.name} passes`} disabled={checked} checked={prediction.includes(r.id)} onChange={e=>setPrediction(p=>e.target.checked?[...p,r.id]:p.filter(id=>id!==r.id))}/></td><th scope="row">{r.name}</th><td>{r.city??<em>NULL</em>}</td><td>{r.age}</td><td>{evaluated?<span className={`where-truth where-${result.toLowerCase()}`}>{result}</span>:"—"}</td></tr>;})}</tbody></table></div><button className="spark-primary" disabled={checked} onClick={()=>{setChecked(true);steps.change(0);}}>Lock prediction & trace →</button>{checked&&<p role="status" className="where-feedback">{mismatches===0?"Your prediction matches. Trace the rows to explain why.":`${mismatches} of your row predictions differ. Trace them to find out why.`}</p>}</section>
      <section className="where-result"><h3>03 · Build the result</h3><div className="where-gate"><span>One row</span><ArrowRight size={16}/><strong>WHERE<br/><code>{predicate(mode,age)}</code></strong><ArrowRight size={16}/><span>TRUE only</span></div><div className="where-result-list" aria-label="Rows returned so far">{passed.length?passed.map(r=><motion.div key={r.id} initial={{opacity:reduced?1:0,x:reduced?0:-12}} animate={{opacity:1,x:0}} transition={{duration:.22}}><strong>{r.name}</strong><span>{r.city??"NULL"}</span><span>{r.age}</span></motion.div>):<p>{!checked?"Your result will appear here.":steps.step===0?"No rows evaluated yet.":"No evaluated rows have passed."}</p>}</div><p className="where-count">{checked?steps.step:0}/{filterRows.length} rows tested · {passed.length} returned so far</p></section>
    </div>
    <section className="where-trace"><div className="where-narration" aria-live="polite"><strong>{!checked?"Predict first—then follow the data.":current?`Testing ${current.name}: ${evaluateFilter(current,mode,age)}`:"Ready to test Alice"}</strong><p>{!checked?"The checkboxes are your hypothesis, not a filter on the source data.":current?filterReason(current,mode,age):"Click Next to substitute each row’s value into the condition. This is a teaching model of SQL semantics, not a database’s physical execution plan."}</p></div><div className="where-controls">{checked?<WalkthroughControls state={steps} stableNavigation/>:<span>Step controls unlock after you make your prediction.</span>}<button onClick={()=>reset()}>Try a new prediction</button></div></section>
    <div className="where-code-grid"><DarkCodeCard title="SQL · matching your current rule" code={filterQuery(mode,age)}/><aside><h3><Lightbulb size={18}/> What actually changed?</h3><p>The result contains only rows where the condition is <strong>TRUE</strong>. FALSE and UNKNOWN are excluded. The original customers table is unchanged.</p><p><code>ORDER BY id</code> makes the display order explicit. WHERE itself does not promise a result order.</p></aside></div>
    <section className="where-challenge"><h3>04 · Break your assumption</h3><p><strong>Find the customer whose city is missing.</strong> Try <code>city = NULL</code>, then <code>city IS NULL</code>. Predict and trace both. Why do they disagree?</p><div className="spark-actions"><button onClick={()=>reset("equals-null")}>Try = NULL</button><button onClick={()=>reset("is-null")}>Try IS NULL</button><button onClick={()=>setChallenge(true)}>Check my current solution</button></div>{challenge&&<p role="status">{mode==="is-null"&&checked&&steps.step===filterRows.length?"Solved: only Dan is returned. IS NULL tests missingness; it does not compare two known values.":"Use the rule that tests missingness, predict the rows, then finish the trace. An ordinary comparison with NULL cannot return TRUE."}</p>}</section>
    <section className="where-interview"><h3><MessageSquare size={19}/>05 · Explain it to an interviewer</h3><p>“Why does <code>city &lt;&gt; &apos;Chennai&apos;</code> return Bob but not Dan? How would you include customers whose city is unknown?”</p><button onClick={()=>reset("not-city")}>Investigate this scenario ↑</button><label htmlFor="where-explanation">Explain using the rows you just saw</label><textarea id="where-explanation" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Bob passes because… Dan is excluded because… To include unknown cities, I would…"/><p className="spark-caption">Draft stays while this view is open. Copy it into your lesson Notes to keep it.</p><button className="spark-primary" onClick={()=>setShowAnswer(v=>!v)}>{showAnswer?"Hide explanation":"Compare my reasoning"}</button>{showAnswer&&<div className="spark-answer"><p>Bob’s city is Mumbai, so the comparison is TRUE. Dan’s city is NULL, so the comparison is UNKNOWN—not TRUE. To include both, use <code>WHERE city &lt;&gt; &apos;Chennai&apos; OR city IS NULL</code>. This returns Bob and Dan without changing the source data.</p><fieldset><legend>Check your explanation · self-review, not automated grading</legend>{["I used Bob and Dan as concrete examples.","I distinguished FALSE from UNKNOWN and stated that WHERE keeps only TRUE.","I included OR city IS NULL to express the missing-city requirement."].map((text,i)=><label key={text}><input type="checkbox" checked={rubric[i]} onChange={e=>setRubric(r=>r.map((v,j)=>j===i?e.target.checked:v))}/>{text}</label>)}</fieldset></div>}</section>
  </div>;
}
