import {dependenciesSatisfied,executionScenario,taskStateMeaning,type ExecutionScenario,type TaskState} from "@/lib/airflow-execution";
import type {AirflowLesson} from "@/lib/airflow-lessons";

export const stateLabels:Record<TaskState,string>={none:"Not ready",scheduled:"Scheduled",queued:"Queued",running:"Running",success:"Success",failed:"Failed",up_for_retry:"Retrying",upstream_failed:"Upstream failed",skipped:"Skipped",up_for_reschedule:"Waiting · reschedule"};
export type VisualTaskState=TaskState|"eligible";
export const visualStateLabels:Record<VisualTaskState,string>={...stateLabels,eligible:"Eligible"};
export function taskVisualState(trace:ExecutionScenario,step:number,id:string):VisualTaskState{
 const frame=trace.frames[step],state=frame.states[id];
 if(state!=="none")return state;
 const parents=trace.edges.filter(([,to])=>to===id).map(([from])=>from);
 const rule=id==="join"?"none_failed_min_one_success":"all_success";
 return dependenciesSatisfied(parents.map(parent=>frame.states[parent]),rule)?"eligible":"none";
}
export function taskReason(trace:ExecutionScenario,step:number,id:string){
 const frame=trace.frames[step],state=frame.states[id];
 if(state!=="none")return taskStateMeaning[state];
 const parents=trace.edges.filter(([,to])=>to===id).map(([from])=>from);
 const rule=id==="join"?"none_failed_min_one_success":"all_success";
 if(dependenciesSatisfied(parents.map(p=>frame.states[p]),rule))return "Dependencies satisfied. The scheduler must still evaluate run eligibility and execution limits; ready does not mean running.";
 return `Waiting for upstream: ${parents.filter(p=>frame.states[p]!=="success").map(p=>`${p} (${stateLabels[frame.states[p]]})`).join(", ")}. Trigger rule: ${rule}.`;
}
export function dagTrace(lesson:AirflowLesson,variant:string):ExecutionScenario{
 let trace=executionScenario(lesson.execution??"chain",variant==="Exhaust retries");
 if(lesson.id==="dags-dependencies"&&variant==="Linear chain")trace=executionScenario("chain");
 if(lesson.id==="retries"&&variant==="Success immediately")trace=executionScenario("chain");
 if(lesson.id==="retries"&&variant==="Timeout"){
  const base=executionScenario("chain"),at=base.frames.findIndex(f=>f.focus==="transform"&&f.states.transform==="running");
  const states={...base.frames[at].states,transform:"failed" as TaskState};
  trace={...base,code:"# transform: execution_timeout=timedelta(seconds=30), retries=0\nextract >> transform >> load",frames:[...base.frames.slice(0,at+1),{title:"Execution timeout exceeded",actor:"Task execution",explanation:"Illustrative timeout, not elapsed browser time. AirflowTaskTimeout fails this attempt; retries=0 makes the failure terminal.",focus:"transform",states},{title:"Load cannot run",actor:"Scheduler",explanation:"all_success cannot be met. load becomes upstream_failed without executing.",focus:"load",states:{...states,load:"upstream_failed"}}]};
 }
 if(lesson.id==="trigger-rules"&&variant==="No data path"){
  const swap=(id:string)=>id==="load"?"no_data":id==="no_data"?"load":id;
  trace={...trace,frames:trace.frames.map(f=>({...f,focus:swap(f.focus),title:f.title.replace(/load/g,"no_data"),explanation:f.explanation.replace(/no_data/g,"TEMP").replace(/load/g,"no_data").replace(/TEMP/g,"load"),states:Object.fromEntries(Object.entries(f.states).map(([id,s])=>[swap(id),s]))}))};
 }
 if(lesson.id==="taskflow"){
  const initial=trace.frames[0];
  trace={...trace,code:"@task\ndef extract(): return 150\n@task\ndef transform(amount): return amount + 20\n@task\ndef load(amount): print(amount)\nload(transform(extract()))",frames:[
   {...initial,title:"Define decorated functions",actor:"DAG processor",explanation:"@task wraps Python functions. No business logic has run yet."},
   {...initial,title:"Calls construct task references",actor:"DAG processor",explanation:"load(transform(extract())) builds nodes and output dependencies, not the final integer 170."},...trace.frames]};
 }
 return trace;
}
export const dagChoices:Record<string,string[]>={"dags-dependencies":["Branch and join","Linear chain"],retries:["Fail once, then succeed","Success immediately","Exhaust retries","Timeout"],"trigger-rules":["Load path","No data path"]};
export interface FlowStep {node:number;title:string;explanation:string;value:string;line:number;danger?:boolean}
export interface FlowStory {nodes:{label:string;detail:string}[];code:string[];steps:FlowStep[];caveat:string}
const step=(node:number,title:string,explanation:string,value:string,line:number,danger=false):FlowStep=>({node,title,explanation,value,line,danger});
const nodes=(...items:[string,string][])=>items.map(([label,detail])=>({label,detail}));
export const flowChoices:Record<string,string[]>={architecture:["Healthy dispatch","No worker capacity"],scheduling:["02:00 UTC","06:00 UTC"],"catchup-backfill":["Catchup off","Catchup on","Bounded backfill"],xcom:["Storage reference","Bulk payload (avoid)"],configuration:["Params","Variables","Connections"],monitoring:["Invalid input","Access denied","Queued task"],production:["Idempotent write","Blind append (avoid)"]};
function architecture(choice:string):FlowStory{
 const blocked=choice==="No worker capacity";
 return {nodes:nodes(["DAG processor","Definition → serialized graph"],["Scheduler","Evaluate eligibility"],["Executor","Dispatch work"],["Task execution","Worker / task process"],["State & UI","Metadata + API services"]),code:["# Conceptual responsibilities — not executable code","parse_and_serialize_definition","evaluate_run_and_task_eligibility","dispatch_via_configured_executor","execute_task_body","report_state_via_supported_services"],steps:[step(0,"Discover the DAG","Parsing exposes tasks and edges. It must not perform the ETL itself.","extract → transform → load",1),step(1,"Evaluate eligibility","The scheduler uses orchestration state, dependencies and limits to decide which task can be scheduled.","extract: scheduled",2),step(2,"Submit to executor","The configured executor dispatches the task. Queued is not running.","extract: queued",3),step(3,blocked?"Capacity unavailable":"Execute task body",blocked?"No slot is available. The task stays queued; business code has not begun.":"An execution process runs the task; its placement depends on executor/deployment.",blocked?"queued · waiting for capacity":"extract: running",4,blocked),step(4,"Inspect orchestration state",blocked?"UI/API shows queued. Inspect executor capacity before debugging Python business logic.":"Task SDK/execution API reports state through supported services. UI/API exposes state and logs.",blocked?"UI: queued":"UI: success",5)],caveat:"Simplified Airflow 3.1 control path. Metadata supports scheduling and UI; it is not a downstream ETL task. Tasks do not query the metadata DB directly."};
}
function scheduling(choice:string):FlowStory{
 const hour=choice.startsWith("06")?"06":"02",interval=`Jan 1 ${hour}:00 → Jan 2 ${hour}:00 UTC`;
 return {nodes:nodes(["Timetable",`${hour}:00 UTC daily`],["Data interval","Start included · end excluded"],["DAG run","Created after interval closes"],["Task eligibility","Dependencies + capacity"]),code:["from airflow.timetables.interval import CronDataIntervalTimetable",`schedule=CronDataIntervalTimetable('0 ${Number(hour)} * * *', timezone='UTC')`,"# logical date = interval start in this example","# run is due after interval end","# scheduler evaluates tasks; executor dispatches"],steps:[step(0,"Choose explicit semantics","This lesson uses CronDataIntervalTimetable, not an unspecified cron default.",`${hour}:00 UTC`,1),step(1,"Accumulate a data interval","The interval labels the data to process. It is not the duration of task execution.",interval,2),step(2,"Interval closes; run becomes due","The scheduler may create the scheduled run after Jan 2 at the selected hour, subject to run limits.",`Logical date: Jan 1 ${hour}:00 UTC`,3),step(3,"Evaluate tasks separately","Run creation does not instantly execute tasks. Tasks move scheduled → queued → running as dependencies and capacity permit.","Due time ≠ actual task start",4)],caveat:"Explicit UTC interval timetable. Manual runs and trigger-style timetables can have different semantics; do not use now() to select historical data."};
}
function catchup(choice:string):FlowStory{
 const selected=choice==="Catchup off"?[false,false,true]:[true,true,true],backfill=choice==="Bounded backfill";
 return {nodes:nodes(["Jan 1 → Jan 2",selected[0]?"Selected missing interval":"Not caught up"],["Jan 2 → Jan 3",selected[1]?"Selected missing interval":"Not caught up"],["Jan 3 → Jan 4","Selected interval"],["Run queue","Bound concurrency"]),code:[`catchup=${choice==="Catchup on"?"True":"False"}`,"# Assume Jan 4 03:00 UTC; all intervals closed, no runs exist",backfill?"# Explicit backfill: Jan 1–3; review reprocessing policy":"# Scheduler considers missing eligible intervals","# Per-run interval selects inputs; writes must be idempotent"],steps:[step(0,"Review closed intervals","All intervals are 02:00 UTC to 02:00 UTC. These are historical work units, not task retries.","3 closed intervals · no existing runs",1),step(1,backfill?"Request historical range":"Apply catchup policy",backfill?"An explicit bounded backfill is separate from catchup=False. Review the range and reprocessing policy first.":choice==="Catchup on"?"Missing eligible historical intervals can be scheduled, subject to limits.":"With catchup disabled, only the latest interval is considered here. Old runs are not deleted.",backfill?"Dry-run selection: 3 intervals":`${selected.filter(Boolean).length} interval(s) selected`,2),step(2,"Assign interval-specific input","Each selected run must read its own interval, not latest.csv or today's partition.","[data_interval_start, data_interval_end)",3),step(3,"Queue bounded work","Control active runs and resource pools. This is a selection preview, not a real backfill.",`${selected.filter(Boolean).length} planned run(s)`,3)],caveat:"Assumes no existing runs and an explicit interval timetable. Existing history, reprocessing policy and concurrency limits affect real backfills."};
}
function xcom(choice:string):FlowStory{
 const bad=choice.startsWith("Bulk"),value=bad?"Huge DataFrame — unsuitable payload":'"/data/orders/2026-09-26.parquet"';
 return {nodes:nodes(["Task A","Store bulk data externally"],["XCom","Small task-scoped message"],["Task B","Resolve reference"],["External storage","Read dataset with own access"]),code:["@task","def locate_orders():",'    return "/data/orders/2026-09-26.parquet"',"@task","def consume(path):", "    read_external_dataset(path)","consume(locate_orders())"],steps:[step(0,"Task A produces a reference","A durable file holds the rows. The return value identifies it; the rows do not travel through this arrow.",value,2,bad),step(1,bad?"Reject the mental model":"Publish small return value",bad?"Do not use the lesson's XCom path for a large dataset. Keep data in durable storage and pass a URI.":"TaskFlow can publish the small return value through XCom for this DAG run.",bad?"Use a reference instead":value,2,bad),step(2,"Resolve task output","The downstream task receives the reference after its upstream succeeds.",bad?"Corrected payload: storage URI":value,6),step(3,"Read the actual data","Task B accesses external storage with its own authorized connection. XCom is not the data lake.","Bulk rows: external storage → Task B",5)],caveat:"XCom backends differ, but keep orchestration messages relatively small. Paths here are illustrative; no data or credentials are accessed."};
}
function configuration(choice:string):FlowStory{
 const options:Record<string,[string,string,string]>={Params:["Run-specific validated input",'context["params"]["region"]','region = "APAC"'],Variables:["Shared non-secret configuration",'Variable.get("landing_bucket")','landing_bucket = "orders-demo"'],Connections:["External-system connection configuration",'BaseHook.get_connection("warehouse")',"Connection ID: warehouse · credentials not displayed"]};
 const [purpose,lookup,value]=options[choice];
 return {nodes:nodes([choice,purpose],["Task runtime","Resolve supported configuration"],["Validate","Check expected input"],["Use safely","No secret logging"]),code:["# Illustrative runtime lookup; imports/setup in Examples",lookup,"# Validate required values before external work","# Never print credentials or put secrets in XCom"],steps:[step(0,"Choose the correct source",purpose+". These sources are not interchangeable.",choice,0),step(1,"Resolve at runtime","Use supported APIs and authorized configuration. Avoid unnecessary lookups during DAG parsing.",value,1),step(2,"Check the contract",choice==="Params"?"Params support JSON Schema validation; supported run overrides depend on deployment configuration.":"Confirm required configuration exists and has the expected shape before starting side effects.","Validated configuration, not business data",2),step(3,"Perform authorized work",choice==="Connections"?"The task uses the configured external-system access without exposing secrets in the lesson or logs.":"Use the setting/input consistently for this run. Never treat configuration as a transport for a large dataset.","No credentials displayed",3)],caveat:"Values are fabricated, non-secret teaching examples. Connections may be resolved from configured secret backends; no real lookup occurs."};
}
function monitoring(choice:string):FlowStory{
 const queued=choice==="Queued task",auth=choice==="Access denied";
 const evidence=queued?"State: queued; no task-body log yet":auth?"AuthenticationError: access denied":"ValueError: missing required field amount";
 return {nodes:nodes(["Run overview",queued?"Run waiting":"Run failed"],["Task instance",queued?"load · queued":"validate · failed"],["Evidence","State + educational logs"],["Diagnosis","Likely cause + safe next check"]),code:["# Mock diagnostic evidence — not live logs",queued?"task=load state=queued":"task=validate state=failed",evidence,queued?"# Inspect executor, pools and available slots":auth?"# Inspect connection permissions; never paste credentials":"# Inspect input contract and rejected record"],steps:[step(0,"Locate affected run","Begin with the run and task state, not an assumption that more retries will fix it.",queued?"Run active · load queued":"Run failed · validate failed",1),step(1,"Select the task instance",queued?"Queued means execution has not started. There may be no task-body log to inspect.":"Identify the failed task and attempt before opening its logs.",queued?"load: queued":"validate: failed",1),step(2,"Read the evidence","These are deterministic, sanitized teaching logs. No live Airflow deployment is connected.",evidence,2),step(3,"Choose the next check",queued?"Inspect executor health, pools and concurrency before changing task code.":auth?"Check Connection configuration and authorization. Repeating the same unauthorized request will not grant access.":"Check the schema/input contract. Correct or quarantine bad data; blind retries do not restore missing fields.",queued?"Capacity issue suspected":auth?"Authorization issue suspected":"Input contract issue suspected",3)],caveat:"One example symptom is not a definitive production diagnosis. Inspect state, attempts and surrounding evidence; never log secrets."};
}
function production(choice:string):FlowStory{
 const safe=choice==="Idempotent write";
 return {nodes:nodes(["Interval input","Business key: order 501"],["Attempt 1","Write then lose acknowledgement"],["Retry","Same input · same business key"],["Warehouse result",safe?"One business row":"Duplicate business rows"]),code:["# Teaching write strategy, not runnable database code","key = (order_id, interval_start)",safe?"transactional_upsert(key, values)":"blind_append(values)","# Reconcile results after partial failures"],steps:[step(0,"Bind input to an interval","An intentional rerun must address the same logical data, not a moving latest input.","Order 501 · same interval",1),step(1,"Write succeeds; acknowledgement fails","The external effect may have happened even when the task reports an error.","Warehouse: [501] · task retry pending",2),step(2,"Repeat the attempt",safe?"A defined business key and transactional upsert avoid inserting another copy in this example.":"Blind append inserts the same business row again. Airflow retries do not deduplicate external effects.",safe?"UPSERT 501 → existing row":"APPEND 501 → second row",2,!safe),step(3,"Reconcile business output",safe?"One business row remains. Validate counts and partial-write recovery; idempotency requires deliberate design.":"Two rows represent one order. Correct the write contract, not just the retry count.",safe?"[501] · 1 row":"[501, 501] · 2 rows",3,!safe)],caveat:"Illustrative transactional strategy, not an exactly-once guarantee. Also bound concurrency, avoid heavy parsing-time work, and protect service credentials."};
}
const storyBuilders:Record<string,(choice:string)=>FlowStory>={architecture,scheduling,"catchup-backfill":catchup,xcom,configuration,monitoring,production};
export function flowStory(id:string,choice:string):FlowStory{return storyBuilders[id](choice);}
