import type { SparkLesson } from "@/lib/spark-lessons";
import type { SqlTable } from "@/lib/sql-lessons";

type Question=SparkLesson["quiz"][number];
export type ModelVisual="entities"|"keys"|"cardinality"|"er"|"normalization"|"denormalization"|"workloads"|"facts"|"star"|"snowflake"|"scd"|"analytics";
export interface ModelFrame {title:string;description:string;tables:SqlTable[]}
export interface ModelingLesson extends SparkLesson {
  visual:ModelVisual; question:string; why:string; remember:string; takeaway:string;
  frames:ModelFrame[]; decision:Question; resource:{title:string;url:string};
}
const table=(title:string,columns:string[],rows:SqlTable["rows"]):SqlTable=>({title,columns,rows});
export const modelTables={
  customers:table("customers",["customer_id","name","city"],[[1,"Alice","Chennai"],[2,"Bob","Mumbai"]]),
  products:table("products",["product_id","product","category"],[[10,"Notebook","Stationery"],[20,"Pen","Stationery"]]),
  orders:table("orders",["order_id","customer_id","order_date"],[[501,1,"2026-01-10"],[502,1,"2026-01-12"],[503,2,"2026-01-12"]]),
  lines:table("order_lines",["order_id","line_no","product_id","quantity","unit_price"],[[501,1,10,2,50],[501,2,20,3,10],[502,1,10,1,50],[503,1,20,2,10]]),
  flat:table("Order-line extract · repeated customer/product details",["order_id","line_no","customer","city","product","quantity","unit_price"],[[501,1,"Alice","Chennai","Notebook",2,50],[501,2,"Alice","Chennai","Pen",3,10],[502,1,"Alice","Chennai","Notebook",1,50],[503,1,"Bob","Mumbai","Pen",2,10]]),
  fact:table("fact_sales · one row per order line",["order_id","line_no","customer_key","product_key","date_key","store_key","quantity","revenue"],[[501,1,101,10,20260110,1,2,100],[501,2,101,20,20260110,1,3,30],[502,1,101,10,20260112,1,1,50],[503,1,102,20,20260112,1,2,20]]),
  dimCustomer:table("dim_customer",["customer_key","customer_id","name","city"],[[101,1,"Alice","Chennai"],[102,2,"Bob","Mumbai"]]),
  dimProduct:table("dim_product",["product_key","product","category"],[[10,"Notebook","Stationery"],[20,"Pen","Stationery"]]),
  dimDate:table("dim_date",["date_key","calendar_date","month"],[[20260110,"2026-01-10","2026-01"],[20260112,"2026-01-12","2026-01"]]),
  dimStore:table("dim_store",["store_key","store","region"],[[1,"Web India","India"]]),
  history:table("Type 2 · Alice’s versions (exclusive end_date)",["customer_key","customer_id","name","city","start_date","end_date"],[[101,1,"Alice","Chennai","2026-01-01","2026-02-01"],[205,1,"Alice","Bangalore","2026-02-01",null]]),
};
const t=modelTables;
const frame=(title:string,description:string,...tables:SqlTable[]):ModelFrame=>({title,description,tables});
const q=(question:string,options:string[],correct:number,explanation:string):Question=>({question,options,correct,explanation});
const relational={title:"PostgreSQL · constraints",url:"https://www.postgresql.org/docs/current/ddl-constraints.html"};
const dimensional={title:"Kimball · dimensional design process",url:"https://www.kimballgroup.com/data-warehouse-business-intelligence-resources/kimball-techniques/dimensional-modeling-techniques/four-4-step-design-process/"};
const schema={title:"Microsoft Learn · star schemas and dimensions",url:"https://learn.microsoft.com/en-us/power-bi/guidance/star-schema"};
interface Spec {
  id:string;title:string;visual:ModelVisual;idea:string;question:string;why:string;remember:string;takeaway:string;
  frames:ModelFrame[];decision:Question;hint:string;solution:string;
  interview:[string,string,string]; mistakes:[string,string,string,string,string][];quiz:Question[];
  code?:string;resource?:{title:string;url:string};
}
const specs:Spec[]=[
  {id:"introduction",title:"Data Modeling Introduction",visual:"entities",
    idea:"Data modeling describes the things a system stores, their properties, and how they connect. A useful model also makes the meaning of each row explicit.",
    question:"What does one row mean, and how does it connect to another?",
    why:"If a customer’s name is copied into every order without an update rule, different orders can disagree about the same person.",
    remember:"Start with business rules, not a list of columns. Different workloads can justify different models.",takeaway:"Model the business meaning first; choose tables and keys to preserve it.",
    frames:[frame("Observe the business","Alice places orders 501 and 502; Bob places order 503.",t.flat),frame("Identify the things","Customers exist independently of orders. One customer can place several orders.",t.customers,t.orders),frame("Connect with identity","customer_id connects the rows without using a person’s name as identity.",t.customers,t.orders)],
    decision:q("A store must keep customers even when they have not ordered. Which design fits?",["Store customers only inside orders","Separate customers and orders, linked by customer_id","One table per customer"],1,"An independent customers table can hold a customer with zero orders; orders reference that customer."),
    hint:"Can the model represent a customer before their first purchase?",solution:"Keep customers(customer_id, name, city) and orders(order_id, customer_id, order_date). A customer has zero or many orders; each order belongs to one customer in this scenario.",
    interview:["What makes a data model useful?","It captures entities, row meanings, relationships and constraints that support a business workload. I validate it against example records and queries rather than just drawing boxes.","What changes if orders may be placed by guests?"],
    mistakes:[["Starting with database types","Column types alone do not describe who owns an order.","Write the business rule before choosing types.","order: id, text, text","Each order belongs to one customer; customer_id references customers."],["Using names as identity","Different people can share the same name.","Use a stable identifier and store the name as an attribute.","orders.customer_name = Alice","orders.customer_id = 1"]],
    quiz:[q("Alice has two orders. How many customer rows describe Alice in this current-state model?",["Two","One","One per product"],1,"Customer identity does not depend on how many orders she places."),q("Which is a business rule rather than a data type?",["INTEGER","VARCHAR","Each order belongs to one customer"],2,"The relationship rule guides both the schema and its validation.")],resource:relational},
  {id:"entities",title:"Entities, Attributes & Relationships",visual:"entities",
    idea:"An Entity is something you track, such as a customer. An Attribute describes it, such as a name. A Relationship connects things, such as a customer placing an order.",question:"Is this a thing, a property, or a connection?",
    why:"Separating these ideas prevents a changing description, such as city, from being mistaken for a stable identity.",remember:"An attribute can become an entity when it has its own identity, lifecycle, or relationships.",takeaway:"Customer is the entity, name is an attribute, and places connects Customer to Order.",
    frames:[frame("Find entities","Customer, Order and Product are tracked independently.",t.customers,t.products),frame("Assign attributes","Name and city describe Customer; order_date describes Order.",t.customers,t.orders),frame("Record relationships","The order row carries customer_id. Product membership is recorded through order lines.",t.orders,t.lines)],
    decision:q("Customers can save several addresses, each with a label and validity dates. How should addresses be modeled?",["One comma-separated address field","Address entity linked to Customer","Use city as the customer key"],1,"Addresses now have multiple instances and properties. An address_id and customer_id allow each address to be tracked."),hint:"Look for something that can have multiple instances for one customer.",solution:"Customer(customer_id, name) 1 → 0..many Address(address_id, customer_id, label, city, valid_from, valid_to). Choose shipping address per order when historical delivery details matter.",
    interview:["When does an attribute deserve its own entity?","When it has multiple instances, independent identity or lifecycle, or relationships of its own. A simple current city may be an attribute; multiple shipping addresses can be an entity.","Should changing a saved address rewrite an old order’s shipping address?"],
    mistakes:[["Storing several values in one field","Searching and validating individual values becomes awkward.","Represent repeated items as related rows.","addresses = Chennai, Mumbai","Address rows with their own keys and customer_id"],["Treating the relationship as a name match","Names are not reliable join keys.","Represent the relationship using identifiers.","Match customer_name to name","Match orders.customer_id to customers.customer_id"]],
    quiz:[q("In Customer(customer_id, name, city), what is city?",["Entity","Attribute","Foreign key by definition"],1,"City describes the customer in this particular model."),q("Which phrase describes a relationship?",["Order has an amount","Customer places Order","Customer name is text"],1,"It connects two entity types.")],resource:relational},
  {id:"keys",title:"Keys & Constraints",visual:"keys",
    idea:"A Primary Key uniquely identifies a row and is non-null. A Foreign Key references a key. NOT NULL, UNIQUE and CHECK constraints express additional rules.",question:"Which values identify rows, and which values connect them?",
    why:"Bad keys can create duplicates or orders linked to nonexistent customers. A Surrogate Key separates warehouse identity from a changing Natural Key.",remember:"A Foreign Key does not make its child column unique. Constraint enforcement also depends on the database platform.",takeaway:"Choose stable row identity; validate relationships and business rules separately.",
    frames:[frame("Identify customers","customer_id is unique in customers; name is not an identity guarantee.",t.customers),frame("Allow repeated references","Orders 501 and 502 both reference customer 1. Their own order_id values differ.",t.orders),frame("Test an invalid reference","An order pointing to customer 99 should be rejected by an enforced foreign key.",table("Proposed invalid order",["order_id","customer_id"],[[504,99]]))],
    decision:q("Which column should identify each row in orders, where one customer may buy many times?",["customer_id","order_date","order_id"],2,"order_id distinguishes purchases; customer_id repeats and order_date may be shared."),hint:"Look at Alice’s two orders. Which value is different for each?",solution:"PRIMARY KEY (order_id); customer_id NOT NULL REFERENCES customers(customer_id). Do not add UNIQUE(customer_id) unless the business allows at most one order per customer.",
    interview:["Natural key or surrogate key?","A natural key comes from the business, such as a governed product code. A surrogate key is assigned by the system. Evaluate stability, source collisions and history needs; retain business-key uniqueness rules where appropriate.","Why does adding a surrogate ID not automatically prevent duplicate business events?"],
    mistakes:[["Making customer_id the order primary key","The second order by the same customer would be rejected.","Use order_id as the key and customer_id as a reference.","orders PRIMARY KEY(customer_id)","orders PRIMARY KEY(order_id); FOREIGN KEY(customer_id)"],["Believing a CHECK also forbids NULL","In SQL a CHECK can pass an unknown/null outcome.","Use NOT NULL alongside a numeric range check.","quantity INTEGER CHECK(quantity > 0)","quantity INTEGER NOT NULL CHECK(quantity > 0)"]],
    quiz:[q("Can two orders have the same customer_id foreign key?",["Yes, in this one-to-many model","No, foreign keys are always unique","Only if their order_id is also identical"],0,"The child reference can repeat; order identity must remain unique."),q("What prevents an absent customer_id on a required relationship?",["A foreign key alone","NOT NULL plus the foreign key","An index alone"],1,"Nullability and reference validity are separate rules.")],
    code:"CREATE TABLE customers (\n  customer_id INTEGER PRIMARY KEY,\n  name TEXT NOT NULL\n);\nCREATE TABLE orders (\n  order_id INTEGER PRIMARY KEY,\n  customer_id INTEGER NOT NULL REFERENCES customers(customer_id)\n);",resource:relational},
  {id:"cardinality",title:"Cardinality",visual:"cardinality",
    idea:"Cardinality describes how many records can participate in a Relationship. Minimum participation also matters: zero orders is different from at least one order.",question:"For one row here, how many rows may exist over there?",why:"Wrong cardinality can reject valid data or multiply query results unexpectedly.",remember:"One-to-one rules need uniqueness on the reference; a foreign key alone permits many children.",takeaway:"State both directions and optionality before implementing the relationship.",
    frames:[frame("One customer, several orders","Alice appears once in customers and twice as a reference in orders.",t.customers,t.orders),frame("Many students, many courses","Enrollment records one student-course pair; neither single column is unique.",table("enrollment",["student_id","course_id"],[[1,10],[1,20],[2,10]])),frame("Prevent repeated membership","A composite key on (student_id, course_id) rejects a duplicate enrollment for the same course instance.",table("Unique enrollment pairs",["student_id + course_id"],[["1 + 10"],["1 + 20"],["2 + 10"]]))],
    decision:q("A student takes many courses and a course has many students. Which design represents this?",["course_id on Student only","student_id on Course only","Enrollment(student_id, course_id) between them"],2,"The bridge gives each student-course pairing its own row; model course offerings too if repeat enrollment is allowed."),hint:"Where would a second course for the same student go?",solution:"Student 1 → many Enrollment many ← 1 Course. Use a unique pair (student_id, course_id) for one enrollment per course; add offering_id if the same course can be taken in different terms.",
    interview:["How do you model a many-to-many relationship?","Use an associative entity or bridge that references both sides. Define the grain of that association and its uniqueness rule; properties such as enrollment date belong on that association.","How would retaking a course change the enrollment key?"],
    mistakes:[["Mistaking optionality for maximum count","Zero-or-many and exactly-one are different business rules.","Specify minimum and maximum at both ends.","Customer — Order","Customer has 0..many Orders; each Order has exactly 1 Customer"],["Omitting the bridge","One reference column cannot express many values in both directions.","Introduce a row for each allowed pair.","Student(course_ids = 10,20)","Enrollment(1,10), Enrollment(1,20)"]],
    quiz:[q("Alice places two orders. What is Customer → Order?",["One-to-one","One-to-many","Many-to-one"],1,"One customer can be referenced by multiple orders."),q("What makes Profile.customer_id at most one profile per customer?",["Foreign key only","UNIQUE plus a foreign key","A text name"],1,"Uniqueness caps the number of referencing profiles; existence is a separate rule.")],resource:relational},
  {id:"er-modeling",title:"ER Modeling",visual:"er",
    idea:"An entity-relationship model makes entities, attributes, keys and relationship rules visible. It is a communication tool before it becomes a physical database design.",question:"Can another engineer read the diagram and explain the business rules?",why:"A small diagram exposes missing relationships and impossible cases before a pipeline loads data.",remember:"A diagram documents a rule; the database or pipeline must still enforce it.",takeaway:"Label keys, cardinality and optionality, then validate the diagram against example rows.",
    frames:[frame("Start with entity identity","Customer and Order each have their own key.",t.customers,t.orders),frame("Resolve order contents","An order can contain multiple lines. The pair (order_id, line_no) identifies a line.",t.lines),frame("Check a real case","Order 501 has Notebook and Pen; both lines reference valid products.",t.products,t.lines)],
    decision:q("Order 501 contains two different products. Which model records quantity and purchase price correctly?",["product_id on customers","OrderLine with order_id, line_no, product_id, quantity, unit_price","A list of product names in orders"],1,"OrderLine represents each purchased item and stores event-specific quantity and price."),hint:"Quantity describes the purchase of a product on a particular order, not the customer or product alone.",solution:"Customer 1 → many Order; Order 1 → many OrderLine; Product 1 → many OrderLine. OrderLine key is (order_id, line_no). Keep purchase unit_price on the line so catalog price changes do not rewrite sales.",
    interview:["How do you validate an ER model?","Trace ordinary, optional and duplicate cases. Check row identity, reference direction and whether relationship attributes live at the right grain. Confirm the rules with business owners.","Where would multiple payments per order fit?"],
    mistakes:[["Unlabeled relationship lines","Readers cannot tell which side may repeat.","Add the relationship verb and cardinality.","Customer — Order","Customer 1 — places — 0..many Order"],["Putting quantity on Product","Quantity purchased varies for every order line.","Put event attributes on the association.","Product(product_id, purchased_quantity)","OrderLine(order_id, line_no, product_id, quantity)"]],
    quiz:[q("Which entity owns quantity purchased on order 501?",["Customer","Product category","OrderLine"],2,"It is a property of a specific purchase line."),q("Does drawing a foreign-key arrow enforce data validity?",["Yes","No; implement and test the rule","Only in a star diagram"],1,"Documentation and enforcement are different responsibilities.")],resource:relational},
  {id:"normalization",title:"Normalization",visual:"normalization",
    idea:"Normalization organizes relations using dependencies to reduce redundant facts and update anomalies. Separate facts that depend on different keys while keeping meaningful relationships.",question:"If Alice changes city, how many places must we update?",why:"Repeated customer or product descriptions can drift apart. Separate ownership gives each current attribute a clear home.",remember:"1NF: no repeating groups. 2NF: non-key attributes depend on the whole candidate key. 3NF: remove inappropriate transitive dependencies. A surrogate ID alone does not fix dependencies.",takeaway:"Normalize by dependencies, not by splitting every column into a table.",
    frames:[frame("Before: repeating groups","A list of products hides the individual purchased items and their quantities.",table("Unnormalized order",["order_id","customer","products","quantities"],[[501,"Alice","Notebook, Pen","2, 3"]])),frame("1NF: one item per line","Split the repeated items into rows. Customer and product details still repeat; 1NF does not eliminate all redundancy.",t.flat),frame("2NF: separate whole-key dependencies","For a line key (order_id, line_no), order_date depends only on order_id. Move order-level facts to orders.",t.orders,t.lines),frame("3NF: separate descriptive dependencies","customer_id determines customer details; product_id determines product details. Keep those details in their own relations.",t.customers,t.products),frame("After: reconnect by keys","OrderLine stores the purchase price; that historical price belongs to the sale, not today’s product catalog.",t.orders,t.lines)],
    decision:q("OrderLine(order_id, line_no, order_date, product_id, quantity) has key (order_id, line_no). What should move out?",["quantity into Customer","order_date into Order","line_no into Product"],1,"order_date depends on order_id alone, a partial dependency on the composite line key."),hint:"Which value is identical for every line of the same order?",solution:"Order(order_id, order_date, customer_id); OrderLine(order_id, line_no, product_id, quantity, unit_price); Customer(customer_id, name, city); Product(product_id, product, category). Purchase price stays on the line.",
    interview:["Explain an update anomaly with an example.","If Alice’s current city appears on several order rows, updating only one leaves conflicting values. Store her current city once in Customer and reference her ID. Preserve a separate order shipping snapshot when history is required.","Why is keeping historical purchase price on the order line not the same anomaly?"],
    mistakes:[["Calling any table split normalization","Arbitrary splits add joins without fixing dependencies.","Identify candidate keys and what determines each attribute.","One table per column","Customer attributes depend on customer_id; line quantity on the whole line key"],["Replacing historical prices with current prices","Old revenue changes when the catalog price changes.","Store the price agreed for each purchase line.","revenue = quantity × current_product_price","revenue = quantity × order_line.unit_price"]],
    quiz:[q("Why move customer_city from Order to Customer in a current-state operational model?",["City depends on customer identity, not order identity","Every string needs a separate table","Foreign keys forbid text"],0,"Customer identity determines the current city; it need not be copied to every order."),q("A cell contains 'Notebook, Pen'. What is a useful 1NF repair?",["Rename the column","Make one related order-line row per item","Add a surrogate ID only"],1,"Separate repeated items into individually addressable rows.")],resource:relational},
  {id:"denormalization",title:"Denormalization",visual:"denormalization",
    idea:"Denormalization intentionally combines or repeats selected data to serve a read workload. It trades simpler reads against storage, refresh logic and consistency responsibilities.",question:"Which repeated joins can we precompute without losing the meaning of a row?",why:"A curated order-line extract can make frequent reporting easier, while normalized operational tables remain the authoritative source.",remember:"Do not copy order totals onto every line and then sum them. Keep the analytical grain explicit.",takeaway:"Denormalize for a measured workload, with an owner and a refresh contract.",
    frames:[frame("Sources own their facts","Customer, Order and Product attributes start in separate tables.",t.customers,t.orders),frame("Join at line grain","Each line joins to one order, one customer and one product.",t.lines,t.products),frame("Publish a read model","Descriptions repeat intentionally. Refresh from authoritative sources and document whether city is current or historical.",t.flat)],
    decision:q("A daily report repeatedly joins four tables and tolerates a one-day delay. Which is a reasonable design to evaluate?",["A daily refreshed order-line read model with validation","Copy data with no refresh owner","Repeat order totals on every line and SUM them"],0,"A governed read model may reduce repeated joins. Benchmark it and define freshness and grain explicitly."),hint:"Consider read frequency, acceptable freshness and who maintains repeated attributes.",solution:"Keep normalized write tables. Publish a daily refreshed line-grain extract keyed by (order_id, line_no), validate uniqueness, and document its current-city versus historical-city policy. Measure query cost before and after.",
    interview:["When would you denormalize?","When a known read workload benefits from fewer joins or precomputed summaries and the refresh cost is justified. I preserve a declared grain, source ownership, freshness targets and reconciliation checks.","What happens when a customer attribute changes between refreshes?"],
    mistakes:[["Denormalizing everything","Extra copies increase update and reconciliation costs.","Target specific expensive or awkward read paths.","Copy every source into every report","Build a named read model for a known workload"],["Duplicating order totals across lines","Order 501 totals 130; repeating 130 on two lines sums to 260.","Store line revenue or aggregate each order once.","501 line 1: 130; line 2: 130 → 260","501 line 1: 100; line 2: 30 → 130"]],
    quiz:[q("What new responsibility comes with repeated customer city in a report table?",["No responsibility","Refresh and history semantics","Automatic constraint enforcement"],1,"Copies need a defined update policy and historical meaning."),q("Does denormalization always improve performance?",["Yes","No, measure the workload and maintenance cost","Only if all columns are text"],1,"Performance depends on the engine, data and queries.")],resource:schema},
  {id:"oltp-olap",title:"OLTP vs OLAP",visual:"workloads",
    idea:"OLTP supports operational transactions such as placing an order. OLAP supports analytical questions across many events, such as monthly category revenue.",question:"Are we recording one purchase or learning from many purchases?",why:"Write correctness, read latency, historical scope and query patterns affect schema and storage choices.",remember:"These are workload categories, not a rule that every OLTP model is normalized or every OLAP model is a star.",takeaway:"Choose a model for the workload and its correctness, freshness and performance needs.",
    frames:[frame("Record an event","Operational work inserts order 501 and its lines with transaction checks.",t.orders,t.lines),frame("Prepare analytical rows","A warehouse load resolves dimension keys and records line revenue.",t.fact),frame("Ask across events","Summarize all four lines: 100 + 30 + 50 + 20 = 200.",table("January report",["month","category","revenue"],[["2026-01","Stationery",200]]))],
    decision:q("Checkout latency rises when a dashboard scans years of sales. What would you evaluate?",["Run more full scans during checkout","A separate analytical read path with a freshness contract","Remove transaction checks"],1,"Separating workload paths can protect operational latency, but introduces replication and freshness responsibilities."),hint:"The two consumers have different latency, scan and update patterns.",solution:"Keep checkout on the transactional store. Load a warehouse or read replica for reporting, define acceptable lag, reconcile totals and monitor both paths. Select the simplest architecture that meets the workload.",
    interview:["How do OLTP and OLAP influence modeling?","OLTP emphasizes reliable small transactions and current operational state. OLAP emphasizes understandable aggregation over many historical events. Schema, indexing, storage and refresh design should reflect those access patterns.","What trade-off appears when the reporting store lags the operational store?"],
    mistakes:[["Using a workload label as a schema law","Real systems can combine normalized and dimensional structures.","Ask about actual queries and updates.","OLTP always means this exact schema","Model checkout and reporting according to their needs"],["Ignoring freshness","A daily report cannot promise real-time inventory.","State the refresh frequency and lag.","Dashboard says live; load runs nightly","Dashboard states data through last successful load"]],
    quiz:[q("Which request is primarily analytical?",["Insert one payment","Update one shipping address","Revenue by category for the last year"],2,"It summarizes many events over time."),q("Moving reports to a warehouse introduces which concern?",["Data freshness and reconciliation","No need for business keys","No need for grain"],0,"Copies must be kept sufficiently current and reconciled.")],resource:dimensional},
  {id:"facts-dimensions",title:"Fact & Dimension Tables",visual:"facts",
    idea:"A Fact table records business events or observations at a declared Grain. A Dimension supplies descriptive context used to filter and group those observations.",question:"What happened, and who, what, when and where describe it?",why:"Clear roles make revenue measures understandable and prevent joins from silently multiplying events.",remember:"Not every numeric column is a measure: product_key is an identifier. Some measures, such as balances, cannot be summed over every dimension.",takeaway:"Declare the event grain before choosing dimension references and compatible measures.",
    frames:[frame("Describe the context","Product names/categories belong in a dimension, not as the identity of each sale.",t.dimProduct),frame("Record the events","Four order-line facts reference dimensions. Revenue is additive in this single-currency sales example.",t.fact),frame("Summarize with context","Notebook revenue = 150; Pen revenue = 50. Total remains 200.",table("Revenue by product",["product","revenue"],[["Notebook",150],["Pen",50]]))],
    decision:q("At one row per order line, which is a measure rather than a dimension key?",["product_key","customer_key","quantity"],2,"Quantity measures the event; keys connect that event to descriptive context."),hint:"Ask whether summing the column describes the business or just adds identifiers.",solution:"Fact grain: one order line. References: customer_key, product_key, date_key, store_key. Measures: quantity and line revenue. Retain order_id and line_no to identify source events and prevent duplicate loads.",
    interview:["How do you distinguish facts from dimensions?","Start with the business event and grain. Facts record observations and compatible measures; dimensions describe them. A numeric customer ID is not a revenue measure, and a fact table can even be factless when recording participation.","Why should an inventory balance not be summed across daily snapshots?"],
    mistakes:[["Treating every number as a measure","Adding customer IDs has no business meaning.","Separate keys from measured quantities.","SUM(customer_key)","SUM(revenue) grouped by customer attributes"],["Mixing balances and sales without semantics","A balance represents a point in time, not new sales each day.","Define additivity and aggregation for each measure.","SUM(daily_balance) over a month","Use end-of-period balance or an explicitly defined average"]],
    quiz:[q("Which table should hold product category?",["A product dimension","Only the order-line primary key","A sum of customer IDs"],0,"It describes products and provides a grouping attribute."),q("Two rows have the same order_id but different line_no. Are they duplicate line-grain facts?",["Always","Not necessarily; they are different lines","Only if the prices match"],1,"The full declared grain determines event uniqueness.")],resource:dimensional},
  {id:"star-schema",title:"Star Schema",visual:"star",
    idea:"A Star Schema places a Fact table at the center with direct references to descriptive Dimension tables. Each dimension row key is unique on the one side of the relationship.",question:"Can every sale join to one version of each descriptive context?",why:"A consistent fact grain and direct dimension joins make common analytical questions easier to express and audit.",remember:"The star shape does not prevent duplicate facts. Test source-event uniqueness and dimension-key uniqueness.",takeaway:"Keep one fact grain, direct dimension references, and measures that match that grain.",
    frames:[frame("Declare the fact","One row per order line; do not add a separate order-total row to this fact.",t.fact),frame("Attach descriptive dimensions","Each product key finds exactly one dimension row.",t.dimProduct,t.dimCustomer),frame("Validate the total","Joining unique dimensions preserves four fact rows and total revenue 200.",table("Reconciliation",["check","value"],[["Fact rows",4],["Rows after valid dimension joins",4],["Revenue",200]]))],
    decision:q("An order has two lines and one delivery fee of 15. How should the fee be represented?",["Put 15 on both lines and sum it","Keep an order-grain fact or use a documented allocation totaling 15","Store it as product_key"],1,"An order-level measure does not naturally belong at line grain. A separate grain or explicit allocation avoids doubling."),hint:"After modeling the fee, its total for this order must still be 15.",solution:"Use an order-grain delivery fee fact keyed by order_id, or allocate the 15 across lines using a stated business rule. Never repeat the full fee and then sum it at line grain.",
    interview:["How would you design a retail sales star?","Declare one row per sale line, identify date, product, customer and store dimensions, then add compatible quantity and revenue measures. Preserve source-line identity and reconcile counts and totals after loading and joining.","How would returns and multiple currencies affect the design?"],
    mistakes:[["Joining on non-unique dimension names","Two products with the same name multiply matches.","Join facts to unique dimension version keys.","fact.product_name = dim_product.name","fact.product_key = dim_product.product_key"],["Mixing grains","Order totals and line amounts overlap.","Separate fact grains or define an allocation.","Order total 130 plus line amounts 100 and 30","Line fact total 130; order summary stored separately"]],
    quiz:[q("A star fact normally connects directly to what?",["Descriptive dimensions","Every other fact table","Only text files"],0,"Direct fact-to-dimension relationships create the star."),q("A dimension join changes four sale rows to six. What should you check first?",["Dimension join-key uniqueness","Font size","Whether the fact is named sales"],0,"Multiple dimension matches can inflate row counts and measures.")],code:"SELECT p.category, SUM(f.revenue) AS revenue\nFROM fact_sales f\nJOIN dim_product p ON p.product_key = f.product_key\nGROUP BY p.category;",resource:schema},
  {id:"snowflake-schema",title:"Snowflake Schema",visual:"snowflake",
    idea:"A Snowflake Schema normalizes some dimension attributes into related tables. Product can reference Category instead of repeating its category description in every product row.",question:"Should category details live with each product or in one shared category table?",why:"Separating a governed hierarchy can reduce repeated descriptive data but adds joins and navigation for consumers.",remember:"Star versus snowflake is a workload and governance trade-off, not a universal performance ranking.",takeaway:"Normalize a dimension hierarchy when the benefits justify additional joins and maintenance.",
    frames:[frame("Star dimension","Category repeats inside each product row.",t.dimProduct),frame("Snowflake the hierarchy","Both products reference category 7; its description is stored once.",table("dim_product",["product_key","product","category_key"],[[10,"Notebook",7],[20,"Pen",7]]),table("dim_category",["category_key","category"],[[7,"Stationery"]])),frame("Trace the analytical path","Fact → Product → Category still returns revenue 200 when each reference has one match.",table("Category result",["category","revenue"],[["Stationery",200]]))],
    decision:q("Category has governed attributes shared by thousands of products. Which design is reasonable to evaluate?",["A category dimension referenced by product","A category table with no key","Copy category into every fact without a refresh plan"],0,"A shared hierarchy can justify snowflaking. Compare consumer complexity and measured query cost with a flattened dimension."),hint:"Separate the ownership of category descriptions from the event grain.",solution:"fact_sales.product_key → dim_product.product_key; dim_product.category_key → dim_category.category_key. Keep referenced keys unique, preserve row counts, and benchmark against a flat product dimension.",
    interview:["Star versus snowflake: how do you choose?","A flat dimension simplifies consumer joins; a normalized hierarchy centralizes shared attributes. Evaluate governance, change patterns, engine behavior and consumer usability rather than declaring either always faster.","What if a product can belong to multiple categories at the same time?"],
    mistakes:[["Snowflaking every small attribute","Unnecessary tables can make a simple model hard to use.","Separate hierarchies for a clear ownership or workload reason.","One lookup table per descriptive field","A governed category hierarchy where it adds value"],["Assuming categories are always single-valued","Multiple category matches may duplicate fact measures.","Validate membership rules; model a bridge and allocation if needed.","Join to every category, then sum revenue","Define exclusive membership or weighted attribution"]],
    quiz:[q("Which path illustrates a snowflaked product dimension?",["Fact → Product → Category","Fact → Product with category text only","Customer → Customer"],0,"A dimension references another normalized descriptive table."),q("Does snowflaking remove the need to declare fact grain?",["Yes","No","Only for revenue"],1,"Dimension shape does not define or repair event grain.")],resource:schema},
  {id:"scd",title:"Slowly Changing Dimensions",visual:"scd",
    idea:"Slowly Changing Dimensions define how descriptive changes are stored. Type 1 overwrites a value; SCD Type 2 keeps versions so past events can retain their historical context.",question:"Should January sales use Alice’s January city or her current city?",why:"Historical segmentation needs the right version, not just the latest customer record.",remember:"For Type 2 use non-overlapping validity intervals and resolve each fact to the appropriate dimension version. Late-arriving changes require a deliberate repair policy.",takeaway:"Choose overwrite or version history by reporting need, and test the effective-date boundary.",
    frames:[frame("Before the move","Alice lives in Chennai. Her January sale references key 101.",table("Customer before change",["customer_key","customer_id","name","city"],[[101,1,"Alice","Chennai"]])),frame("Type 1: overwrite","Changing city to Bangalore on key 101 loses the old city in this dimension.",table("Type 1 after change",["customer_key","customer_id","name","city"],[[101,1,"Alice","Bangalore"]])),frame("Type 2: add a version","On February 1 close key 101 and insert key 205. end_date is exclusive; NULL means current in this example.",t.history),frame("Resolve the event’s version","A January event uses 101; an event exactly on February 1 uses 205.",table("Facts retain historical context",["event_date","customer_key","city_at_event"],[["2026-01-10",101,"Chennai"],["2026-02-01",205,"Bangalore"]]))],
    decision:q("Alice moves February 1. Reports must preserve the city at the time of each sale. Which update fits?",["Overwrite key 101","Add key 205 and close key 101 at February 1","Join every sale to both versions using customer_id alone"],1,"Type 2 preserves old rows. Resolve facts to one version based on the event time and interval boundaries."),hint:"The same business customer needs two warehouse versions, not two different people.",solution:"Expire key 101 at 2026-02-01; insert key 205 starting 2026-02-01. Use [start_date, end_date) intervals. Existing January facts keep 101; later facts use 205. Enforce one current version and no overlapping intervals.",
    interview:["How would you preserve customer address history?","Use Type 2 for tracked address changes, with a new surrogate key and validity interval per version. Resolve facts using event time. Keep business identity separately and handle late updates and duplicate change events intentionally.","How would you repair a change that arrives a month after its effective date?"],
    mistakes:[["Joining only on the business key","A customer with two versions can match twice.","Store the resolved dimension version key or use an as-of condition.","fact.customer_id = dim.customer_id","fact.customer_key = dim.customer_key"],["Overlapping effective intervals","A boundary event may match more than one version.","Use a consistent exclusive end and test boundary dates.","Old end inclusive Feb 1; new start Feb 1","Old [Jan 1, Feb 1); new [Feb 1, NULL)"]],
    quiz:[q("What happens to Alice’s Chennai row with Type 2?",["It is preserved and expired","It is always deleted","Its natural key must become a new person"],0,"A new row represents the changed version; business identity stays the same."),q("With [start,end), which key matches an event on February 1?",["101","205","Both"],1,"The old interval excludes February 1; the new one includes it.")],resource:{title:"Kimball · Type 2: add a new row",url:"https://www.kimballgroup.com/data-warehouse-business-intelligence-resources/kimball-techniques/dimensional-modeling-techniques/type-2/"}},
  {id:"analytics",title:"Modeling for Analytics",visual:"analytics",
    idea:"Translate business questions into a consistent event grain, dimensions and measures. Design from the questions people need to answer, not from a memorized diagram.",question:"What event detail must we retain to answer all four reporting questions?",why:"Monthly revenue, category revenue, top customers and sales by store region can share line-grain facts when the required dimension keys are retained.",remember:"Revenue, tax, shipping, discounts, refunds and currency need explicit definitions. Our sample uses one currency and revenue before any such adjustments.",takeaway:"Business questions → grain → dimensions and measures → schema → reconciliation.",
    frames:[frame("Declare the event grain","One row per order line keeps product-level detail that an order total would lose.",t.lines),frame("Choose descriptive context","Date supports month, product supports category, customer supports ranking and store supports region.",t.dimDate,t.dimStore),frame("Validate useful outputs","Four lines give revenue 200. Alice contributes 180; Bob contributes 20.",table("Customer revenue",["customer","revenue"],[["Alice",180],["Bob",20]]),table("Month / category revenue",["month","category","revenue"],[["2026-01","Stationery",200]]))],
    decision:q("The business needs revenue by product category and customer. Which grain retains the needed detail?",["One row per month with only a total","One row per order line with product and customer context","One row per customer name only"],1,"Line grain retains which products were bought. Coarser totals can be derived later but lost detail cannot be recovered."),hint:"A single order can contain products from different categories.",solution:"Use order-line grain, customer/product/date/store dimension keys, quantity and clearly defined revenue. Retain (order_id, line_no) for deduplication. Check uniqueness, valid references and source-to-target totals before publishing.",
    interview:["How would you model an e-commerce analytics system?","Clarify required decisions and metric definitions, declare order-line grain, then identify descriptive dimensions and compatible measures. Address returns, currency and history separately; reconcile source events and analytical totals.","What additional fact would you need to analyze payments or daily inventory?"],
    mistakes:[["Choosing grain after adding measures","Order totals and product-level revenue can conflict.","Write the grain sentence before selecting measures.","One table of all totals and transactions","One row per order line; other processes get their own grain"],["Counting lines as orders","Order 501 has two lines, so COUNT(*) counts items not orders.","Use the intended event identity for each metric.","4 lines = 4 orders","COUNT(DISTINCT order_id) = 3 orders"]],
    quiz:[q("The sample has four lines across orders 501, 502 and 503. How many orders?",["4","3","2"],1,"Order count and order-line count are different metrics."),q("Which question cannot be answered from sale events alone?",["Revenue by product","Units sold","Exact on-hand inventory for every day"],2,"Inventory needs movements or snapshots and appropriate opening balances.")],resource:dimensional},
  {id:"interview-review",title:"Data Modeling Interview Review",visual:"analytics",
    idea:"A strong modeling answer explains the business process, grain, relationships, measures, history and validation. Use a small example to defend each decision.",question:"Can I explain my design and demonstrate that it does not double-count?",why:"Interview scenarios usually change a rule. Understanding the model lets you adapt rather than recite terminology.",remember:"State assumptions, ask about ambiguous rules, and explain a trade-off. There may be several valid models.",takeaway:"Defend your grain, keys, cardinality, history policy and reconciliation checks with sample rows.",
    frames:[frame("Read the evidence","Alice has two orders; order 501 has two lines. Identify which keys can repeat.",t.orders,t.lines),frame("Defend the analytical design","Explain why keys describe context and revenue measures each line event.",t.fact),frame("Test the answer","Expected checks: three orders, four lines, revenue 200; a dimension join must not inflate those totals.",table("Review checklist",["test","expected"],[["Distinct orders",3],["Unique order-line pairs",4],["Revenue",200],["Orphan dimension references",0]]))],
    decision:q("A report doubles revenue after adding product category. What is your first diagnostic?",["Divide every result by two","Inspect join cardinality and category membership","Drop all primary keys"],1,"Find where one input fact produces multiple matches before changing aggregation. Membership rules may require unique keys or a governed bridge."),hint:"Trace one fact row through each join and count how many rows it becomes.",solution:"Check dimension-key uniqueness and product-category membership. Compare row counts and revenue before/after each join. Fix duplicate dimension rows or define category attribution; do not hide the error with an arbitrary divisor.",
    interview:["The interviewer adds split payments and returns. How does your model change?","Keep payment events and return lines at their own declared grains, connected to order or order-line identity. Define how net revenue and payment reconciliation are computed; do not join raw many-row facts and sum blindly.","When should independently aggregated facts be combined instead of raw fact rows?"],
    mistakes:[["Giving a diagram without assumptions","It hides unresolved rules and history requirements.","State the business rules and validate them with examples.","Here is a star","Here is a line-grain star; one currency; historical customer version; returns modeled separately"],["Hiding duplicate joins with DISTINCT","Distinct can erase legitimate equal-valued events or fail to fix measures.","Fix the key/cardinality issue and reconcile totals.","SUM(DISTINCT revenue)","Unique fact identity + unique dimension keys + normal SUM(revenue)"]],
    quiz:[q("Two legitimate sale lines each have revenue 50. Is SUM(DISTINCT revenue) a safe fix for join duplication?",["Yes","No, it would count 50 only once","Only on Mondays"],1,"Distinct measure values are not distinct business events."),q("Which explanation best defends a design?",["Star is always fastest","Every row means one order line; keys and measures follow that rule","All IDs are interchangeable"],1,"A declared grain links schema choices to business meaning.")],resource:dimensional},
];

export const modelingLessons:ModelingLesson[]=specs.map(s=>({
  id:s.id,title:s.title,minutes:["introduction","entities"].includes(s.id)?15:25,description:s.question,
  concepts:[[s.title,s.idea],["Why it matters",s.why],["Remember",s.remember]],flow:s.frames.map(f=>f.title),
  visual:s.visual,question:s.question,why:s.why,remember:s.remember,takeaway:s.takeaway,frames:s.frames,decision:s.decision,resource:s.resource??dimensional,
  example:{code:s.code??"",output:s.frames.at(-1)!.description,walkthrough:s.frames.map(f=>f.description)},
  practice:{task:s.decision.question,hint:s.hint,solution:s.solution,output:s.decision.explanation},
  interview:[{question:s.interview[0],answer:s.interview[1],followup:s.interview[2]},{question:s.decision.question,answer:s.solution,followup:"What assumption would make you change this design?"}],
  mistakes:s.mistakes.map(([title,why,better,before,after])=>({title,why,better,before,after})),quiz:s.quiz,
}));
export const modelingById=Object.fromEntries(modelingLessons.map(lesson=>[lesson.id,lesson]));
