export interface GlossaryItem {
  id: string;
  term: string;
  category: "Spark" | "SQL" | "Airflow" | "Kafka";
  difficulty: "Easy" | "Medium" | "Hard";
  interviewFrequency: number;
  definition: string;
  explanation: string;
  related: string[];
  style: "spark" | "sql" | "tool" | "concept";
  expanded?: string;
  aliases?: string[];
  questions: string[];
  mistakes: string[];
  flow: string[];
}

// Frequency values are editorial demo estimates, not measured interview statistics.
export const glossary: GlossaryItem[] = [
  { id: "rdd", term: "RDD", expanded: "Resilient Distributed Dataset", aliases: ["RDDs"], category: "Spark", style: "spark", difficulty: "Medium", interviewFrequency: 78, definition: "Spark’s immutable distributed collection for low-level transformations and fine-grained control.", explanation: "Explain partition-level computation, lazy evaluation, and lineage-based recovery. Contrast explicit RDD functions with the optimizer-visible expressions of DataFrames.", related: ["DataFrame", "Partitioning", "Shuffle"], questions: ["When would you choose an RDD over a DataFrame?", "How does lineage help recover a lost partition?"], mistakes: ["Calling collect() on a dataset too large for the driver.", "Assuming a transformation runs immediately."], flow: ["Partitioned source", "Lazy transformations", "Action → tasks"] },
  { id: "dataframe", term: "DataFrame", aliases: ["DataFrames"], category: "Spark", style: "spark", difficulty: "Medium", interviewFrequency: 86, definition: "A distributed table with named columns and a schema that Spark can optimize.", explanation: "Interviewers use DataFrames to explore schemas, query plans, and built-in expressions. Explain how structured expressions give Catalyst information it cannot infer from arbitrary Python functions.", related: ["RDD", "Catalyst Optimizer", "Partitioning"], questions: ["Why can a DataFrame outperform an RDD?", "How do you inspect a DataFrame’s execution plan?"], mistakes: ["Using a Python UDF when a built-in expression exists.", "Treating schema inference as data validation."], flow: ["Data + schema", "Logical plan", "Optimized execution"] },
  { id: "catalyst", term: "Catalyst Optimizer", aliases: ["Catalyst"], category: "Spark", style: "spark", difficulty: "Hard", interviewFrequency: 76, definition: "Spark SQL’s framework for analyzing, optimizing, and planning structured queries.", explanation: "Discuss predicate pushdown, column pruning, and logical versus physical plans. Be clear that the execution engine runs the physical plan after planning.", related: ["DataFrame", "Shuffle", "DAG"], questions: ["What is predicate pushdown?", "How do logical and physical plans differ?"], mistakes: ["Expecting Catalyst to optimize arbitrary RDD functions.", "Assuming every filter can be pushed into a source."], flow: ["Parsed query", "Analyzed + optimized plan", "Physical plan"] },
  { id: "shuffle", term: "Shuffle", category: "Spark", style: "concept", difficulty: "Hard", interviewFrequency: 82, definition: "Redistribution of records across partitions, often involving network and disk I/O.", explanation: "Joins and aggregations often require records with matching keys to meet. Explain the cost of moving data and how skew causes uneven task duration.", related: ["Partitioning", "DataFrame", "RDD"], questions: ["Which operations cause a shuffle?", "How would you diagnose a skewed join?"], mistakes: ["Repartitioning repeatedly without checking the plan.", "Ignoring hot keys and uneven partition sizes."], flow: ["Source partitions", "Exchange by key", "Destination partitions"] },
  { id: "partitioning", term: "Partitioning", category: "Spark", style: "concept", difficulty: "Medium", interviewFrequency: 81, definition: "Dividing data into units that can be stored or processed independently.", explanation: "Distinguish execution partitions from directory partitions on storage. Reason about parallelism, skew, pruning, and small files when choosing a strategy.", related: ["Shuffle", "RDD", "DataFrame"], questions: ["How do repartition and coalesce differ?", "What happens when partitions are too small?"], mistakes: ["Confusing storage partitioning with task parallelism.", "Partitioning storage by a very high-cardinality column."], flow: ["Input records", "Partition strategy", "Parallel tasks"] },
  { id: "dag", term: "DAG", expanded: "Directed Acyclic Graph", category: "Airflow", style: "concept", difficulty: "Medium", interviewFrequency: 74, definition: "A graph of directed dependencies with no cycles.", explanation: "Use a DAG to reason about task ordering, parallel work, and retries. Airflow DAGs orchestrate tasks; Spark execution DAGs describe distributed computation.", related: ["Airflow", "RDD"], questions: ["Why must a workflow graph be acyclic?", "How do retries affect downstream tasks?"], mistakes: ["Creating circular dependencies.", "Putting heavy computation into DAG parsing."], flow: ["Extract", "Transform", "Load"] },
  { id: "kafka-topic", term: "Kafka Topic", category: "Kafka", style: "concept", difficulty: "Medium", interviewFrequency: 72, definition: "A named stream of records organized into partitions in Kafka.", explanation: "Explain ordering within a partition, offsets, retention, and consumer groups. A topic is not a global ordered queue when it has multiple partitions.", related: ["Kafka", "Partitioning", "CDC"], questions: ["Where does Kafka guarantee ordering?", "How do consumer groups share partitions?"], mistakes: ["Assuming global ordering across partitions.", "Equating consumer offsets with deletion of records."], flow: ["Producer", "Topic partitions", "Consumer group"] },
  { id: "window-function", term: "Window Function", aliases: ["Window Functions"], category: "SQL", style: "concept", difficulty: "Medium", interviewFrequency: 88, definition: "A SQL calculation over related rows that preserves individual output rows.", explanation: "Practice rankings, running totals, and deduplication. Explain PARTITION BY, ORDER BY, and window frames, including ties and deterministic ordering.", related: ["SELECT", "Partitioning"], questions: ["How do ROW_NUMBER and RANK differ?", "How would you calculate a running total?"], mistakes: ["Omitting a tie-breaker for deduplication.", "Ignoring the default window frame."], flow: ["Rows", "Partition + order + frame", "Per-row result"] },
  { id: "star-schema", term: "Star Schema", category: "SQL", style: "concept", difficulty: "Medium", interviewFrequency: 69, definition: "An analytical model with a central fact table linked to dimension tables.", explanation: "Start with the fact grain, then define measures and dimensions. Discuss why a clear grain avoids double-counting and supports consistent analysis.", related: ["SCD Type 2", "Normalization"], questions: ["How do you choose fact-table grain?", "How does a star differ from a snowflake schema?"], mistakes: ["Mixing multiple grains in one fact table.", "Joining facts through non-unique dimension keys."], flow: ["Dimensions", "Fact table at fixed grain", "Analytical query"] },
  { id: "scd-type-2", term: "SCD Type 2", category: "SQL", style: "concept", difficulty: "Hard", interviewFrequency: 73, definition: "A dimension-history technique that inserts a new row for each tracked change.", explanation: "Explain surrogate keys, effective intervals, current flags, and as-of joins. Address late-arriving changes and non-overlapping validity intervals.", related: ["Star Schema", "CDC"], questions: ["How do you preserve a customer’s address history?", "How would you join facts to the correct historical version?"], mistakes: ["Overwriting historical rows.", "Leaving overlapping effective-date ranges."], flow: ["Changed record", "Expire prior version", "Insert new version"] },
  { id: "select", term: "SELECT", category: "SQL", style: "sql", difficulty: "Easy", interviewFrequency: 95, definition: "Specifies the expressions and columns returned by a SQL query.", explanation: "Explain projection and expression evaluation. Distinguish SQL’s logical processing order from the order clauses are written.", related: ["FROM", "WHERE", "Window Function"], questions: ["Why avoid SELECT * in production pipelines?"], mistakes: ["Depending on an unstable column order."], flow: ["Input relation", "Projection", "Result columns"] },
  { id: "from", term: "FROM", category: "SQL", style: "sql", difficulty: "Easy", interviewFrequency: 90, definition: "Identifies the source relations for a SQL query.", explanation: "Discuss tables, subqueries, and join cardinality. A join can multiply rows when keys are not unique.", related: ["SELECT", "WHERE"], questions: ["How can a join unexpectedly multiply row counts?"], mistakes: ["Joining without understanding key uniqueness."], flow: ["Tables or subqueries", "Joins", "Input relation"] },
  { id: "where", term: "WHERE", category: "SQL", style: "sql", difficulty: "Easy", interviewFrequency: 92, definition: "Filters input rows using a predicate before grouping.", explanation: "Contrast WHERE with HAVING and explain SQL’s three-valued logic when NULL is present.", related: ["SELECT", "FROM"], questions: ["How does WHERE differ from HAVING?"], mistakes: ["Using = NULL instead of IS NULL."], flow: ["Input rows", "Predicate", "Matching rows"] },
  { id: "airflow", term: "Airflow", category: "Airflow", style: "tool", difficulty: "Medium", interviewFrequency: 67, definition: "A platform for authoring, scheduling, and monitoring batch workflows.", explanation: "Discuss orchestration, task dependencies, retries, backfills, and idempotent tasks.", related: ["DAG", "dbt"], questions: ["How do you make a retried task safe?"], mistakes: ["Treating Airflow as a streaming processing engine."], flow: ["DAG definition", "Scheduler", "Task execution"] },
  { id: "kafka", term: "Kafka", category: "Kafka", style: "tool", difficulty: "Medium", interviewFrequency: 71, definition: "A distributed event-streaming platform built around partitioned logs.", explanation: "Explain producers, brokers, consumers, retention, and the scope of delivery guarantees.", related: ["Kafka Topic", "CDC"], questions: ["What does at-least-once delivery mean for a consumer?"], mistakes: ["Assuming retries cannot produce duplicates."], flow: ["Producer", "Broker log", "Consumer"] },
  { id: "dbt", term: "dbt", category: "SQL", style: "tool", difficulty: "Medium", interviewFrequency: 62, definition: "A framework for building, testing, and documenting data transformations.", explanation: "Discuss model dependencies, materializations, tests, and incremental processing in a warehouse.", related: ["DAG", "Star Schema"], questions: ["When would you choose an incremental model?"], mistakes: ["Ignoring late-arriving records in an incremental filter."], flow: ["Source tables", "SQL models + tests", "Analytics tables"] },
  { id: "normalization", term: "Normalization", category: "SQL", style: "concept", difficulty: "Medium", interviewFrequency: 58, definition: "Organizing relational data to reduce redundancy and update anomalies.", explanation: "Explain functional dependencies and the tradeoff between normalized transactional models and analytical dimensions.", related: ["Star Schema"], questions: ["What is an update anomaly?"], mistakes: ["Assuming more normalization always improves analytical query performance."], flow: ["Redundant relation", "Functional dependencies", "Decomposed relations"] },
  { id: "cdc", term: "CDC", expanded: "Change Data Capture", category: "Kafka", style: "concept", difficulty: "Hard", interviewFrequency: 64, definition: "Capturing inserts, updates, and deletes from a source for downstream processing.", explanation: "Discuss snapshots, change logs, ordering, deletes, and idempotent application of changes.", related: ["Kafka Topic", "SCD Type 2"], questions: ["How do you handle duplicate change events?"], mistakes: ["Ignoring deletes or source transaction order."], flow: ["Source changes", "Change stream", "Downstream state"] },
];

export const glossaryLookup = new Map(glossary.flatMap(item => [item.id, item.term, ...(item.aliases ?? [])].map(key => [key.toLowerCase(), item] as const)));
export function getGlossaryItem(term: string) { return glossaryLookup.get(term.toLowerCase()); }

export type GlossaryToken = { text: string; item?: GlossaryItem };
const names = glossary.flatMap(item => [item.term, ...(item.aliases ?? [])]).sort((a, b) => b.length - a.length);
const escape = (text: string) => text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
const pattern = new RegExp(`(?<![\\p{L}\\p{N}_])(${names.map(escape).join("|")})(?![\\p{L}\\p{N}_])`, "giu");
export function tokenizeGlossary(text: string): GlossaryToken[] {
  const result: GlossaryToken[] = []; let cursor = 0;
  for (const match of text.matchAll(pattern)) {
    const index = match.index!;
    if (index > cursor) result.push({ text: text.slice(cursor, index) });
    const item = getGlossaryItem(match[0]);
    // Ordinary prose words such as “from” should not become SQL pills.
    result.push({ text: match[0], item: item?.style === "sql" && match[0] !== item.term ? undefined : item });
    cursor = index + match[0].length;
  }
  if (cursor < text.length) result.push({ text: text.slice(cursor) });
  return result;
}
