export interface GlossaryItem {
  contextOnly?: boolean;
  id: string;
  term: string;
  category: "Spark" | "SQL" | "Airflow" | "Kafka" | "Data Modeling";
  difficulty: "Easy" | "Medium" | "Hard";
  interviewFrequency: number;
  definition: string;
  explanation: string;
  related: string[];
  style: "spark" | "sql" | "tool" | "concept";
  expanded?: string;
  aliases?: string[];
  questions: string[];
  mistakes: string[];
  flow: string[];
}

// Frequency values are editorial demo estimates, not measured interview statistics.
export const glossary: GlossaryItem[] = [
  {"id":"kafka-producer","term":"Producer","contextOnly":true,"category":"Kafka","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"An application component that publishes records to Kafka topics.","explanation":"A producer serializes keys and values, chooses partitions and handles delivery outcomes. An acknowledgement is not proof that a consumer completed its work.","related":["Kafka","Kafka Topic"],"questions":["How does Producer affect order-event recovery?"],"mistakes":["Assuming a guarantee at this boundary automatically covers external business effects."],"flow":["Create event","Serialize","Send","Acknowledgement"]},
  {"id":"kafka-consumer","term":"Consumer","contextOnly":true,"category":"Kafka","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"An application component that fetches and processes Kafka records.","explanation":"In an ordinary consumer group it reads assigned partitions. Fetching, processing and committing progress are separate actions.","related":["Kafka","Kafka Topic"],"questions":["How does Consumer affect order-event recovery?"],"mistakes":["Assuming a guarantee at this boundary automatically covers external business effects."],"flow":["Fetch","Process","Commit next offset"]},
  {"id":"kafka-partition","term":"Partition","contextOnly":true,"category":"Kafka","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"One ordered log inside a Kafka topic.","explanation":"Its offsets form a local position space. Different partitions do not have a shared global order; replicas copy the same logical partition.","related":["Kafka","Kafka Topic"],"questions":["How does Partition affect order-event recovery?"],"mistakes":["Assuming a guarantee at this boundary automatically covers external business effects."],"flow":["Topic","Partition log","Local offsets"]},
  {"id":"kafka-offset","term":"Offset","contextOnly":true,"category":"Kafka","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"A record position in one Kafka partition.","explanation":"Track topic, partition and offset together. A committed consumer offset denotes the next position to process; offsets can have gaps after cleanup.","related":["Kafka","Kafka Topic"],"questions":["How does Offset affect order-event recovery?"],"mistakes":["Assuming a guarantee at this boundary automatically covers external business effects."],"flow":["P1:211 processed","Commit 212","Resume at 212"]},
  {"id":"kafka-broker","term":"Broker","contextOnly":true,"category":"Kafka","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"A Kafka server that hosts partition replicas and serves requests.","explanation":"A topic can span several brokers, and a broker can host replicas from many topics. A leader’s host is not the partition’s logical identity.","related":["Kafka","Kafka Topic"],"questions":["How does Broker affect order-event recovery?"],"mistakes":["Assuming a guarantee at this boundary automatically covers external business effects."],"flow":["Cluster","Broker","Hosted replicas"]},
  {"id":"kafka-consumer-group","term":"Consumer Group","contextOnly":true,"category":"Kafka","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"Consumers that divide partition ownership and maintain group progress.","explanation":"In a stable ordinary group assignment, one member owns a partition at a time. A separate group has independent ownership and offsets; share groups have different semantics.","related":["Kafka","Kafka Topic"],"questions":["How does Consumer Group affect order-event recovery?"],"mistakes":["Assuming a guarantee at this boundary automatically covers external business effects."],"flow":["Partitions","Group assignment","Members"]},
  {"id":"kafka-consumer-lag","term":"Consumer Lag","contextOnly":true,"category":"Kafka","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"A gap between log-end progress and consumer progress.","explanation":"State which position is measured: fetched, processed or committed. Offset gaps are not always exact business-record counts, so measure latency and errors too.","related":["Kafka","Kafka Topic"],"questions":["How does Consumer Lag affect order-event recovery?"],"mistakes":["Assuming a guarantee at this boundary automatically covers external business effects."],"flow":["Log end 106","Committed 104","Offset gap 2"]},
  {"id":"kafka-message-key","term":"Message Key","contextOnly":true,"category":"Kafka","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"Serialized record data commonly used to choose a partition.","explanation":"Stable keys with stable partitioning behavior/count route consistently. Choose a key for the entity whose ordering matters and watch for hot-key skew.","related":["Kafka","Kafka Topic"],"questions":["How does Message Key affect order-event recovery?"],"mistakes":["Assuming a guarantee at this boundary automatically covers external business effects."],"flow":["Entity identity","Partitioner","Partition"]},
  {"id":"kafka-leader","term":"Leader","contextOnly":true,"category":"Kafka","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"The replica coordinating writes for a partition.","explanation":"Producers send writes to the partition leader. On failure, eligible replicas can take over under cluster policy; this does not create a new partition.","related":["Kafka","Kafka Topic"],"questions":["How does Leader affect order-event recovery?"],"mistakes":["Assuming a guarantee at this boundary automatically covers external business effects."],"flow":["Producer","Leader append","Follower replication"]},
  {"id":"kafka-follower","term":"Follower","contextOnly":true,"category":"Kafka","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"A replica that copies a partition’s log from its leader.","explanation":"Replication progress determines whether it is in sync. Not every surviving stale follower is safe to elect without data-loss tradeoffs.","related":["Kafka","Kafka Topic"],"questions":["How does Follower affect order-event recovery?"],"mistakes":["Assuming a guarantee at this boundary automatically covers external business effects."],"flow":["Leader log","Copy records","In-sync state"]},
  {"id":"kafka-replica","term":"Replica","contextOnly":true,"category":"Kafka","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"A copy of one logical partition’s log.","explanation":"Copies are placed across brokers for resilience. Replication does not multiply ordinary consumer-group parallelism for that partition.","related":["Kafka","Kafka Topic"],"questions":["How does Replica affect order-event recovery?"],"mistakes":["Assuming a guarantee at this boundary automatically covers external business effects."],"flow":["Logical partition","Leader copy","Follower copies"]},
  {"id":"kafka-replication-factor","term":"Replication Factor","contextOnly":true,"category":"Kafka","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"The configured total number of replicas for a partition, including its leader.","explanation":"RF=3 means one leader and two followers. Durability also depends on ISR, acknowledgements and election policy.","related":["Kafka","Kafka Topic"],"questions":["How does Replication Factor affect order-event recovery?"],"mistakes":["Assuming a guarantee at this boundary automatically covers external business effects."],"flow":["RF 3","1 leader","2 followers"]},
  {"id":"kafka-acknowledgement","term":"Acknowledgement","contextOnly":true,"category":"Kafka","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"The producer’s configured confirmation of broker acceptance.","explanation":"acks=all waits on the current in-sync set; min.insync.replicas constrains availability for those writes. It says nothing about completion of external consumer effects.","related":["Kafka","Kafka Topic"],"questions":["How does Acknowledgement affect order-event recovery?"],"mistakes":["Assuming a guarantee at this boundary automatically covers external business effects."],"flow":["Producer send","Broker/ISR policy","Delivery result"]},
  {"id":"kafka-serialization","term":"Serialization","contextOnly":true,"category":"Kafka","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"Converting application values into bytes for transmission and storage.","explanation":"The consumer must deserialize using a compatible contract. Kafka accepting bytes does not prove their business schema is valid.","related":["Kafka","Kafka Topic"],"questions":["How does Serialization affect order-event recovery?"],"mistakes":["Assuming a guarantee at this boundary automatically covers external business effects."],"flow":["Object","Bytes","Reader object"]},
  {"id":"kafka-retention","term":"Retention","contextOnly":true,"category":"Kafka","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"The policy controlling how long or how much log data remains available.","explanation":"Consumer commits do not delete records. A lagging consumer can fall behind available data; set retention for recovery and business requirements.","related":["Kafka","Kafka Topic"],"questions":["How does Retention affect order-event recovery?"],"mistakes":["Assuming a guarantee at this boundary automatically covers external business effects."],"flow":["Append","Retain under policy","Cleanup"]},
  {"id":"kafka-compaction","term":"Compaction","contextOnly":true,"category":"Kafka","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"Eventual removal of superseded values for the same key in a log.","explanation":"It supports keyed state, not complete immutable history. Cleanup is asynchronous, offsets are not renumbered, and tombstone behavior/configuration matters.","related":["Kafka","Kafka Topic"],"questions":["How does Compaction affect order-event recovery?"],"mistakes":["Assuming a guarantee at this boundary automatically covers external business effects."],"flow":["Keyed versions","Background cleanup","Latest state"]},
  {"id":"kafka-rebalance","term":"Rebalance","contextOnly":true,"category":"Kafka","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"A coordinated change in consumer-group partition assignments.","explanation":"Membership and subscription changes can move ownership. Timing depends on the protocol; a replacement member may replay uncommitted work.","related":["Kafka","Kafka Topic"],"questions":["How does Rebalance affect order-event recovery?"],"mistakes":["Assuming a guarantee at this boundary automatically covers external business effects."],"flow":["Membership change","Coordination","New assignment"]},
  {"id":"kafka-kafka-connect","term":"Kafka Connect","contextOnly":true,"category":"Kafka","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"A framework for reusable integrations into and out of Kafka.","explanation":"Plugins implement external-system behavior and tasks execute the work. Validate each plugin’s schemas, offsets, retries and delivery guarantees.","related":["Kafka","Kafka Topic"],"questions":["How does Kafka Connect affect order-event recovery?"],"mistakes":["Assuming a guarantee at this boundary automatically covers external business effects."],"flow":["External system","Connector tasks","Kafka"]},
  {"id":"kafka-source-connector","term":"Source Connector","contextOnly":true,"category":"Kafka","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"A Connect integration that brings external data into Kafka.","explanation":"Source progress, snapshots and CDC behavior are plugin-specific. Do not assume every database connector captures every change type.","related":["Kafka","Kafka Topic"],"questions":["How does Source Connector affect order-event recovery?"],"mistakes":["Assuming a guarantee at this boundary automatically covers external business effects."],"flow":["External records","Source tasks","Kafka topic"]},
  {"id":"kafka-sink-connector","term":"Sink Connector","contextOnly":true,"category":"Kafka","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"A Connect integration that writes Kafka data into an external system.","explanation":"Destination writes and consumed offsets need a reliability contract. Retried deliveries may require idempotent/upsert behavior.","related":["Kafka","Kafka Topic"],"questions":["How does Sink Connector affect order-event recovery?"],"mistakes":["Assuming a guarantee at this boundary automatically covers external business effects."],"flow":["Kafka topic","Sink tasks","Destination"]},
  {"id":"airflow-task-instance","term":"Task Instance","category":"Airflow","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"One task’s execution record within a particular DAG run.","explanation":"A task definition is reusable. Its task instance holds state and attempts for one run; mapped tasks also have an index.","related":["Airflow","DAG"],"questions":["How does Task Instance affect a daily sales pipeline?"],"mistakes":["Confusing workflow definitions with the states of a particular execution."],"flow":["Task definition","DAG run","Task instance","Attempts + outcome"]},
  {"id":"airflow-scheduler","term":"Scheduler","category":"Airflow","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"The component that determines which runs and tasks are eligible.","explanation":"It checks scheduling, dependencies and limits, then submits work through the executor. Eligible does not mean already running.","related":["Airflow","DAG"],"questions":["How does Scheduler affect a daily sales pipeline?"],"mistakes":["Confusing workflow definitions with the states of a particular execution."],"flow":["Eligibility","Scheduled","Queued","Running"]},
  {"id":"airflow-executor","term":"Executor","category":"Airflow","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"The mechanism Airflow uses to dispatch task execution.","explanation":"The configured executor determines how work is submitted. Capacity and deployment affect where and when task code runs.","related":["Airflow","DAG"],"questions":["How does Executor affect a daily sales pipeline?"],"mistakes":["Confusing workflow definitions with the states of a particular execution."],"flow":["Scheduled task","Executor dispatch","Task execution"]},
  {"id":"airflow-xcom","term":"XCom","category":"Airflow","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"Small values or references passed between task instances.","explanation":"Keep bulk data in durable external storage; pass its URI and small metadata. Never use a worker-local variable as a shared data contract.","related":["Airflow","DAG"],"questions":["How does XCom affect a daily sales pipeline?"],"mistakes":["Confusing workflow definitions with the states of a particular execution."],"flow":["Producer","Small reference","Consumer"]},
  {"id":"airflow-sensor","term":"Sensor","category":"Airflow","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"A task that waits for an external condition.","explanation":"Reschedule mode releases the worker slot between checks. Deferrable operators use a different mechanism and require supported operators and a triggerer.","related":["Airflow","DAG"],"questions":["How does Sensor affect a daily sales pipeline?"],"mistakes":["Confusing workflow definitions with the states of a particular execution."],"flow":["Check","Not ready","Wait","Check again","Ready"]},
  {"id":"airflow-data-interval","term":"Data Interval","category":"Airflow","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"The time range a scheduled run is intended to process.","explanation":"An explicit interval timetable can schedule a run after its interval ends. Logical time is different from the wall-clock execution start.","related":["Airflow","DAG"],"questions":["How does Data Interval affect a daily sales pipeline?"],"mistakes":["Confusing workflow definitions with the states of a particular execution."],"flow":["Interval start","Interval end","Run becomes due"]},
  {"id":"airflow-catchup","term":"Catchup","category":"Airflow","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"Automatically scheduling eligible missing historical intervals.","explanation":"With catchup=False the scheduler generally creates the latest eligible interval, not every missed interval. Backfill is a separate explicit operation.","related":["Airflow","DAG"],"questions":["How does Catchup affect a daily sales pipeline?"],"mistakes":["Confusing workflow definitions with the states of a particular execution."],"flow":["Missing intervals","Catchup policy","Eligible runs"]},
  {"id":"airflow-backfill","term":"Backfill","category":"Airflow","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"An explicit request to process a historical date range.","explanation":"Choose the time range and reprocessing policy, then use rerun-safe tasks. Disabling catchup does not disable backfill.","related":["Airflow","DAG"],"questions":["How does Backfill affect a daily sales pipeline?"],"mistakes":["Confusing workflow definitions with the states of a particular execution."],"flow":["Choose range","Choose reprocessing policy","Historical runs"]},
  {"id":"airflow-trigger-rule","term":"Trigger Rule","category":"Airflow","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"The upstream-state condition required for a task to run.","explanation":"The default all_success requires successful parents. After a branch, none_failed_min_one_success can accept success plus skipped.","related":["Airflow","DAG"],"questions":["How does Trigger Rule affect a daily sales pipeline?"],"mistakes":["Confusing workflow definitions with the states of a particular execution."],"flow":["Parent states","Evaluate rule","Eligible or blocked"]},
  {"id":"airflow-taskflow","term":"TaskFlow","category":"Airflow","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"Airflow’s decorated-task API for defining tasks and passing small results.","explanation":"Calling a decorated task while defining a DAG constructs its workflow relationships; its Python body runs later as task work.","related":["Airflow","DAG"],"questions":["How does TaskFlow affect a daily sales pipeline?"],"mistakes":["Confusing workflow definitions with the states of a particular execution."],"flow":["Decorated function","DAG relationship","Task execution"]},
  {"id":"airflow-idempotency","term":"Idempotency","category":"Airflow","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"Repeating an operation has the same intended effect as applying it once.","explanation":"Use stable business keys and safe writes so retries do not duplicate data. Airflow retries do not make external writes exactly-once.","related":["Airflow","DAG"],"questions":["How does Idempotency affect a daily sales pipeline?"],"mistakes":["Confusing workflow definitions with the states of a particular execution."],"flow":["First attempt","Safe repeat","Same intended result"]},
  {"id":"airflow-dynamic-task-mapping","term":"Dynamic Task Mapping","category":"Airflow","style":"concept","difficulty":"Medium","interviewFrequency":0,"definition":"Creating task instances from a collection determined at runtime.","explanation":"Use expand to map over inputs. Each mapped instance has its own index and state, while concurrency limits still apply.","related":["Airflow","DAG"],"questions":["How does Dynamic Task Mapping affect a daily sales pipeline?"],"mistakes":["Confusing workflow definitions with the states of a particular execution."],"flow":["Input collection","Mapped instances","Downstream aggregation"]},
  {id:"entity",term:"Entity",aliases:["Entities"],category:"Data Modeling",style:"concept",difficulty:"Easy",interviewFrequency:0,definition:"A kind of thing the model tracks, such as Customer or Order.",explanation:"Distinguish the entity type from individual records. Decide its identity, lifecycle and relationships before choosing storage details.",related:["Attribute","Relationship","Primary Key"],questions:["When should an address be an entity rather than one field?"],mistakes:["Using an entity’s display name as guaranteed identity."],flow:["Business thing","Attributes + identity","Related records"]},
  {id:"attribute",term:"Attribute",aliases:["Attributes"],category:"Data Modeling",style:"concept",difficulty:"Easy",interviewFrequency:0,definition:"A property of an entity or relationship, such as a customer’s name or a purchase quantity.",explanation:"Place an attribute where it depends on the row’s key. Quantity purchased belongs to an order line, not to the product catalog.",related:["Entity","Grain"],questions:["Where should the purchase price of an item live?"],mistakes:["Putting event-specific values on a shared descriptive entity."],flow:["Record identity","Property of that record","Stored value"]},
  {id:"relationship",term:"Relationship",aliases:["Relationships"],category:"Data Modeling",style:"concept",difficulty:"Easy",interviewFrequency:0,definition:"A meaningful connection between entities, such as Customer places Order.",explanation:"Specify the verb, cardinality and optionality. Use appropriate keys or association records to implement the rule.",related:["Entity","Cardinality","Foreign Key"],questions:["Can a customer exist without any orders?"],mistakes:["Drawing a line without explaining how many records may match."],flow:["Customer","Places","Order"]},
  {id:"cardinality",term:"Cardinality",category:"Data Modeling",style:"concept",difficulty:"Medium",interviewFrequency:0,definition:"How many records on one side may be related to a record on the other side.",explanation:"Describe both directions and distinguish maximum count from optional participation. A many-to-many relationship often needs an associative entity.",related:["Relationship","Foreign Key"],questions:["How would you store students enrolled in several courses?"],mistakes:["Assuming a foreign key alone enforces one-to-one."],flow:["Business rule","Minimum + maximum participation","Key and uniqueness constraints"]},
  {id:"denormalization",term:"Denormalization",category:"Data Modeling",style:"concept",difficulty:"Medium",interviewFrequency:0,definition:"Deliberately combining or repeating selected data to support a read workload.",explanation:"Weigh simpler reads against extra storage, refresh cost and consistency responsibilities. Benchmark the workload and retain a clear row grain.",related:["Normalization","Grain","Star Schema"],questions:["Who maintains repeated customer attributes in a report table?"],mistakes:["Copying order totals to every line and summing them."],flow:["Authoritative tables","Governed read model","Refresh + reconcile"]},
  {id:"grain",term:"Grain",category:"Data Modeling",style:"concept",difficulty:"Medium",interviewFrequency:0,definition:"The precise business meaning of one row, such as one purchased order line.",explanation:"Declare grain before measures and dimension keys. Separate order-level and line-level observations, or document a valid allocation rule.",related:["Fact","Dimension","Star Schema"],questions:["Can an order delivery fee be summed safely from every order line?"],mistakes:["Mixing summary rows and detailed event rows in the same fact."],flow:["Business event","One row means…","Compatible keys + measures"]},
  {id:"fact",term:"Fact",aliases:["Facts","Fact table","Fact tables"],category:"Data Modeling",style:"concept",difficulty:"Medium",interviewFrequency:0,definition:"A business observation; a fact table stores observations at a defined grain with context keys and, often, measures.",explanation:"Keep row identity and measure additivity explicit. Keys are not measures just because they contain numbers; factless tables record events without numeric measures.",related:["Grain","Dimension"],questions:["Why should daily account balances not be summed across dates?"],mistakes:["Summing identifiers or incompatible measures."],flow:["Event","Grain + context keys","Measures or participation"]},
  {id:"dimension",term:"Dimension",aliases:["Dimensions","Dimension table","Dimension tables"],category:"Data Modeling",style:"concept",difficulty:"Medium",interviewFrequency:0,definition:"Descriptive context for observations, such as product category or customer city.",explanation:"Dimension attributes let users filter and group facts. A referenced dimension version key must identify one row; history policies determine which version describes an event.",related:["Fact","Surrogate Key","SCD Type 2"],questions:["Why can a customer dimension have multiple rows for one business customer?"],mistakes:["Joining facts to multiple historical versions at once."],flow:["Context attributes","Unique dimension version","Filter or group facts"]},
  {id:"surrogate-key",term:"Surrogate Key",category:"Data Modeling",style:"concept",difficulty:"Medium",interviewFrequency:0,definition:"An identifier assigned by the system rather than taken from business meaning.",explanation:"It can identify each warehouse version independently of source IDs. Keep source identity and business uniqueness rules as well; an added ID alone does not remove duplicate business events.",related:["Natural Key","Primary Key","SCD Type 2"],questions:["Why do Type 2 customer versions need different warehouse keys?"],mistakes:["Assuming a generated ID deduplicates incoming events."],flow:["Source identity","Assigned warehouse key","Specific stored row"]},
  {id:"natural-key",term:"Natural Key",category:"Data Modeling",style:"concept",difficulty:"Medium",interviewFrequency:0,definition:"An identifier with business meaning, such as a governed product code.",explanation:"Evaluate uniqueness, stability, reuse and cross-source collisions. A business identifier can remain useful even when a surrogate key identifies stored rows.",related:["Surrogate Key","Primary Key"],questions:["What happens if two source systems use the same customer ID?"],mistakes:["Assuming every business identifier is immutable and globally unique."],flow:["Business identifier","Validate scope + stability","Uniqueness rule"]},
  {id:"snowflake-schema",term:"Snowflake Schema",category:"Data Modeling",style:"concept",difficulty:"Medium",interviewFrequency:0,definition:"An analytical model in which some dimension attributes are normalized into related tables.",explanation:"For example, Product references Category. This centralizes a hierarchy but adds a join path; evaluate governance and query usability against a flattened dimension.",related:["Star Schema","Normalization","Dimension"],questions:["When is a shared category hierarchy worth an extra join?"],mistakes:["Assuming snowflake always beats star performance."],flow:["Fact sales","Product dimension","Category dimension"]},
  {id:"scd",term:"SCD",expanded:"Slowly Changing Dimension",category:"Data Modeling",style:"concept",difficulty:"Medium",interviewFrequency:0,definition:"A policy for handling changes to descriptive dimension attributes.",explanation:"Type 1 overwrites; Type 2 adds a version. Choose per attribute and reporting need, then define effective time and late-change behavior.",related:["SCD Type 1","SCD Type 2","Dimension"],questions:["Do reports need the current city or the city at the sale time?"],mistakes:["Choosing history behavior without asking the reporting requirement."],flow:["Attribute change","History policy","Updated or versioned rows"]},
  {id:"scd-type-1",term:"SCD Type 1",category:"Data Modeling",style:"concept",difficulty:"Easy",interviewFrequency:0,definition:"Overwriting a dimension attribute without preserving its old value in that row.",explanation:"Useful when only current values are needed or a correction should replace the old value. Past facts referencing the same key now see the updated description.",related:["SCD","SCD Type 2"],questions:["Would overwriting a customer city change a historical city report?"],mistakes:["Expecting old values to remain available after overwrite."],flow:["Existing row","Overwrite value","Current description only"]},
  {id:"join",term:"JOIN",aliases:["JOINs"],category:"SQL",style:"sql",difficulty:"Medium",interviewFrequency:0,definition:"Combine rows from two tables when a condition matches.",explanation:"INNER JOIN returns matching pairs. LEFT JOIN also keeps unmatched left rows with null right-side values. Multiple matches can multiply rows.",related:["Primary Key","Foreign Key","NULL"],questions:["Why can one customer appear twice after a join?","How do you keep customers without orders?"],mistakes:["Assuming the right-side key is unique.","Filtering right-side NULL values away after a LEFT JOIN."],flow:["Customers + orders","Match customer IDs","One row per matching pair"]},
  {id:"cte",term:"CTE",expanded:"Common Table Expression",category:"SQL",style:"concept",difficulty:"Medium",interviewFrequency:0,definition:"A query-scoped named result defined with WITH.",explanation:"Use a CTE to explain intermediate steps. It is not a permanent table or an automatic performance improvement.",related:["SELECT","Aggregate"],questions:["When is a CTE clearer than a nested query?"],mistakes:["Assuming every CTE is cached."],flow:["WITH name AS (query)","Reference name","Final result"]},
  {id:"aggregate",term:"Aggregate",category:"SQL",style:"concept",difficulty:"Easy",interviewFrequency:0,definition:"A calculation that summarizes several rows, such as SUM or COUNT.",explanation:"GROUP BY returns one summary per key. COUNT(*) counts rows; COUNT(column) skips NULL values. SUM ignores NULL inputs and returns NULL when there are no non-null inputs.",related:["NULL","Window Function"],questions:["How do COUNT(*) and COUNT(column) differ?"],mistakes:["Assuming SUM over an empty set returns zero."],flow:["Input rows","Group + summarize","Summary rows"]},
  {id:"primary-key",term:"Primary Key",category:"SQL",style:"concept",difficulty:"Easy",interviewFrequency:0,definition:"A column or set of columns that uniquely identifies a table row and cannot be null.",explanation:"An order ID identifies an order. A customer ID cannot identify an order if a customer places several orders.",related:["Foreign Key","JOIN"],questions:["Why is customer_id not an order’s primary key?"],mistakes:["Choosing a key that is not unique."],flow:["Table row","Unique non-null key","Reliable identity"]},
  {id:"foreign-key",term:"Foreign Key",category:"SQL",style:"concept",difficulty:"Easy",interviewFrequency:0,definition:"A constraint linking column values to a referenced key in another or the same table.",explanation:"orders.customer_id references customers.id. Many orders may reference one customer. Nullability is a separate constraint.",related:["Primary Key","JOIN"],questions:["Does a foreign key make the child column unique?"],mistakes:["Confusing a relationship with a one-to-one relationship."],flow:["Order customer_id","Referenced customers.id","Related customer"]},
  {id:"null",term:"NULL",category:"SQL",style:"sql",difficulty:"Easy",interviewFrequency:0,definition:"A marker for a missing or unknown value, not zero or empty text.",explanation:"Use IS NULL to test missing values. Comparisons such as = NULL evaluate to unknown; WHERE retains only true conditions.",related:["WHERE","Aggregate"],questions:["Why does column = NULL not find missing rows?"],mistakes:["Replacing missing values with zero without a business rule."],flow:["Unknown value","IS NULL test","True or false"]},
  { id: "rdd", term: "RDD", expanded: "Resilient Distributed Dataset", aliases: ["RDDs"], category: "Spark", style: "spark", difficulty: "Medium", interviewFrequency: 78, definition: "Spark’s immutable distributed collection for low-level transformations and fine-grained control.", explanation: "Explain partition-level computation, lazy evaluation, and lineage-based recovery. Contrast explicit RDD functions with the optimizer-visible expressions of DataFrames.", related: ["DataFrame", "Partitioning", "Shuffle"], questions: ["When would you choose an RDD over a DataFrame?", "How does lineage help recover a lost partition?"], mistakes: ["Calling collect() on a dataset too large for the driver.", "Assuming a transformation runs immediately."], flow: ["Partitioned source", "Lazy transformations", "Action → tasks"] },
  { id: "dataframe", term: "DataFrame", aliases: ["DataFrames"], category: "Spark", style: "spark", difficulty: "Medium", interviewFrequency: 86, definition: "A distributed table with named columns and a schema that Spark can optimize.", explanation: "Interviewers use DataFrames to explore schemas, query plans, and built-in expressions. Explain how structured expressions give Catalyst information it cannot infer from arbitrary Python functions.", related: ["RDD", "Catalyst Optimizer", "Partitioning"], questions: ["Why can a DataFrame outperform an RDD?", "How do you inspect a DataFrame’s execution plan?"], mistakes: ["Using a Python UDF when a built-in expression exists.", "Treating schema inference as data validation."], flow: ["Data + schema", "Logical plan", "Optimized execution"] },
  { id: "catalyst", term: "Catalyst Optimizer", aliases: ["Catalyst"], category: "Spark", style: "spark", difficulty: "Hard", interviewFrequency: 76, definition: "Spark SQL’s framework for analyzing, optimizing, and planning structured queries.", explanation: "Discuss predicate pushdown, column pruning, and logical versus physical plans. Be clear that the execution engine runs the physical plan after planning.", related: ["DataFrame", "Shuffle", "DAG"], questions: ["What is predicate pushdown?", "How do logical and physical plans differ?"], mistakes: ["Expecting Catalyst to optimize arbitrary RDD functions.", "Assuming every filter can be pushed into a source."], flow: ["Parsed query", "Analyzed + optimized plan", "Physical plan"] },
  { id: "shuffle", term: "Shuffle", category: "Spark", style: "concept", difficulty: "Hard", interviewFrequency: 82, definition: "Redistribution of records across partitions, often involving network and disk I/O.", explanation: "Joins and aggregations often require records with matching keys to meet. Explain the cost of moving data and how skew causes uneven task duration.", related: ["Partitioning", "DataFrame", "RDD"], questions: ["Which operations cause a shuffle?", "How would you diagnose a skewed join?"], mistakes: ["Repartitioning repeatedly without checking the plan.", "Ignoring hot keys and uneven partition sizes."], flow: ["Source partitions", "Exchange by key", "Destination partitions"] },
  { id: "partitioning", term: "Partitioning", category: "Spark", style: "concept", difficulty: "Medium", interviewFrequency: 81, definition: "Dividing data into units that can be stored or processed independently.", explanation: "Distinguish execution partitions from directory partitions on storage. Reason about parallelism, skew, pruning, and small files when choosing a strategy.", related: ["Shuffle", "RDD", "DataFrame"], questions: ["How do repartition and coalesce differ?", "What happens when partitions are too small?"], mistakes: ["Confusing storage partitioning with task parallelism.", "Partitioning storage by a very high-cardinality column."], flow: ["Input records", "Partition strategy", "Parallel tasks"] },
  { id: "transformations", term: "Transformations", category: "Spark", style: "concept", difficulty: "Easy", interviewFrequency: 0, definition: "Operations such as map and filter that describe a new distributed dataset without immediately producing a final result.", explanation: "Explain lazy evaluation and immutability: a transformation returns a new RDD or DataFrame, while an action requests computation.", related: ["RDD", "DataFrame", "DAG"], questions: ["Why are Spark transformations lazy?", "Does filter modify the original dataset?"], mistakes: ["Assuming a transformation runs immediately.", "Discarding the transformed result and reusing the unchanged input."], flow: ["Input data", "Lazy transformation", "Action requests result"] },
  { id: "dag", term: "DAG", expanded: "Directed Acyclic Graph", category: "Airflow", style: "concept", difficulty: "Medium", interviewFrequency: 74, definition: "A graph of directed dependencies with no cycles.", explanation: "Use a DAG to reason about task ordering, parallel work, and retries. Airflow DAGs orchestrate tasks; Spark execution DAGs describe distributed computation.", related: ["Airflow", "RDD"], questions: ["Why must a workflow graph be acyclic?", "How do retries affect downstream tasks?"], mistakes: ["Creating circular dependencies.", "Putting heavy computation into DAG parsing."], flow: ["Extract", "Transform", "Load"] },
  { id: "kafka-topic", term: "Kafka Topic", category: "Kafka", style: "concept", difficulty: "Medium", interviewFrequency: 72, definition: "A named stream of records organized into partitions in Kafka.", explanation: "Explain ordering within a partition, offsets, retention, and consumer groups. A topic is not a global ordered queue when it has multiple partitions.", related: ["Kafka", "Partitioning", "CDC"], questions: ["Where does Kafka guarantee ordering?", "How do consumer groups share partitions?"], mistakes: ["Assuming global ordering across partitions.", "Equating consumer offsets with deletion of records."], flow: ["Producer", "Topic partitions", "Consumer group"] },
  { id: "window-function", term: "Window Function", aliases: ["Window Functions"], category: "SQL", style: "concept", difficulty: "Medium", interviewFrequency: 88, definition: "A SQL calculation over related rows that preserves individual output rows.", explanation: "Practice rankings, running totals, and deduplication. Explain PARTITION BY, ORDER BY, and window frames, including ties and deterministic ordering.", related: ["SELECT", "Partitioning"], questions: ["How do ROW_NUMBER and RANK differ?", "How would you calculate a running total?"], mistakes: ["Omitting a tie-breaker for deduplication.", "Ignoring the default window frame."], flow: ["Rows", "Partition + order + frame", "Per-row result"] },
  { id: "star-schema", term: "Star Schema", category: "SQL", style: "concept", difficulty: "Medium", interviewFrequency: 69, definition: "An analytical model with a central fact table linked to dimension tables.", explanation: "Start with the fact grain, then define measures and dimensions. Discuss why a clear grain avoids double-counting and supports consistent analysis.", related: ["SCD Type 2", "Normalization"], questions: ["How do you choose fact-table grain?", "How does a star differ from a snowflake schema?"], mistakes: ["Mixing multiple grains in one fact table.", "Joining facts through non-unique dimension keys."], flow: ["Dimensions", "Fact table at fixed grain", "Analytical query"] },
  { id: "scd-type-2", term: "SCD Type 2", category: "SQL", style: "concept", difficulty: "Hard", interviewFrequency: 73, definition: "A dimension-history technique that inserts a new row for each tracked change.", explanation: "Explain surrogate keys, effective intervals, current flags, and as-of joins. Address late-arriving changes and non-overlapping validity intervals.", related: ["Star Schema", "CDC"], questions: ["How do you preserve a customer’s address history?", "How would you join facts to the correct historical version?"], mistakes: ["Overwriting historical rows.", "Leaving overlapping effective-date ranges."], flow: ["Changed record", "Expire prior version", "Insert new version"] },
  { id: "select", term: "SELECT", category: "SQL", style: "sql", difficulty: "Easy", interviewFrequency: 95, definition: "Specifies the expressions and columns returned by a SQL query.", explanation: "Explain projection and expression evaluation. Distinguish SQL’s logical processing order from the order clauses are written.", related: ["FROM", "WHERE", "Window Function"], questions: ["Why avoid SELECT * in production pipelines?"], mistakes: ["Depending on an unstable column order."], flow: ["Input relation", "Projection", "Result columns"] },
  { id: "from", term: "FROM", category: "SQL", style: "sql", difficulty: "Easy", interviewFrequency: 90, definition: "Identifies the source relations for a SQL query.", explanation: "Discuss tables, subqueries, and join cardinality. A join can multiply rows when keys are not unique.", related: ["SELECT", "WHERE"], questions: ["How can a join unexpectedly multiply row counts?"], mistakes: ["Joining without understanding key uniqueness."], flow: ["Tables or subqueries", "Joins", "Input relation"] },
  { id: "where", term: "WHERE", category: "SQL", style: "sql", difficulty: "Easy", interviewFrequency: 92, definition: "Filters input rows using a predicate before grouping.", explanation: "Contrast WHERE with HAVING and explain SQL’s three-valued logic when NULL is present.", related: ["SELECT", "FROM"], questions: ["How does WHERE differ from HAVING?"], mistakes: ["Using = NULL instead of IS NULL."], flow: ["Input rows", "Predicate", "Matching rows"] },
  { id: "airflow", term: "Airflow", category: "Airflow", style: "tool", difficulty: "Medium", interviewFrequency: 67, definition: "A platform for authoring, scheduling, and monitoring batch workflows.", explanation: "Discuss orchestration, task dependencies, retries, backfills, and idempotent tasks.", related: ["DAG", "dbt"], questions: ["How do you make a retried task safe?"], mistakes: ["Treating Airflow as a streaming processing engine."], flow: ["DAG definition", "Scheduler", "Task execution"] },
  { id: "kafka", term: "Kafka", category: "Kafka", style: "tool", difficulty: "Medium", interviewFrequency: 71, definition: "A distributed event-streaming platform built around partitioned logs.", explanation: "Explain producers, brokers, consumers, retention, and the scope of delivery guarantees.", related: ["Kafka Topic", "CDC"], questions: ["What does at-least-once delivery mean for a consumer?"], mistakes: ["Assuming retries cannot produce duplicates."], flow: ["Producer", "Broker log", "Consumer"] },
  { id: "dbt", term: "dbt", category: "SQL", style: "tool", difficulty: "Medium", interviewFrequency: 62, definition: "A framework for building, testing, and documenting data transformations.", explanation: "Discuss model dependencies, materializations, tests, and incremental processing in a warehouse.", related: ["DAG", "Star Schema"], questions: ["When would you choose an incremental model?"], mistakes: ["Ignoring late-arriving records in an incremental filter."], flow: ["Source tables", "SQL models + tests", "Analytics tables"] },
  { id: "normalization", term: "Normalization", category: "SQL", style: "concept", difficulty: "Medium", interviewFrequency: 58, definition: "Organizing relational data to reduce redundancy and update anomalies.", explanation: "Explain functional dependencies and the tradeoff between normalized transactional models and analytical dimensions.", related: ["Star Schema"], questions: ["What is an update anomaly?"], mistakes: ["Assuming more normalization always improves analytical query performance."], flow: ["Redundant relation", "Functional dependencies", "Decomposed relations"] },
  { id: "cdc", term: "CDC", expanded: "Change Data Capture", category: "Kafka", style: "concept", difficulty: "Hard", interviewFrequency: 64, definition: "Capturing inserts, updates, and deletes from a source for downstream processing.", explanation: "Discuss snapshots, change logs, ordering, deletes, and idempotent application of changes.", related: ["Kafka Topic", "SCD Type 2"], questions: ["How do you handle duplicate change events?"], mistakes: ["Ignoring deletes or source transaction order."], flow: ["Source changes", "Change stream", "Downstream state"] },
];

export const glossaryLookup = new Map(glossary.flatMap(item => [item.id, item.term, ...(item.aliases ?? [])].map(key => [key.toLowerCase(), item] as const)));
export function getGlossaryItem(term: string) { return glossaryLookup.get(term.toLowerCase()); }

export type GlossaryToken = { text: string; item?: GlossaryItem };
const names = glossary.filter(item => !item.contextOnly).flatMap(item => [item.term, ...(item.aliases ?? [])]).sort((a, b) => b.length - a.length);
const escape = (text: string) => text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
const pattern = new RegExp(`(?<![\\p{L}\\p{N}_])(${names.map(escape).join("|")})(?![\\p{L}\\p{N}_])`, "giu");
export function tokenizeGlossary(text: string): GlossaryToken[] {
  const result: GlossaryToken[] = []; let cursor = 0;
  for (const match of text.matchAll(pattern)) {
    const index = match.index!;
    if (index > cursor) result.push({ text: text.slice(cursor, index) });
    const item = getGlossaryItem(match[0]);
    // Ordinary prose words such as “from” should not become SQL pills.
    result.push({ text: match[0], item: item?.style === "sql" && match[0] !== item.term ? undefined : item });
    cursor = index + match[0].length;
  }
  if (cursor < text.length) result.push({ text: text.slice(cursor) });
  return result;
}
