import type { SparkLesson } from "@/lib/spark-lessons";
export type KafkaVisual="intro"|"event"|"partitions"|"brokers"|"keys"|"groups"|"offsets"|"replicas"|"delivery"|"schema"|"connect"|"streams"|"production"|"review";
type Question=SparkLesson["quiz"][number];
export interface KafkaLesson extends SparkLesson {visual:KafkaVisual;takeaway:string;resource:string;decision:Question;setup:string;codeTitle:string;}
const q=(question:string,options:string[],correct:number,explanation:string):Question=>({question,options,correct,explanation});
const pythonSetup="Python 3 standard-library learning model. Run locally if you wish; it does not connect to Kafka. The website illustrates expected results and does not execute your draft.";
const cliSetup="Kafka 4.1 baseline. These Bash commands require a separately running local Kafka broker at localhost:9092 and the Kafka distribution in your current directory (for example, inside WSL). Use a disposable learning environment. They are not PowerShell commands and are not executed by this website. Production clusters also require approved authentication/TLS configuration.";
interface Spec {id:string;title:string;visual:KafkaVisual;idea:string;why:string;remember:string;takeaway:string;code:string;output:string;steps:string[];decision:Question;hint:string;solution:string;interview:[string,string,string][];mistakes:[string,string,string,string,string][];quiz:Question[];doc:string;setup?:string;codeTitle?:string;}
const specs:Spec[]=[
 {id:"introduction",title:"Introduction to Apache Kafka",visual:"intro",idea:"An order can interest fulfillment, analytics and fraud detection. Instead of the checkout service calling each system directly, a Producer publishes an event to Kafka. Consumers read it independently, while Kafka retains it according to the topic’s policy.",why:"A slow analytics service need not be on the checkout request path. Retained events can be replayed while they remain available.",remember:"Kafka is an event-streaming platform, not an automatic guarantee that every downstream system is correct or caught up. Retention, access and processing contracts still matter.",takeaway:"Publish once to a retained stream; independent consumers can make progress at different speeds.",code:`import json
event = {"event_id": "evt-1042", "type": "OrderCreated",
         "order_id": 1042, "amount": 499}
# Local event representation, not a Kafka send.
print(json.dumps(event, sort_keys=True))`,output:'{"amount": 499, "event_id": "evt-1042", "order_id": 1042, "type": "OrderCreated"}',steps:["Checkout creates a business fact with a stable event identity.","In a real pipeline, a producer serializes and publishes that event.","Separate consumer applications handle fulfillment and analytics independently."],decision:q("Analytics is offline briefly. How can checkout avoid synchronously waiting for it?",["Call analytics repeatedly in the checkout request","Publish to a retained topic and let analytics consume independently","Delete every event immediately after checkout"],1,"Decouple publication from downstream processing; retention and capacity must cover the outage."),hint:"Separate creating an event from every system processing it.",solution:"Publish OrderCreated with a stable event ID to orders. Use independent consumer applications and monitor lag. Plan retention for recovery rather than assuming infinite replay.",interview:[["Why is Kafka used?","It separates producers from consumers through retained, partitioned event streams. It supports independent consumption, replay within retention and scalable processing.","How long can a consumer remain offline safely?"],["Kafka versus a traditional queue?","Ordinary Kafka consumer groups share partition work, while separate groups independently read the same log. Consumption does not delete records; retention governs availability. Queue products and Kafka share groups have other semantics, outside this module.","Why is an acknowledgement not the same as deleting a Kafka record?"]],mistakes:[["Treating Kafka as infinite storage","Old data may leave the log.","Set retention to the recovery requirement.","Replay any event forever","Replay only data still retained"],["Coupling checkout to every reader","Downstream latency spreads upstream.","Separate publication and processing contracts.","Wait for all analytics dashboards","Publish and monitor downstream progress"]],quiz:[q("Two independent applications need all order events. What should they use?",["One shared group to split the records","Separate consumer groups","One broker per customer"],1,"Different groups maintain independent progress."),q("Does reading an event delete it?",["Yes","No; retention/compaction govern log cleanup","Only if its key is numeric"],1,"Consumer progress and retention are separate concerns.")],doc:"getting-started/introduction/"},
 {id:"producers-consumers-topics",title:"Producers, Consumers & Topics",visual:"event",idea:"A Producer writes records to a named Kafka Topic. A Consumer fetches records. Event, record and message are often used for the same item; its key, value, headers and timestamp carry the application contract.",why:"Several checkout instances can publish to orders without choosing a particular analytics worker.",remember:"Multiple producers can interleave writes. They do not create a global business ordering across a partitioned topic.",takeaway:"Producers write records to a topic; consumers fetch records from partitions.",code:`# Bash / WSL; run from an installed Kafka distribution.
bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --if-not-exists --topic dataprep-orders --partitions 3 --replication-factor 1
printf '%s\n' '{"event_id":"evt-1042","order_id":1042,"amount":499}' | bin/kafka-console-producer.sh --bootstrap-server localhost:9092 --topic dataprep-orders
bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic dataprep-orders --from-beginning --max-messages 1`,setup:cliSetup,codeTitle:"Kafka CLI · Bash · local broker required",output:"On a fresh learning topic, the consumer prints the JSON order. With existing records, --from-beginning may read an older retained record. Re-running the producer appends another record.",steps:["Create a disposable three-partition topic; replication factor 1 is only for a one-broker lab.","The console producer sends the JSON as a string value without a key.","The console consumer fetches a retained record; its read does not delete the log entry."],decision:q("Orders and payments have different event contracts. What is a reasonable boundary?",["Use explicit orders and payments topics/contracts","Make a broker for every JSON field","Call every record a consumer group"],0,"Topic boundaries should reflect ownership, access, retention and event contracts."),hint:"A topic is a named stream, not a machine.",solution:"Define orders and payments topic contracts with consistent event identities. Let producers publish without embedding knowledge of each consumer instance.",interview:[["What is a topic?","A named stream partitioned into ordered logs. Producers publish records; consumer applications subscribe and track progress.","When might two event types share a topic?"],["Can several producers write to one topic?","Yes. Writes are appended to partitions, and multiple producers can interleave. Establish keys and business sequence checks when order matters.","Does producer clock time establish a global topic order?"]],mistakes:[["Naming a topic after a transient consumer instance","Deployment changes leak into the data contract.","Use a stable stream boundary.","orders-for-worker-273","orders with independent consumer groups"],["Assuming a successful send means analytics finished","Broker acceptance is not consumer processing.","Monitor both publication and downstream processing.","Send acknowledged means dashboard updated","Track consumption and sink effects separately"]],quiz:[q("Where does a producer normally send a record?",["To a topic/partition via brokers","To a random consumer’s heap","To its own committed consumer offset"],0,"Consumers fetch later; the producer does not push directly into a group member."),q("Two checkout producers send concurrently. What is safe to assume?",["A global business order across topics","An append order within each partition, not a global topic order","Identical timestamps prevent interleaving"],1,"Partition logs have local order; application intent may need additional sequencing.")],doc:"getting-started/quickstart/"},
 {id:"partitions-offsets",title:"Partitions & Offsets",visual:"partitions",idea:"A Kafka Topic contains partitions. Each partition is an ordered log with its own Offset. P0:2 and P1:2 are different positions; there is no single topic-wide offset.",why:"Partitions enable storage and consumer parallelism while keeping each log’s order understandable.",remember:"Offsets are positions, not guaranteed dense row numbers forever. Retention and compaction can leave earlier data unavailable or create gaps.",takeaway:"Identify a record position with topic + partition + offset.",code:`logs = {0: ["A", "B", "C"], 1: ["D", "E"]}
for partition, events in logs.items():
    for offset, event in enumerate(events):
        print(f"orders P{partition}:{offset} {event}")
# Contiguous offsets only in this fresh-log learning fixture.`,output:"orders P0:0 A\norders P0:1 B\norders P0:2 C\norders P1:0 D\norders P1:1 E",steps:["Create two separate ordered teaching logs.","Number positions independently in each partition.","P0:0 and P1:0 identify different records, even though the offset number matches."],decision:q("A record is described only as offset 2. What is missing?",["Nothing; offsets are globally unique","Its topic and partition","Its consumer’s screen size"],1,"The log location needs the topic and partition as well as the offset."),hint:"Both P0 and P1 can contain offset 2.",solution:"Record the coordinate (orders, partition 0, offset 2). For downstream deduplication across republished business events, also use a stable business/event identifier.",interview:[["Why use partitions?","They distribute log storage and allow parallel consumption. More partitions bring costs such as metadata, recovery, rebalances and key-remapping implications.","Why not make a million partitions by default?"],["What is an offset?","A position in one partition’s log. It is not a global record ID and may outlive the availability of the record after cleanup.","Can compaction renumber the remaining offsets?"]],mistakes:[["Treating offsets as global IDs","Different partitions reuse offset numbers.","Keep the full log coordinate.","Deduplicate on offset alone","Track topic + partition + offset"],["Assuming unlimited partitions are always faster","Coordination and operational overhead increase.","Size for workload and parallelism requirements.","Maximize partitions without measurement","Measure throughput, ordering and operational cost"]],quiz:[q("P0:1 contains B; P1:1 contains E. Are they the same record?",["Yes","No","Only if one consumer reads both"],1,"Partition is part of the coordinate."),q("In an ordinary consumer group with one partition, how many members can actively own that partition?",["One at a time","Every member simultaneously","None"],0,"Partition ownership bounds this form of group parallelism.")],doc:"getting-started/introduction/"},
 {id:"brokers-cluster",title:"Brokers & Kafka Cluster",visual:"brokers",idea:"A Broker is a server that stores partition replicas and serves requests. A cluster distributes topic partitions across brokers. The topic is a logical stream, not a single machine.",why:"Separating the stream from machine placement lets the system spread load and maintain replicas across failures.",remember:"Kafka 4.x uses KRaft metadata management. Controllers manage cluster metadata; they are not the application consumers. Broker and controller deployment roles can be separated.",takeaway:"Topics contain partitions; brokers host replicas of those partitions.",code:`# Placement sketch, not a live cluster query.
leaders = {0: "broker-1", 1: "broker-2", 2: "broker-3"}
for partition, broker in leaders.items():
    print(f"orders P{partition} leader: {broker}")`,output:"orders P0 leader: broker-1\norders P1 leader: broker-2\norders P2 leader: broker-3",steps:["Start with one topic and three partitions.","Place their leaders across three different brokers.","Replicas, introduced later, add copies; they do not create additional logical partitions."],decision:q("Broker 1 hosts orders P0 and payments P2. Is this valid?",["No; one broker is one topic","Yes; a broker can host partitions from several topics","Only if offsets are globally unique"],1,"A broker is storage/serving infrastructure, not the topic itself."),hint:"Distinguish logical data from its physical host.",solution:"Draw topics separately from broker boxes and label hosted partition replicas. Review leader placement and replica distribution, not only the number of brokers.",interview:[["Topic versus broker?","A topic names a partitioned stream; a broker is a server hosting replicas and serving data requests. Many topics can share a broker.","Can one topic span several brokers?"],["What do KRaft controllers do?","They manage cluster metadata and coordination. Data-bearing brokers serve partition data; deployment roles depend on cluster configuration.","Does adding a broker automatically fix a hot message key?"]],mistakes:[["Equating a topic with one server","It hides placement and failure behavior.","Separate logical partitions from hosting brokers.","orders equals broker-1","orders partitions distributed across brokers"],["Assuming a broker count equals consumer count","Consumer scaling follows assignment and partitions.","Size producer, broker and consumer resources separately.","Three brokers require three consumers","Partition count and workload guide consumer parallelism"]],quiz:[q("Does moving P0’s leader change its topic name?",["Yes","No","Only if the client is Python"],1,"Logical identity does not depend on the current leader host."),q("Two brokers host copies of P0. How many logical P0 partitions are there?",["Two","One","Zero until a consumer reads"],1,"Replicas copy one partition; they do not create new partition IDs.")],doc:"getting-started/introduction/"},
 {id:"message-keys",title:"Message Keys & Partitioning",visual:"keys",idea:"A Message Key lets a partitioner route related events consistently. With stable key bytes, partition count and partitioner behavior, the same key normally maps to the same partition.",why:"OrderCreated, PaymentReceived and OrderShipped for one order can be processed in partition order when published to the same topic using an order key.",remember:"Our visual uses an explicit teaching routing table, not Kafka’s default hash. Changing partition counts or partitioners can move keys; different topics do not share an ordering guarantee.",takeaway:"Choose a key for the entity whose order matters, and plan for skew and routing changes.",code:`# Explicit teaching routes, NOT Kafka's default hash.
routes = {"101": 2, "205": 0, "330": 1}
for key in ["101", "205", "101", "330"]:
    print(f"customer {key} -> P{routes[key]}")`,output:"customer 101 -> P2\ncustomer 205 -> P0\ncustomer 101 -> P2\ncustomer 330 -> P1",steps:["Look up the key in the declared teaching routing table.","Both records for customer 101 enter P2.","Within P2, append order is preserved; event-time/business order still needs application discipline."],decision:q("You need order lifecycle events together in one topic. Which key best matches that requirement?",["A new random key for every event","order_id","The producer machine’s current CPU usage"],1,"A stable order key groups that order’s records under a stable routing configuration."),hint:"Key by the entity whose sequence must stay together.",solution:"Use the same serialized order_id for lifecycle events in the same topic. Keep the partitioning strategy stable, check hot keys and include a business sequence/version if several producers can race.",interview:[["Why use message keys?","They support consistent partition routing and keyed processing. Key choice balances related-event ordering against skew and parallelism.","What happens when one customer generates most traffic?"],["Does the same key guarantee order forever?","Only within the relevant partition and producer/application semantics. Routing changes, cross-topic events and concurrent producers require extra care.","How would you expand partitions without silently breaking an ordering assumption?"]],mistakes:[["Assuming customer keys guarantee order across topics","orders and payments are independent logs.","Reconcile cross-topic events explicitly.","Same key means global order","Partition-local order plus application correlation"],["Using a constant key for all orders","One partition can become hot.","Choose a meaningful distributed key.","key='all-orders'","key=order_id with skew monitoring"]],quiz:[q("Under the displayed routes, where does the second customer 101 event go?",["P0","P1","P2"],2,"The explicit route maps 101 to P2 consistently."),q("What may change when a topic gains partitions?",["Existing record offsets are renumbered","Future key routing may change","Every old record is deleted immediately"],1,"A partition-count-dependent hash can choose a different partition for future records.")],doc:"configuration/producer-configs/"},
 {id:"consumer-groups",title:"Consumer Groups",visual:"groups",idea:"In an ordinary Kafka consumer group, each partition is assigned to one member at a time. Members divide the topic’s partition work. A separate group has its own assignment and progress.",why:"Scale analytics workers without intentionally processing every record in every worker. Independently, a fraud group can read the whole stream too.",remember:"The diagram uses a deterministic round-robin teaching assignment, not a prediction of Kafka’s configured assignor. Failure detection and reassignment take time; transitions can replay uncommitted work. Share groups are outside this lesson.",takeaway:"Partitions bound active parallelism within an ordinary consumer group.",code:`partitions = range(3)
members = ["A", "B", "C", "D"]
assigned = {member: [] for member in members}
for p in partitions:
    assigned[members[p % len(members)]].append(p)
print(assigned)
# Teaching assignment only, not Kafka's actual assignor.`,output:"{'A': [0], 'B': [1], 'C': [2], 'D': []}",steps:["Three partitions supply three independent ownership units.","A fourth member receives no partition in this example.","After a member fails, the group reassigns affected work; actual assignment depends on protocol and strategy."],decision:q("A group has P0, P1, P2 and four healthy members. Can all four own a partition?",["Yes, each record is randomly shared","No; at least one member has no partition","Only if offsets start at 100"],1,"Three ownership units cannot occupy four members simultaneously."),hint:"Count partitions, not records.",solution:"Expect at least one idle member. On failure, wait for group coordination and reassign affected partitions. Resume from committed progress and make processing replay-safe.",interview:[["What happens when a consumer crashes?","Once detected, group coordination reassigns its partitions. A new owner resumes from committed progress, subject to offset availability/reset policy; uncommitted effects may repeat.","Why is reassignment not instantaneous?"],["How do two groups read the same topic?","They maintain separate assignments and offsets, so each group can process the stream independently.","Should fraud and analytics share a group ID if both need every event?"]],mistakes:[["Adding consumers beyond partitions for throughput","Extra members may have no assignment.","Measure partition and processing bottlenecks.","Four consumers speed up three busy partitions automatically","Size members to partitions and workload"],["Sharing a group ID across independent applications","They divide work instead of both reading it all.","Use separate group identities.","Fraud and analytics share analytics-v1","fraud-v1 and analytics-v1"]],quiz:[q("In the initial diagram, Consumer B owns P1 and fails. What must happen?",["P1 is deleted","Ownership is reassigned after coordination","The topic gains a global offset"],1,"Group membership changes drive reassignment."),q("Would a separate fraud group steal P0 from analytics?",["Yes","No; group assignments are independent","Only with three brokers"],1,"Ownership exclusivity is scoped to a group.")],doc:"javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html"},
 {id:"consumer-offsets",title:"Consumer Offsets",visual:"offsets",idea:"The committed Offset is the next offset a group intends to consume for a partition. After successfully processing P1:211, commit 212—not 211. Fetch position, processed progress and committed progress are different.",why:"A restart or reassignment uses durable progress rather than a lost in-memory cursor.",remember:"The example assumes the committed record is still retained. If no valid offset exists, the configured reset policy matters. Do not commit past unfinished records when processing asynchronously.",takeaway:"Process safely, then commit the next offset according to your delivery contract.",code:`processed_offset = 211
committed_next = processed_offset + 1
print(f"Processed P1:{processed_offset}")
print(f"Commit P1:{committed_next}")
print(f"Restart resumes at P1:{committed_next}")
# Real commits require the consumer API and correct partition ownership.`,output:"Processed P1:211\nCommit P1:212\nRestart resumes at P1:212",steps:["Fetching 211 does not prove its business effect completed.","After successful processing, commit the next offset 212.","A replacement member starts from durable progress if that offset remains valid."],decision:q("You processed offsets 100 through 103 successfully. What should the next-offset commit be?",["103","104","105"],1,"104 is the next record to process, not the last processed record."),hint:"Commit the next position, not the last completed position.",solution:"Commit 104 for that partition after the corresponding effects are safe. Keep other partitions’ commits separate; on restart, verify retention/reset behavior and deduplication requirements.",interview:[["Position versus committed offset?","The current consumer position advances through fetching; committed progress survives restarts/reassignment. Neither alone proves an external sink transaction committed safely.","Why can fetched progress be ahead of processed progress?"],["What is consumer lag?","An offset-based gap between a partition end position and a consumer/group progress position. Specify which position and measure processing time too; gaps/transactions can make it unlike a simple row count.","Why can lag rise even if the consumer process is alive?"]],mistakes:[["Committing the last processed offset","Restart can reread it.","Commit the next safe offset.","Processed 103; commit 103","Processed through 103; commit 104"],["Committing beyond unfinished asynchronous work","A crash can skip incomplete records.","Track a contiguous safe processing frontier per partition.","Commit 105 while 103 is unfinished","Wait until every earlier required effect is safe"]],quiz:[q("Processed 211, committed 211, then crashed. Where does normal recovery begin?",["211 again","212","Offset 0 in every partition"],0,"211 is still the next durable resume position."),q("Is a consumer commit a deletion request?",["Yes","No","Only for JSON records"],1,"Log cleanup remains separate from group progress.")],doc:"javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html"},
 {id:"replication",title:"Replication & Fault Tolerance",visual:"replicas",idea:"A partition has a Leader and follower replicas on other brokers. Producers write to the leader; followers replicate its log. Eligible in-sync replicas can take over after leader failure.",why:"Replicas protect availability and durability across some broker failures, subject to acknowledgement, replication and election policies.",remember:"Replication factor is the total copy count, including the leader. acks=all waits for all current in-sync replicas; min.insync.replicas constrains write availability. RF=3 does not guarantee survival of every failure.",takeaway:"Reason about copies, in-sync state, acknowledgement and eligible leaders together.",code:`# Properties sketch: producer and topic settings are separate.
producer = {"acks": "all", "enable.idempotence": True}
topic = {"replication.factor": 3, "min.insync.replicas": 2}
in_sync = {1, 2, 3}
in_sync.remove(1)  # broker 1 failed
print(len(in_sync) >= topic["min.insync.replicas"])
# True indicates the count requirement only, not a live write result.`,output:"True",steps:["Start with three in-sync copies of one partition.","After broker 1 fails, two in-sync copies remain in this fixture.","An eligible leader and healthy coordination are still needed before writes can continue."],decision:q("RF=3, min ISR=2, acks=all: only one replica remains in sync. What should you expect?",["Writes should be rejected under this durability requirement","The broker invents two copies","External payments become exactly-once"],0,"The required in-sync count is not met; favoring durability can reduce write availability."),hint:"Copy count configured is not the same as healthy in-sync copies now.",solution:"Keep the durability policy explicit, inspect ISR and broker health, and recover replicas. Do not lower safety settings reflexively without understanding data-loss risk.",interview:[["What happens when a leader broker fails?","The cluster coordinates leadership change to an eligible replica under its election policy. Clients refresh metadata and retry; availability and possible loss depend on which copies survived and what was acknowledged.","Why can an out-of-sync replica be unsafe?"],["Does acks=all mean every configured replica?","It refers to the current in-sync set. min.insync.replicas supplies the minimum in-sync requirement for these writes.","Why combine RF=3 and min ISR=2?"]],mistakes:[["Counting RF=3 as three followers","The leader is included.","Draw one leader plus two followers.","1 leader + 3 followers for RF3","1 leader + 2 followers"],["Assuming any replica can safely take over","A stale copy may lack acknowledged data.","Respect eligible leader policies and ISR health.","Elect any available stale copy without tradeoffs","Recover an eligible replica or accept availability limits"]],quiz:[q("RF=3 normally means how many total copies?",["Three","Four","One per consumer"],0,"The leader counts as one copy."),q("Does an acknowledged write mean a warehouse has processed it?",["Yes","No","Only when all replicas are in sync"],1,"Replication and downstream application processing are different guarantees.")],doc:"design/design/"},
 {id:"delivery-semantics",title:"Ordering & Delivery Semantics",visual:"delivery",idea:"Kafka log order is partition-scoped. Commit-before-process can skip an effect after a crash; process-before-commit can repeat an effect. The application must choose and implement a delivery contract.",why:"An order event may be replayed after a failure even when producer retries were idempotent.",remember:"Idempotent producers address retry duplication in their producer protocol scope, not every business republish. Kafka transactions can coordinate Kafka output and consumed offsets; external side effects need sink cooperation/deduplication. read_committed readers matter for transactional output.",takeaway:"Separate partition order, producer retry guarantees and end-to-end processing effects.",code:`event_id = "evt-1042"
naive_writes = []
safe_writes = {}
for attempt in range(2):  # replay after a crash before commit
    naive_writes.append(event_id)
    safe_writes[event_id] = 499
print(len(naive_writes), len(safe_writes))
# A dictionary illustrates a key, not a distributed transaction.`,output:"2 1",steps:["The same event is processed twice across a simulated restart.","A naive append leaves two effects.","A stable event key can support deduplication, but a real sink needs atomic writes and a clear contract."],decision:q("A payment API succeeded, then your consumer crashed before commit. What is the risk?",["The API cannot be called again","Replay may repeat the payment unless the API honors an idempotency key","Kafka automatically rolls back the external payment"],1,"Consumer offset commits do not atomically cover arbitrary external APIs."),hint:"The API effect and Kafka progress are separate unless deliberately coordinated.",solution:"Use an external idempotency key such as event_id and a transactional/deduplication strategy supported by the destination. Commit only according to the processing contract and monitor failures.",interview:[["At-most-once versus at-least-once?","Committing ahead of effects risks missed effects; committing after effects permits replay when a crash occurs between them. At-least-once processing needs safe repeated effects.","What if the external write succeeds but its response is lost?"],["What does exactly-once mean in Kafka?","Within a correctly configured Kafka read-process-write transaction, output records and input offsets can be coordinated. It does not automatically include an arbitrary database or payment call.","Why is producer idempotence alone insufficient for a sink?"]],mistakes:[["Assuming global topic ordering","Partitions progress independently.","Scope ordering to a partition and business requirements.","P0 events always precede all P1 events","No global order between P0 and P1"],["Equating idempotent production with exactly-once external effects","Consumer replays and business republishing still exist.","Design replay-safe sink effects.","enable.idempotence fixes all duplicates","Use event identity plus atomic sink behavior"]],quiz:[q("Process succeeded; commit did not. After restart, what is possible?",["Duplicate processing","Guaranteed no replay","Record deletion"],0,"The durable resume point may still include the record."),q("Can Kafka transactions automatically roll back an email already sent?",["Yes","No","Only for three partitions"],1,"Arbitrary external effects are outside the Kafka transaction.")],doc:"design/design/"},
 {id:"serialization-schema",title:"Serialization & Schema Evolution",visual:"schema",idea:"A Serializer converts application values to bytes; a deserializer reconstructs values. Kafka stores bytes, so producers and consumers must agree on formats and schema contracts.",why:"A producer update that changes amount from a number to an object can break existing readers, even if Kafka accepts the bytes.",remember:"JSON, Avro and Protobuf have different schema and compatibility rules. Adding a field is not automatically safe for every reader. A Schema Registry is a separate service; Kafka brokers do not enforce arbitrary application schemas by default.",takeaway:"Test new writers against old readers and new readers against retained old records.",code:`import json
old_event = {"order_id": 1042, "amount": 499}
wire = json.dumps(old_event).encode("utf-8")
new_reader = json.loads(wire.decode("utf-8"))
currency = new_reader.get("currency", "INR")
print(new_reader["amount"], currency)
# Default is an explicit business contract in this example.`,output:"499 INR",steps:["Serialize the old event to UTF-8 JSON bytes.","Read it with a consumer that knows an optional currency field.","Apply a documented default; test that the default is correct for historical data."],decision:q("Old records have numeric amount. A new writer sends amount as an object. What is needed?",["Assume Kafka will convert it","Compatibility testing and an explicit migration/version strategy","Only a new broker name"],1,"The broker does not repair incompatible business contracts."),hint:"Can every existing reader parse the new value shape?",solution:"Version or migrate the contract, test representative old/new records and coordinate rollout. Use format-appropriate compatibility checks; do not silently invent currency or amount semantics.",interview:[["Why do schemas matter in Kafka?","They make record meaning and decoding expectations explicit. Retained data and independently deployed consumers make compatibility important across time and versions.","How would you read older records after adding a field?"],["Does JSON remove schema management?","No. Even without an enforced schema language, applications still assume names, types and meaning.","Is changing a field’s meaning safe if its JSON type stays the same?"]],mistakes:[["Changing field types without a migration","Existing readers can fail.","Test version combinations and plan rollout.","amount:499 becomes amount:{value:499}","Versioned contract and reader migration"],["Assuming added fields are always safe","Strict readers and format rules differ.","Test compatibility for the actual serialization system.","All additions are universally compatible","Validate old/new writers and readers"]],quiz:[q("What does Kafka primarily store for a value?",["Application objects with automatic type repair","Serialized bytes","Only JSON tables"],1,"Meaning comes from agreed serializers/deserializers and contracts."),q("A new reader replays old records missing currency. What should happen?",["An explicit valid default/migration or intentional rejection","Invent a random currency","Delete all offsets"],0,"Business meaning must be deliberate, not guessed.")],doc:"streams/developer-guide/datatypes/"},
 {id:"kafka-connect",title:"Kafka Connect",visual:"connect",idea:"Kafka Connect is a framework for reusable integrations. A Source Connector brings external data into Kafka; a Sink Connector writes Kafka data to an external system. Connector tasks perform the work.",why:"Data engineers can configure and operate integrations instead of implementing every poll loop, offset path and conversion layer from scratch.",remember:"Plugins are separately installed and configured. CDC, snapshotting, retry policies and delivery guarantees are connector-specific. A diagram alone does not deploy PostgreSQL-to-warehouse replication.",takeaway:"Source means into Kafka; sink means out of Kafka. Validate each connector’s contract.",code:`# Architecture inventory, NOT a deployable connector config.
pipeline = ["PostgreSQL", "source connector", "orders topic",
            "sink connector", "warehouse"]
print(" -> ".join(pipeline))`,output:"PostgreSQL -> source connector -> orders topic -> sink connector -> warehouse",steps:["Choose a source plugin supporting the required snapshot/change capture.","Define record keys, converters and topic contracts.","Choose a sink plugin with appropriate write/deduplication semantics and monitor task health."],decision:q("You need database changes published into Kafka. Which role is required?",["Source connector","Sink connector only","A consumer group named producer"],0,"From the framework’s Kafka-centered perspective, the database is a source."),hint:"Read direction relative to Kafka.",solution:"Choose a compatible database source/CDC plugin, configure approved credentials outside checked-in code, validate snapshot/change ordering and test the warehouse sink’s replay behavior.",interview:[["Why use Connect?","It standardizes integration deployment and task management while plugins provide system-specific data movement. It reduces custom integration plumbing, not the need for contracts and operations.","What still needs testing when a connector advertises at-least-once?"],["Source versus sink connector?","Source produces external data into Kafka. Sink consumes Kafka records into another system. Tasks execute portions of connector work.","Can every source split work into arbitrarily many tasks?"]],mistakes:[["Assuming every connector includes CDC","Capabilities differ by plugin.","Check snapshot and change capture support.","Any database source captures every delete","Verify deletes, keys and snapshots"],["Assuming delivery guarantees are universal","Sink and source capabilities vary.","Test failures and replay against the actual destination.","Connect means no duplicates ever","Check plugin guarantees and idempotent writes"]],quiz:[q("Kafka → warehouse is which connector direction?",["Source","Sink","Controller"],1,"It writes out of Kafka."),q("Does this lesson’s pipeline inventory create a running connector?",["Yes","No; it is an architecture sketch","Only on Windows"],1,"A real Connect deployment and installed plugin/configuration are required.")],doc:"connect/overview/"},
 {id:"stream-processing",title:"Kafka Streams & Stream Processing",visual:"streams",idea:"A consumer can simply read events; stream processing transforms and combines them continuously. Kafka Streams is a Java library for building processing applications, including stateful operations over Kafka topics.",why:"An orders stream can become sales_by_region through filtering, keying and aggregation rather than a periodic full-table scan.",remember:"Grouping by a new key can require repartitioning. Stateful processing needs recovery/state stores; windows and late events require explicit time semantics. A Python sum here explains the operation, not the Kafka Streams API.",takeaway:"A stream processor has a topology, state and output contracts—not just a read loop.",code:`events = [("IN", 499), ("US", 200), ("IN", -1), ("IN", 101)]
totals = {}
for region, amount in events:
    if amount > 0:
        totals[region] = totals.get(region, 0) + amount
print(totals)
# Finite Python model, not a Kafka Streams application.`,output:"{'IN': 600, 'US': 200}",steps:["Discard the invalid negative amount in this teaching rule.","Group accepted records by region and update totals.","A real continuous topology must define state recovery, changelog/output semantics and late-event policy."],decision:q("Orders are keyed by order_id, but you aggregate by region. What may be necessary?",["Repartition records by region","Assume each worker already has every region’s records","Delete consumer progress"],0,"Related aggregation keys must meet at the appropriate processing task."),hint:"An order key and a region key group different records.",solution:"Re-key by region and account for the repartition topic and state store. Decide whether output is an updated aggregate table/changelog or immutable events, and define window/late-data behavior if required.",interview:[["Kafka versus Kafka Streams?","Kafka provides the event platform. Kafka Streams is a client-side Java processing library used by applications; it is not a separate broker replacement.","Where does your processing application run?"],["Why does aggregation need state?","The result depends on earlier events for the key/window. State must be recoverable and time/late-event semantics explicit.","How should downstream consumers interpret updated totals?"]],mistakes:[["Summing every emitted aggregate update as a new sale","Updates can represent replacement totals.","Define changelog/upsert semantics.","Add total 499 then total 600 as independent sales","Treat the new total as an update for its key"],["Ignoring re-keying costs","Records may need redistribution.","Plan repartitioning and state.","Group by any field with no data movement","Re-key, repartition where needed and maintain state"]],quiz:[q("For IN amounts 499, -1, 101 after filtering positive values, what is the total?",["599","600","499"],1,"Only 499 and 101 contribute."),q("Is the Python example a production Kafka Streams deployment?",["Yes","No; it is a finite learning model","Only with three consumers"],1,"The real library and application lifecycle require a separate environment.")],doc:"streams/"},
 {id:"production-patterns",title:"Reliability & Production Patterns",visual:"production",idea:"Reliable pipelines combine acknowledgements, bounded retries, safe consumer effects and observability. Consumer Lag is one signal; also inspect processing latency, errors, hot partitions and replica health.",why:"A poison record can stall a partition, while committing past it without a policy can silently lose business work.",remember:"Batching and compression trade latency/CPU against throughput. Retention is not a consumer acknowledgement policy. Compaction keeps keyed state eventually, not every historical version forever; tombstones and cleanup timing matter.",takeaway:"Choose durability and recovery policies first, then tune measurable bottlenecks.",code:`log_end = 106  # next offset after the log's final record
committed_next = 104
print("offset lag:", log_end - committed_next)
producer_properties = {"acks": "all", "enable.idempotence": True,
                       "compression.type": "lz4"}
# Configuration sketch, not client construction or a cluster write.`,output:"offset lag: 2",steps:["Distinguish end offset 106 from the last record offset 105.","Compare with committed-next 104 to get an offset gap of 2.","Correlate lag with error rates and processing latency before choosing a tuning change."],decision:q("One invalid record causes endless retries. What is a responsible response?",["Commit beyond it silently","Apply a documented retry/quarantine policy with monitoring and replay","Retry forever without alerts"],1,"Handle the business failure explicitly. Quarantine publication, offset advancement and replay need their own reliability contract."),hint:"Avoid both silent loss and an invisible permanent stall.",solution:"Classify transient versus permanent failures. Bound retries, record diagnostics without secrets, and quarantine where approved. Ensure durable quarantine before advancing progress, and define ownership/replay procedures and ordering implications.",interview:[["What would you monitor?","Per-partition lag and processing latency, error/retry rates, group churn, producer failures and replica/ISR health. Relate each to service objectives.","Can low lag still hide wrong business results?"],["Retention versus compaction?","Time/size retention removes old log segments under policy. Compaction eventually removes superseded keyed values while retaining latest state subject to tombstones and configuration; it is not a complete event-history guarantee.","How would you preserve a separate immutable audit trail?"]],mistakes:[["Treating a dead-letter topic as automatic recovery","Bad records still need accountable handling.","Define quarantine reliability and replay ownership.","Send to DLQ and forget","Alert, diagnose, repair and replay safely"],["Tuning batching without measuring latency","Larger batches can increase waiting and memory costs.","Measure throughput and latency together.","Largest possible batch everywhere","Tune against workload and service objectives"]],quiz:[q("End offset 106 and committed-next 104 imply what offset gap?",["1","2","106"],1,"106 - 104 = 2; this is not always an exact business-row backlog count."),q("Does compaction preserve every historical version forever?",["Yes","No","Only if the key is a string"],1,"Compaction is intended for keyed state rather than immutable full history.")],doc:"configuration/producer-configs/"},
 {id:"architecture-review",title:"Kafka Architecture & Interview Review",visual:"review",idea:"Connect the entire order-event path: producer, key, topic, partition leader, replicas, assigned consumer, business effect and committed next offset. Each boundary has its own contract and failure mode.",why:"An interview architecture answer should explain who owns order, durability, progress and replay—not merely draw boxes.",remember:"Avoid implying that cluster replication makes an external payment exactly-once. Keep partition order, application identity and offset coordinates separate.",takeaway:"Trace one event successfully, then trace the same event through a failure before declaring the design reliable.",code:`design = {
    "topic": "orders", "key": "order_id",
    "partitions": 3, "replication_factor": 3,
    "groups": ["analytics-v1", "fulfillment-v1"],
    "deduplication_key": "event_id",
    "processed": ("orders", 1, 211),
    "committed_next": 212,
}
print(design["groups"])
print(design["processed"], "->", design["committed_next"])
# Design inventory, not executable cluster provisioning.`,output:"['analytics-v1', 'fulfillment-v1']\n('orders', 1, 211) -> 212",steps:["Use an order key for stable same-topic routing; use event_id for replay identity.","Separate application groups and replicas from consumer parallelism.","Explain a crash after an external effect but before commit, including replay-safe recovery."],decision:q("Analytics and fulfillment each need every order. What design fits?",["One group with one analytics member and one fulfillment member","Two independent groups with explicit effect/replay contracts","Delete each order after the first read"],1,"Each group needs independent progress and the complete stream."),hint:"Sharing a group means sharing work, not broadcasting every record to every member.",solution:"Use an orders topic keyed by order_id, independent analytics and fulfillment groups, tested producer durability and replay-safe sink effects keyed by event_id. Monitor lag, errors, group churn and replica health; define retention and schema evolution.",interview:[["Design an order-event pipeline.","Start with event IDs and schemas, define keys/topics/retention, size partitions and replication, choose producer durability, and give each independent application a group. Explain commits, replay-safe effects, poison-event policy and observability.","What changes if strict global order is required?"],["Walk through a consumer failure after a warehouse write.","If the next-offset commit did not persist, the record can replay under a new owner. A stable event key and atomic idempotent sink write avoid repeated business effects; offset handling alone is insufficient.","What if the sink write succeeded but the consumer saw a timeout?"]],mistakes:[["A diagram with no failure contracts","Happy-path boxes hide loss and duplication.","Trace failure at each boundary.","Producer → Kafka → database, done","Explain acknowledgement, processing, commit and replay"],["Using one key for different meanings","Log position and business identity are not interchangeable.","Name each identity explicitly.","offset means order_id","event_id, order_id and topic/partition/offset have different roles"]],quiz:[q("A producer retry is idempotent. Can a consumer still repeat a sink write after restart?",["Yes","No","Only with JSON"],0,"These are distinct failure boundaries."),q("What proves the design is understood?",["Naming as many configs as possible","Explaining one event’s routing, durability, processing and recovery","Assuming no failures"],1,"Clear causal reasoning is more useful than memorized labels.")],doc:"design/design/"},
];
export const kafkaLessons:KafkaLesson[]=specs.map(s=>({id:s.id,title:s.title,description:s.takeaway,minutes:s.id==="introduction"?15:25,concepts:[["What is it?",s.idea],["Why it matters",s.why],["Remember",s.remember]],flow:s.steps,example:{code:s.code,output:s.output,walkthrough:s.steps},practice:{task:s.decision.question,hint:s.hint,solution:s.solution,output:s.decision.explanation},interview:s.interview.map(([question,answer,followup])=>({question,answer,followup})),mistakes:s.mistakes.map(([title,why,better,before,after])=>({title,why,better,before,after})),quiz:s.quiz,visual:s.visual,takeaway:s.takeaway,decision:s.decision,setup:s.setup??pythonSetup,codeTitle:s.codeTitle??"Python · deterministic learning model",resource:"https://kafka.apache.org/41/"+s.doc}));
export const kafkaById=Object.fromEntries(kafkaLessons.map(l=>[l.id,l]));
