export type PythonStory = {
  definition: string; vocabulary: string; plain: string; question: string;
  answer: string; recall: string; input: string[]; output: string[];
  station: string; code: string; result: string; pitfall: string; color: string;
};

export const pythonStories: Record<string, PythonStory> = {
  'py-introduction': {
    definition: 'Python is a general-purpose language used to connect systems and transform data.',
    vocabulary: 'Variable: a name referring to a value. Type: the kind of value.',
    plain: 'Read raw amounts, convert the text, then add the numbers.',
    question: 'When would you choose Python over SQL?',
    answer: 'Use Python for APIs, files and custom control flow. Use SQL for set-based transformations in a database. Here Python converts two text amounts and totals them.',
    recall: 'Explain why “100” must become 100 before adding.',
    input: ['"100"', '"50"'], output: ['100', '50'], station: 'int → sum',
    code: 'raw = ["100", "50"]\namounts = [int(x) for x in raw]\nprint(sum(amounts))', result: '150',
    pitfall: 'CSV fields arrive as strings; convert and validate explicitly.', color: '#4f46e5',
  },
  'py-data-structures': {
    definition: 'Data structures organize values so you can store, find and process records.',
    vocabulary: 'List: ordered items. Dict: key/value pairs. Set: unique items. Tuple: immutable sequence.',
    plain: 'A list holds records; a dictionary lets you find one by its key.',
    question: 'Why choose a dictionary for record lookup?',
    answer: 'A dictionary maps a key to a value with average constant-time lookup. A list usually needs a scan. Duplicate keys overwrite earlier values, so confirm uniqueness first.',
    recall: 'Compare a list of records with a dictionary keyed by ID.',
    input: ['ID 1 → 100', 'ID 2 → 50'], output: ['1: 100', '2: 50'], station: 'Index by ID',
    code: 'rows = [(1, 100), (2, 50)]\nby_id = dict(rows)\nprint(by_id[2])', result: '50',
    pitfall: 'Tuple immutability does not make nested mutable objects immutable.', color: '#0891b2',
  },
  'py-functions-modules': {
    definition: 'A function is a named, reusable block of code. A module is an importable file of Python code.',
    vocabulary: 'Parameter: named input. Return: value sent back to the caller.',
    plain: 'Build one cleaning station and send different values through it.',
    question: 'Why avoid a mutable default argument?',
    answer: 'Defaults are evaluated once when the function is defined. A default list can retain changes across calls. Use None and create a fresh list inside the function instead.',
    recall: 'Explain inputs, return values and reuse with clean().',
    input: ['"100"', '"50"'], output: ['100', '50'], station: 'clean(raw)',
    code: 'def clean(raw):\n    return int(raw)\nprint([clean(x) for x in ["100", "50"]])', result: '[100, 50]',
    pitfall: 'Keep reusable transforms separate from script entry-point logic.', color: '#7c3aed',
  },
  'py-files-formats': {
    definition: 'Parsing converts file text into Python values that a pipeline can process.',
    vocabulary: 'CSV: delimited fields. JSON: structured values. Parquet: typed columnar storage.',
    plain: 'A JSON file contains text; parsing creates a usable dictionary.',
    question: 'Why use with when opening a file?',
    answer: 'A with block closes the file on normal exit or when an exception occurs. It manages the resource; it does not validate the contents. Parse and check the records separately.',
    recall: 'Describe the journey from file text to a typed amount.',
    input: ['JSON text', '{"amount": 100}'], output: ['Python dict', 'amount → 100'], station: 'json.loads',
    code: 'import json\ntext = \'{"amount": 100}\'\nrow = json.loads(text)\nprint(row["amount"])', result: '100',
    pitfall: 'For a real file use with open(path, encoding="utf-8"); large files need streaming.', color: '#b45309',
  },
  'py-error-handling': {
    definition: 'An exception signals a failure. Handling it selects an explicit recovery path.',
    vocabulary: 'try: attempt work. except: handle a named error. Logging: record events.',
    plain: 'Valid amounts take the main path; invalid text takes the recovery path.',
    question: 'Why catch ValueError specifically?',
    answer: 'int("bad") raises ValueError. Catching that expected failure lets us mark the value missing while other bugs still surface. Log or count rejected values so recovery stays visible.',
    recall: 'Explain why an invalid amount is missing rather than zero.',
    input: ['"100"', '"bad"'], output: ['100 · valid', 'None · rejected'], station: 'try / except',
    code: 'def parse(x):\n    try: return int(x)\n    except ValueError: return None\nprint([parse("100"), parse("bad")])', result: '[100, None]',
    pitfall: 'int(None) raises TypeError; handle it if missing values are allowed.', color: '#be185d',
  },
  'py-pandas-basics': {
    definition: 'A pandas DataFrame is a labeled table for working with rows and columns in memory.',
    vocabulary: 'Vectorized operation: apply an operation to a whole column or array.',
    plain: 'Select the amount column and total it without a Python row loop.',
    question: 'Why prefer column operations to iterrows()?',
    answer: 'Column operations express the transformation directly and often use optimized array code. iterrows() builds a Series for each row and may change types. Check memory use for large datasets.',
    recall: 'Describe what one DataFrame row and column represent.',
    input: ['amount: 100', 'amount: 50'], output: ['amount column', 'total: 150'], station: 'Column sum',
    code: 'import pandas as pd\ndf = pd.DataFrame({"amount": [100, 50]})\nprint(int(df["amount"].sum()))', result: '150',
    pitfall: 'pandas is an extra dependency; data and intermediate results must fit in memory.', color: '#047857',
  },
  'py-hands-on-task': {
    definition: 'An ETL pipeline extracts data, transforms it and loads a useful result.',
    vocabulary: 'Deduplication: remove repeated records using a defined business key.',
    plain: 'Remove duplicate orders before totaling; otherwise the amount is counted twice.',
    question: 'Why deduplicate before aggregating?',
    answer: 'Aggregation loses individual record identity. If duplicates enter a sum, they inflate it and cannot reliably be removed afterward. Define the key and a conflict policy before grouping.',
    recall: 'Explain why these three records total 150, not 250.',
    input: ['(1, 100)', '(1, 100)', '(2, 50)'], output: ['1 → 100', '2 → 50'], station: 'Deduplicate',
    code: 'rows = [(1, 100), (1, 100), (2, 50)]\nunique = dict(rows)\nprint(sum(unique.values()))', result: '150',
    pitfall: 'Here duplicates agree. dict keeps the last value when duplicate IDs conflict.', color: '#0e7490',
  },
  'py-interview-questions': {
    definition: 'A useful interview answer connects a decision to its mechanism, example and trade-off.',
    vocabulary: 'Lazy evaluation: compute values as they are requested.',
    plain: 'A generator yields amounts one at a time instead of building a result list.',
    question: 'How does a generator help a large pipeline?',
    answer: 'A generator yields values on demand without building an output list. It is consumed once. To save memory across a pipeline, stream the source too; this example starts with a small list.',
    recall: 'Define a generator, give a use case and name one limitation.',
    input: ['100', '50'], output: ['yield 100', 'yield 50'], station: 'Demand → yield',
    code: 'def amounts():\n    yield from [100, 50]\nprint(sum(amounts()))', result: '150',
    pitfall: 'A consumed generator cannot be replayed; create a new one if needed.', color: '#6d28d9',
  },
  'py-quiz': {
    definition: 'A loop processes items from an iterable. range describes a sequence of integers.',
    vocabulary: 'Iterable: supplies items. Exclusive stop: the endpoint is not included.',
    plain: 'range(3) supplies 0, 1 and 2; the loop visits each value once.',
    question: 'What does range(3) produce, and why?',
    answer: 'It represents 0, 1 and 2. The default start is zero and the stop is excluded. This is useful for indexing three records; using 3 as an index would exceed their bounds.',
    recall: 'Predict range(1, 4) and explain the endpoint.',
    input: ['range(3)'], output: ['0', '1', '2'], station: 'for each i',
    code: 'seen = []\nfor i in range(3):\n    seen.append(i)\nprint(seen)', result: '[0, 1, 2]',
    pitfall: 'Predict first, then explain your reasoning; a correct guess is not recall.', color: '#c2410c',
  },
  'py-summary': {
    definition: 'Validation checks that pipeline results satisfy explicit rules before they are used.',
    vocabulary: 'Invariant: a condition that must remain true. Assertion: a debugging check.',
    plain: 'Check small, known inputs before scaling a transformation to more records.',
    question: 'How would you verify a cleaning pipeline?',
    answer: 'Use known inputs and expected results. Check types, rejected records, duplicate keys and totals. Include edge cases such as missing amounts. Monitor those checks after deployment as well.',
    recall: 'Name three checks you would apply before loading data.',
    input: ['100', '50'], output: ['2 valid records', 'total: 150'], station: 'Check → load',
    code: 'amounts = [100, 50]\nassert all(x >= 0 for x in amounts)\nassert sum(amounts) == 150\nprint("validated")', result: 'validated',
    pitfall: 'assert can be disabled with -O; use explicit checks for production validation.', color: '#0369a1',
  },
};
