import type { SparkLesson } from "@/lib/spark-lessons";

export const sqlSchema = `CREATE TABLE customers (
  id INTEGER PRIMARY KEY, name TEXT NOT NULL, city TEXT, age INTEGER
);
CREATE TABLE orders (
  id INTEGER PRIMARY KEY, customer_id INTEGER REFERENCES customers(id), amount INTEGER
);
INSERT INTO customers VALUES
  (1, 'Alice', 'Chennai', 31), (2, 'Bob', 'Mumbai', 22),
  (3, 'Carol', 'Chennai', 29), (4, 'Dan', NULL, 19);
INSERT INTO orders VALUES (101, 1, 500), (102, 1, 300), (103, 3, 200);`;
export type SqlTable = { title:string; columns:string[]; rows:(string|number|null)[][] };
export const customerTable:SqlTable={title:"customers",columns:["id","name","city","age"],rows:[[1,"Alice","Chennai",31],[2,"Bob","Mumbai",22],[3,"Carol","Chennai",29],[4,"Dan",null,19]]};
export const orderTable:SqlTable={title:"orders",columns:["id","customer_id","amount"],rows:[[101,1,500],[102,1,300],[103,3,200]]};
type Spec={id:string;title:string;idea:string;why:string;query:string;columns:string[];rows:SqlTable["rows"];task:string;solution:string;expected:string;question:string;answer:string;mistake:string;bad:string;fix:string;quiz:[string,string[],number,string];tables?:SqlTable[]};
const specs:Spec[]=[
{id:"introduction",title:"SQL Introduction",idea:"A table stores rows with named columns. SQL describes the data you want, not a loop over every record.",why:"A Primary Key identifies one row. A Foreign Key connects an order to a customer; it does not guarantee one order per customer.",query:"SELECT id, name FROM customers ORDER BY id;",columns:["id","name"],rows:[[1,"Alice"],[2,"Bob"],[3,"Carol"],[4,"Dan"]],task:"List the order IDs and their customer IDs.",solution:"SELECT id, customer_id FROM orders ORDER BY id;",expected:"101 | 1\n102 | 1\n103 | 3",question:"Why does an order need its own primary key?",answer:"A customer can place several orders. The order ID identifies one order; customer_id links it to a customer.",mistake:"Assuming a foreign key is unique",bad:"-- Wrong assumption: customer_id identifies one order",fix:"SELECT customer_id, COUNT(*) FROM orders GROUP BY customer_id;",quiz:["How many orders belong to Alice?",["1","2","3"],1,"Orders 101 and 102 both refer to customer 1."]},
{id:"select",title:"SELECT",idea:"SELECT chooses columns or expressions. It does not remove duplicate rows automatically.",why:"Name the columns you need so your output remains predictable when the table changes.",query:"SELECT name, city FROM customers ORDER BY id;",columns:["name","city"],rows:[["Alice","Chennai"],["Bob","Mumbai"],["Carol","Chennai"],["Dan",null]],task:"Return each name and age, using years as the age column alias.",solution:"SELECT name, age AS years FROM customers ORDER BY id;",expected:"Alice | 31\nBob | 22\nCarol | 29\nDan | 19",question:"Why avoid SELECT * in a data pipeline?",answer:"It couples the output to every source column. New or reordered columns can break consumers; explicit columns document the intended contract.",mistake:"Using single quotes for a column reference",bad:"SELECT 'name' FROM customers;",fix:"SELECT name FROM customers;",quiz:["SELECT 'name' returns…",["Customer names","The literal text name","An empty table"],1,"Single quotes denote a string value, not a column name."]},
{id:"where",title:"WHERE / Filtering",idea:"WHERE keeps rows whose condition is true. Rows with false or unknown conditions are excluded.",why:"Parentheses make combinations of AND and OR unambiguous.",query:"SELECT name, age FROM customers WHERE age > 25 ORDER BY id;",columns:["name","age"],rows:[["Alice",31],["Carol",29]],task:"Return customers aged 20 through 30 inclusive.",solution:"SELECT name, age FROM customers WHERE age BETWEEN 20 AND 30 ORDER BY id;",expected:"Bob | 22\nCarol | 29",question:"How do AND and OR differ?",answer:"AND requires both conditions to be true; OR requires at least one. AND has higher precedence, so use parentheses for the intended grouping.",mistake:"Forgetting parentheses around alternatives",bad:"SELECT name FROM customers WHERE city = 'Chennai' OR city = 'Mumbai' AND age > 25;",fix:"SELECT name FROM customers WHERE (city = 'Chennai' OR city = 'Mumbai') AND age > 25 ORDER BY id;",quiz:["Which names pass age > 25?",["Alice and Carol","Bob and Dan","All four"],0,"31 and 29 are greater than 25."]},
{id:"order-by",title:"ORDER BY",idea:"ORDER BY sorts returned rows. Without it, result order is not guaranteed.",why:"Use a unique tie-breaker for stable results when sort values match.",query:"SELECT name, age FROM customers ORDER BY age DESC, id;",columns:["name","age"],rows:[["Alice",31],["Carol",29],["Bob",22],["Dan",19]],task:"Sort customers by age from youngest to oldest.",solution:"SELECT name, age FROM customers ORDER BY age ASC, id;",expected:"Dan | 19\nBob | 22\nCarol | 29\nAlice | 31",question:"Why add id after a sort column?",answer:"It determines the order of ties and makes pagination or top-N selection reproducible.",mistake:"Relying on insertion order",bad:"SELECT name FROM customers;",fix:"SELECT name FROM customers ORDER BY id;",quiz:["DESC means…",["Smallest first","Largest first","Remove duplicates"],1,"Descending order puts larger values first."]},
{id:"distinct",title:"DISTINCT",idea:"DISTINCT removes duplicate combinations of the selected columns, not duplicates of one arbitrary column.",why:"Two customers can share a city while still being different people.",query:"SELECT DISTINCT city FROM customers WHERE city IS NOT NULL ORDER BY city;",columns:["city"],rows:[["Chennai"],["Mumbai"]],task:"Count distinct known cities.",solution:"SELECT COUNT(DISTINCT city) AS city_count FROM customers;",expected:"2",question:"Does DISTINCT city, name return one row per city?",answer:"No. It removes duplicate city/name pairs. Different names in the same city remain separate rows.",mistake:"Using DISTINCT to hide a broken join",bad:"SELECT DISTINCT c.name FROM customers c JOIN orders o ON 1 = 1;",fix:"SELECT DISTINCT c.name FROM customers c JOIN orders o ON c.id = o.customer_id ORDER BY c.name;",quiz:["How many distinct non-null cities exist?",["4","3","2"],2,"Chennai occurs twice; Mumbai once; NULL is excluded here."]},
{id:"limit",title:"LIMIT / Top N",idea:"LIMIT returns at most a chosen number of rows. Pair it with ORDER BY to define which rows you want.",why:"This module uses PostgreSQL-style LIMIT. SQL Server uses TOP or OFFSET/FETCH instead.",query:"SELECT name, age FROM customers ORDER BY age DESC, id LIMIT 2;",columns:["name","age"],rows:[["Alice",31],["Carol",29]],task:"Return the youngest customer.",solution:"SELECT name, age FROM customers ORDER BY age, id LIMIT 1;",expected:"Dan | 19",question:"Does LIMIT 1 mean the first inserted row?",answer:"No. Without ORDER BY there is no defined first row. Specify the sort and a tie-breaker.",mistake:"Requesting top rows without sorting",bad:"SELECT name, age FROM customers LIMIT 2;",fix:"SELECT name, age FROM customers ORDER BY age DESC, id LIMIT 2;",quiz:["Who are the two oldest?",["Alice and Carol","Bob and Dan","Alice and Bob"],0,"Sort ages descending before taking two rows."]},
{id:"aggregates",title:"Aggregate Functions",idea:"An Aggregate summarizes rows: COUNT counts, SUM adds, AVG averages, and MIN/MAX find extremes.",why:"COUNT(*) counts all rows; COUNT(column) counts only non-null values. SUM ignores null inputs.",query:"SELECT COUNT(*) AS orders, SUM(amount) AS total, MIN(amount) AS smallest, MAX(amount) AS largest FROM orders;",columns:["orders","total","smallest","largest"],rows:[[3,1000,200,500]],task:"Count customers and customers with a known city.",solution:"SELECT COUNT(*) AS customers, COUNT(city) AS known_city FROM customers;",expected:"4 | 3",question:"What is the difference between COUNT(*) and COUNT(city)?",answer:"COUNT(*) includes every input row. COUNT(city) skips null city values, giving 4 versus 3 here.",mistake:"Treating SUM over no rows as zero",bad:"SELECT SUM(amount) FROM orders WHERE amount > 1000;",fix:"SELECT COALESCE(SUM(amount), 0) FROM orders WHERE amount > 1000;",quiz:["What is COUNT(city) over customers?",["4","3","2"],1,"Dan has a null city, so only three values are counted."],tables:[orderTable]},
{id:"group-by",title:"GROUP BY",idea:"GROUP BY creates one group for each distinct key, then aggregates within each group.",why:"The selected non-aggregate columns should define the group. A total per customer is a different grain from a total per order.",query:"SELECT customer_id, SUM(amount) AS total FROM orders GROUP BY customer_id ORDER BY customer_id;",columns:["customer_id","total"],rows:[[1,800],[3,200]],task:"Count orders per customer.",solution:"SELECT customer_id, COUNT(*) AS order_count FROM orders GROUP BY customer_id ORDER BY customer_id;",expected:"1 | 2\n3 | 1",question:"Why does GROUP BY reduce row count?",answer:"It returns one summary row per group instead of one row per source record. Three orders become two customer groups.",mistake:"Selecting an ungrouped order ID",bad:"SELECT id, customer_id, SUM(amount) FROM orders GROUP BY customer_id;",fix:"SELECT customer_id, SUM(amount) FROM orders GROUP BY customer_id;",quiz:["Customer 1 has a total of…",["500","300","800"],2,"500 + 300 = 800."],tables:[orderTable]},
{id:"having",title:"HAVING",idea:"WHERE filters input rows. HAVING filters groups after aggregation.",why:"Filtering orders before summing can change group totals. State the business rule before choosing the clause.",query:"SELECT customer_id, SUM(amount) AS total FROM orders GROUP BY customer_id HAVING SUM(amount) > 500 ORDER BY customer_id;",columns:["customer_id","total"],rows:[[1,800]],task:"Find customers who have more than one order.",solution:"SELECT customer_id, COUNT(*) AS order_count FROM orders GROUP BY customer_id HAVING COUNT(*) > 1 ORDER BY customer_id;",expected:"1 | 2",question:"WHERE versus HAVING?",answer:"WHERE chooses input records; HAVING chooses aggregated groups. Use WHERE amount > 500 for individual orders and HAVING SUM(amount) > 500 for customer totals.",mistake:"Using aggregate results in WHERE",bad:"SELECT customer_id, SUM(amount) FROM orders WHERE SUM(amount) > 500 GROUP BY customer_id;",fix:"SELECT customer_id, SUM(amount) FROM orders GROUP BY customer_id HAVING SUM(amount) > 500;",quiz:["Which clause filters SUM(amount)?",["WHERE","HAVING","LIMIT"],1,"HAVING evaluates grouped totals."],tables:[orderTable]},
{id:"joins",title:"JOINs",idea:"JOIN matches rows from two tables using a condition. Alice has two orders, so she appears twice in an INNER JOIN result.",why:"INNER JOIN drops unmatched customers. LEFT JOIN keeps them, with null values for missing order columns.",query:"SELECT c.name, o.amount FROM customers c INNER JOIN orders o ON c.id = o.customer_id ORDER BY c.id, o.id;",columns:["name","amount"],rows:[["Alice",500],["Alice",300],["Carol",200]],task:"Keep every customer, including those with no orders.",solution:"SELECT c.name, o.amount FROM customers c LEFT JOIN orders o ON c.id = o.customer_id ORDER BY c.id, o.id;",expected:"Alice | 500\nAlice | 300\nBob | NULL\nCarol | 200\nDan | NULL",question:"Why can a join return more rows than the left table?",answer:"Each matching pair is returned. One customer with multiple orders creates multiple joined rows. Check key uniqueness and the expected grain.",mistake:"Filtering away unmatched LEFT JOIN rows",bad:"SELECT c.name, o.amount FROM customers c LEFT JOIN orders o ON c.id = o.customer_id WHERE o.amount > 300;",fix:"SELECT c.name, o.amount FROM customers c LEFT JOIN orders o ON c.id = o.customer_id AND o.amount > 300 ORDER BY c.id, o.id;",quiz:["Which customers have no matching order?",["Alice and Carol","Bob and Dan","Only Bob"],1,"No orders reference customer IDs 2 or 4."],tables:[customerTable,orderTable]},
{id:"subqueries-ctes",title:"Subqueries & CTEs",idea:"A subquery is a query inside another. A CTE gives an intermediate query a name using WITH.",why:"A CTE improves readability; it is not inherently a saved table or a guarantee of faster execution.",query:"WITH totals AS (SELECT customer_id, SUM(amount) AS total FROM orders GROUP BY customer_id) SELECT customer_id, total FROM totals WHERE total > 500 ORDER BY customer_id;",columns:["customer_id","total"],rows:[[1,800]],task:"Use a subquery to find orders larger than the average order amount.",solution:"SELECT id, amount FROM orders WHERE amount > (SELECT AVG(amount) FROM orders) ORDER BY id;",expected:"101 | 500",question:"When would you use a CTE?",answer:"To name and explain an intermediate result or separate query steps. The optimizer decides how to execute it; do not assume it is cached.",mistake:"Assuming a scalar subquery returns one row",bad:"SELECT id FROM orders WHERE amount > (SELECT amount FROM orders);",fix:"SELECT id FROM orders WHERE amount > (SELECT AVG(amount) FROM orders);",quiz:["A CTE is always…",["A permanent table","A query-scoped named expression","A performance improvement"],1,"WITH names a query expression for this statement."],tables:[orderTable]},
{id:"window-functions",title:"Window Functions",idea:"A Window Function adds a calculation without collapsing the original rows. OVER defines which related rows it considers.",why:"PARTITION BY customer_id computes a separate total for each customer while keeping each order visible.",query:"SELECT id, customer_id, amount, SUM(amount) OVER (PARTITION BY customer_id) AS customer_total FROM orders ORDER BY id;",columns:["id","customer_id","amount","customer_total"],rows:[[101,1,500,800],[102,1,300,800],[103,3,200,200]],task:"Rank each customer’s orders by amount using ROW_NUMBER, breaking ties with id.",solution:"SELECT id, customer_id, ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY amount DESC, id) AS rn FROM orders ORDER BY id;",expected:"101 | 1 | 1\n102 | 1 | 2\n103 | 3 | 1",question:"Window functions versus GROUP BY?",answer:"GROUP BY collapses rows into summaries. Window functions retain rows and attach calculations. Window ORDER BY controls calculation order; outer ORDER BY controls display.",mistake:"Filtering a window alias in the same WHERE",bad:"SELECT id, ROW_NUMBER() OVER (ORDER BY amount DESC) AS rn FROM orders WHERE rn = 1;",fix:"WITH ranked AS (SELECT id, ROW_NUMBER() OVER (ORDER BY amount DESC, id) AS rn FROM orders) SELECT id FROM ranked WHERE rn = 1;",quiz:["How many rows remain after the example window SUM?",["1","2","3"],2,"All three orders remain; the total is an added column."],tables:[orderTable]},
{id:"null-case",title:"NULL & CASE WHEN",idea:"NULL means missing or unknown, not zero or empty text. Use IS NULL to test it.",why:"CASE WHEN maps conditions to values. COALESCE returns the first non-null value; choose defaults only when they fit the business rule.",query:"SELECT name, CASE WHEN city IS NULL THEN 'Unknown' ELSE city END AS city_label FROM customers ORDER BY id;",columns:["name","city_label"],rows:[["Alice","Chennai"],["Bob","Mumbai"],["Carol","Chennai"],["Dan","Unknown"]],task:"Label customers age 25 or older as Adult segment; label the others Young segment.",solution:"SELECT name, CASE WHEN age >= 25 THEN 'Adult segment' ELSE 'Young segment' END AS segment FROM customers ORDER BY id;",expected:"Alice | Adult segment\nBob | Young segment\nCarol | Adult segment\nDan | Young segment",question:"Why does city = NULL not find Dan?",answer:"Equality with NULL produces unknown. WHERE keeps only true conditions, so use city IS NULL.",mistake:"Comparing NULL with equality",bad:"SELECT name FROM customers WHERE city = NULL;",fix:"SELECT name FROM customers WHERE city IS NULL;",quiz:["Which expression finds unknown cities?",["city = NULL","city IS NULL","city = ''"],1,"IS NULL explicitly tests missing values."]},
{id:"query-execution",title:"Query Execution & Review",idea:"Understand logical processing: FROM/JOIN → WHERE → GROUP BY → HAVING → SELECT → ORDER BY → LIMIT.",why:"This is a reasoning model, not the physical runtime schedule. The optimizer may choose another execution strategy while preserving query meaning.",query:"SELECT customer_id, SUM(amount) AS total FROM orders WHERE amount > 200 GROUP BY customer_id HAVING SUM(amount) > 500 ORDER BY total DESC, customer_id LIMIT 1;",columns:["customer_id","total"],rows:[[1,800]],task:"Combine LEFT JOIN, GROUP BY and COUNT to count orders for every customer, including zero.",solution:"SELECT c.id, c.name, COUNT(o.id) AS order_count FROM customers c LEFT JOIN orders o ON c.id = o.customer_id GROUP BY c.id, c.name ORDER BY c.id;",expected:"1 | Alice | 2\n2 | Bob | 0\n3 | Carol | 1\n4 | Dan | 0",question:"Why use COUNT(o.id), not COUNT(*), after LEFT JOIN?",answer:"Unmatched customers still produce one joined row. COUNT(*) counts that row; COUNT(o.id) skips the null order ID and gives zero.",mistake:"Counting an unmatched join row as an order",bad:"SELECT c.id, COUNT(*) FROM customers c LEFT JOIN orders o ON c.id = o.customer_id GROUP BY c.id;",fix:"SELECT c.id, COUNT(o.id) FROM customers c LEFT JOIN orders o ON c.id = o.customer_id GROUP BY c.id;",quiz:["Does logical SQL order dictate the physical execution plan?",["Yes, always","No, the optimizer chooses a valid plan","Only for SELECT *"],1,"Logical order explains meaning; physical operators may differ."],tables:[customerTable,orderTable]},
];

export const sqlVisuals=Object.fromEntries(specs.map(s=>[s.id,{inputs:s.tables??[customerTable],result:{title:"Expected result",columns:s.columns,rows:s.rows} satisfies SqlTable}]));
const guidance:Record<string,[string,string,string]>={
  introduction:["Select id and customer_id from orders, then sort by id.","One customer can own many orders, so customer_id repeats.","Use the order id as the order’s identity; inspect relationship cardinality."],
  select:["Use AS to rename age in the output.","Single quotes produce a constant string for every row.","Use the unquoted column identifier name to return stored names."],
  where:["BETWEEN includes both endpoints; alternatively combine >= and <= with AND.","AND binds more tightly than OR, so the age test applies only to the second branch.","Group the city alternatives in parentheses before applying the age condition."],
  "order-by":["Use ASC and add id as a tie-breaker.","Storage or insertion order is not a query ordering guarantee.","Specify ORDER BY whenever output order matters."],
  distinct:["COUNT(DISTINCT city) counts unique non-null values.","DISTINCT can conceal duplicated rows while leaving an incorrect relationship.","Fix the join condition before deciding whether de-duplication is required."],
  limit:["Sort age ascending before applying LIMIT 1.","Without ORDER BY, any qualifying rows may be returned.","Define both the desired order and a stable tie-breaker."],
  aggregates:["Compare COUNT(*) with COUNT(city) in one SELECT.","SUM returns NULL when there are no non-null input values.","Use COALESCE only if zero is the intended meaning of an empty total."],
  "group-by":["Use COUNT(*) for each customer_id group.","An arbitrary order id has no single value for a multi-order group.","Select the grouping key and the aggregate, not an ungrouped order id."],
  having:["Group by customer_id, then keep groups with COUNT(*) > 1.","WHERE cannot test a grouped aggregate at this logical stage.","Use HAVING for conditions on grouped results."],
  joins:["Start with customers, use LEFT JOIN, and match id to customer_id.","WHERE on right-side columns rejects null-extended rows after the join.","Put the right-side match restriction in ON when unmatched left rows must remain."],
  "subqueries-ctes":["Use a scalar subquery containing AVG(amount).","A scalar comparison needs one value, not the three amounts returned by this subquery.","Aggregate inside the subquery to produce one comparison value."],
  "window-functions":["Use ROW_NUMBER() OVER with PARTITION BY customer_id and ORDER BY amount DESC, id.","WHERE is evaluated before the SELECT window result exists.","Compute the window column in a CTE, then filter it in the outer query."],
  "null-case":["Use CASE WHEN age >= 25 THEN ... ELSE ... END.","Comparing with NULL produces unknown, which WHERE does not retain.","Use IS NULL or IS NOT NULL for missing-value tests."],
  "query-execution":["LEFT JOIN customers to orders, then COUNT(o.id) per customer.","An unmatched LEFT JOIN row still exists, so COUNT(*) returns one instead of zero.","Count a non-null order key to count actual matches."],
};
export const sqlLessons:SparkLesson[]=specs.map(s=>({
  id:s.id,title:s.title,minutes:s.id==="joins"||s.id==="window-functions"?25:15,description:s.idea,
  concepts:[["In plain English",s.idea],["Why it matters",s.why]],flow:[],
  example:{code:s.query,output:[s.columns.join(" | "),...s.rows.map(row=>row.map(v=>v===null?"NULL":v).join(" | "))].join("\n"),walkthrough:["Inspect the input tables and predict the output.",s.idea,"Compare the expected result with your prediction. "+s.why]},
  practice:{task:s.task,hint:guidance[s.id][0],solution:s.solution,output:s.expected},
  interview:[{question:s.question,answer:s.answer,followup:"Explain your answer using this lesson’s input rows and query."}],
  mistakes:[{title:s.mistake,why:guidance[s.id][1],better:guidance[s.id][2],before:s.bad,after:s.fix}],
  quiz:[{question:s.quiz[0],options:s.quiz[1],correct:s.quiz[2],explanation:s.quiz[3]}],
}));

// The final lesson reviews the module without creating duplicate topic lessons.
sqlLessons[sqlLessons.length-1].quiz=sqlLessons.flatMap(lesson=>lesson.quiz);
sqlLessons[sqlLessons.length-1].interview=[
  ...sqlLessons.filter(lesson=>["having","joins","window-functions","null-case"].includes(lesson.id)).flatMap(lesson=>lesson.interview),
  ...sqlLessons[sqlLessons.length-1].interview,
];
