export interface SqlConceptGuide {
  question:string; definition?:string; model:string[]; syntax?:string;
  parts:[string,string][]; remember:string; takeaway:string; difficulty:"Beginner"|"Intermediate";
  related?:[string,string];
}
export const sqlConceptGuides:Record<string,SqlConceptGuide>={
  introduction:{question:"What information is stored, and how do I ask for it?",model:["Table rows","SQL request","Result rows"],parts:[["SELECT id, name","Columns to return"],["FROM customers","The source table"],["ORDER BY id","Display rows in ID order"]],remember:"A table’s row order is not guaranteed. A primary key identifies a row; it does not sort your result.",takeaway:"SQL describes a result using tables, columns and conditions.",difficulty:"Beginner"},
  select:{question:"Which information do I want to see?",definition:"SELECT specifies which columns or expressions appear in a query result.",syntax:"SELECT name, city\nFROM customers;",model:["customers table","SELECT columns","Result"],parts:[["SELECT","What you want returned"],["name, city","Columns being selected"],["FROM","Where the data comes from"],["customers","Source table"]],remember:"SELECT does not remove duplicates. SELECT city may repeat values; SELECT DISTINCT city returns unique values.",takeaway:"SELECT controls which columns or expressions appear in the result. FROM identifies where that data comes from.",difficulty:"Beginner",related:["distinct","Learn DISTINCT"]},
  where:{question:"Which rows match my rule?",model:["All rows","Test age > 25","Matching rows"],parts:[["WHERE age > 25","Keep only rows where the test is true"],["SELECT name, age","Return these columns from matching rows"]],remember:"WHERE excludes false and unknown conditions. Use IS NULL—not = NULL—to find missing values.",takeaway:"WHERE chooses rows; SELECT chooses the columns you see.",difficulty:"Beginner",related:["null-case","Learn NULL handling"]},
  "order-by":{question:"In which order should the results appear?",model:["Result rows","Sort by age DESC, id","Ordered rows"],parts:[["ORDER BY age DESC","Put older customers first"],["id","Break equal-age ties consistently"]],remember:"Sorting by a non-unique value alone leaves ties unspecified. Add a unique tie-breaker.",takeaway:"ORDER BY defines display order; ASC increases, DESC decreases.",difficulty:"Beginner",related:["limit","Learn Top N"]},
  distinct:{question:"Which selected values are unique?",model:["City values","Remove duplicate values","Unique cities"],parts:[["DISTINCT city","Return each distinct selected city once"],["WHERE city IS NOT NULL","Exclude missing cities from this example"]],remember:"DISTINCT applies to the whole selected row. DISTINCT city, name does not mean one row per city.",takeaway:"DISTINCT removes duplicate selected combinations, not arbitrary source rows.",difficulty:"Beginner"},
  limit:{question:"Which first N results do I need?",model:["Sort by age","Keep first 2","Top two customers"],parts:[["ORDER BY age DESC, id","Define oldest first with a tie-breaker"],["LIMIT 2","Keep at most two rows"]],remember:"LIMIT without ORDER BY does not define which rows you get. LIMIT syntax varies by database.",takeaway:"For reliable Top N results, sort first and then limit.",difficulty:"Beginner",related:["order-by","Review ORDER BY"]},
  aggregates:{question:"What single summary describes these rows?",model:["Three order amounts","Count / add / compare","One summary row"],parts:[["COUNT(*)","Count input rows"],["SUM(amount)","Add non-null amounts"],["MIN / MAX","Find the smallest / largest value"]],remember:"COUNT(column) skips NULL values. SUM over no non-null inputs is NULL, not automatically zero.",takeaway:"Aggregates turn many rows into a summary; null handling depends on the function.",difficulty:"Beginner",related:["group-by","Learn GROUP BY"]},
  "group-by":{question:"What is the summary for each customer?",model:["Order rows","Buckets by customer_id","One total per customer"],parts:[["GROUP BY customer_id","One group per customer"],["SUM(amount)","Add amounts inside each group"]],remember:"Selected columns must be compatible with the grouping. Do not select an arbitrary order ID from a group of orders.",takeaway:"GROUP BY sets the summary grain: one result row per group.",difficulty:"Beginner",related:["having","Learn HAVING"]},
  having:{question:"Which group totals meet my condition?",model:["Group orders","Compute totals","Keep totals > 500"],parts:[["GROUP BY customer_id","Form customer groups"],["HAVING SUM(amount) > 500","Filter the computed group totals"]],remember:"WHERE filters source rows; HAVING filters groups. Filtering before summing can change the answer.",takeaway:"Use HAVING for conditions on aggregate results.",difficulty:"Beginner",related:["where","Review WHERE"]},
  joins:{question:"Which records in these tables belong together?",model:["Customers + orders","Match customer IDs","One row per matching pair"],parts:[["customers c / orders o","Short aliases for the two tables"],["ON c.id = o.customer_id","Match an order to its customer"],["INNER JOIN","Keep matching pairs only"]],remember:"Multiple matches multiply result rows. LEFT JOIN retains unmatched left rows; INNER JOIN does not.",takeaway:"Choose the join type and matching key to preserve the records and grain you need.",difficulty:"Intermediate",related:["aggregates","Review COUNT before counting joins"]},
  "subqueries-ctes":{question:"Can I name an intermediate result and use it next?",model:["Orders","CTE: totals by customer","Filter the totals"],parts:[["WITH totals AS (...)","Name the intermediate query"],["FROM totals","Use its result as input"],["WHERE total > 500","Filter the computed values"]],remember:"A CTE is query-scoped. It is not automatically a stored table, cache or speed improvement.",takeaway:"Subqueries and CTEs let one query result feed another query.",difficulty:"Intermediate"},
  "window-functions":{question:"Can I add a summary without losing individual rows?",model:["Three order rows","Calculate per customer","Same rows + total column"],parts:[["SUM(amount) OVER (...)","Attach a total to each row"],["PARTITION BY customer_id","Use related rows from that customer"]],remember:"GROUP BY collapses rows; a window calculation preserves them. Window ordering is separate from final display ordering.",takeaway:"Window functions add context to each row instead of replacing rows with groups.",difficulty:"Intermediate",related:["group-by","Compare with GROUP BY"]},
  "null-case":{question:"How do I label rows with missing information?",model:["Each customer","Test city IS NULL","Add a display label"],parts:[["WHEN city IS NULL","Test for missing information"],["THEN 'Unknown'","Label a missing city"],["ELSE city","Keep known cities"]],remember:"NULL is unknown, not zero or empty text. A display label does not change the stored city.",takeaway:"IS NULL detects missing values; CASE chooses a result for each row.",difficulty:"Beginner"},
  "query-execution":{question:"What does each clause do to the logical result?",model:["FROM → WHERE","GROUP BY → HAVING","SELECT → ORDER BY → LIMIT"],parts:[["WHERE amount > 200","Filter individual orders"],["GROUP BY / HAVING","Summarize and filter groups"],["ORDER BY / LIMIT","Choose the first result after sorting"]],remember:"Logical clause order explains meaning. A database optimizer may use a different physical execution strategy.",takeaway:"Trace the input, row filters, grouping and output clauses before reasoning about performance.",difficulty:"Intermediate"},
};
