import type { SparkLesson } from "@/lib/spark-lessons";
export type TeachingModule = "sql" | "python" | "modeling" | "spark" | "airflow" | "kafka" | "dbt" | "cloud" | "system";
export interface StudyFocus {
    question: string;
    answer: string;
    distractors: [
        string,
        string
    ];
    reason: string;
    edge: string;
    verify: string;
}
// Original interview-style scenarios, not claims about questions asked by a company.
const focus = (question: string, answer: string, wrongA: string, wrongB: string, reason: string, edge: string, verify: string): StudyFocus => ({ question, answer, distractors: [wrongA, wrongB], reason, edge, verify });
export const studyFocus: Record<TeachingModule, Record<string, StudyFocus>> = { sql: {
        introduction: focus("An analyst asks for customer names. What does SQL describe?", "The desired result from stored relational data", "A loop that visits every disk block", "A new database server", "A query specifies the result; the database chooses a physical execution plan.", "An empty customers table should return no customer rows.", "Compare selected columns and row count with the input; confirm the source table is unchanged."),
        select: focus("You need only names and cities. Which query is appropriate?", "SELECT name, city FROM customers;", "SELECT * FROM customers;", "DELETE FROM customers;", "Projection chooses columns; it does not remove rows or duplicates.", "Two customers can have the same name and city; SELECT alone retains both.", "Check the two column headers and that the result has one row for each input customer."),
        where: focus("A customer must be in Chennai or Mumbai AND aged at least 30. How should the city condition be written?", "(city = 'Chennai' OR city = 'Mumbai') AND age >= 30", "city = 'Chennai' OR city = 'Mumbai' AND age >= 30", "city = 'Chennai' AND city = 'Mumbai'", "Parentheses group city alternatives before applying the age requirement.", "A NULL age does not satisfy age >= 30; decide explicitly whether unknown ages belong.", "Test one younger Chennai customer, one older Mumbai customer, and one NULL age."),
        "order-by": focus("Two customers share the same age. How do you make their displayed order stable?", "ORDER BY age DESC, id ASC", "ORDER BY age DESC alone", "Rely on the table's insertion order", "A unique tie-breaker makes the ordering deterministic within a fixed dataset.", "Include tied ages and decide where NULL ages should appear.", "Verify age ordering and ascending IDs within each tied age."),
        distinct: focus("What does SELECT DISTINCT city, age remove?", "Duplicate combinations of city and age", "Every duplicate city regardless of age", "Rows with NULL values", "DISTINCT operates on the full selected tuple, not independently on each column.", "Two people in the same city with different ages should remain two result tuples.", "List unique (city, age) pairs manually and compare them with the result."),
        limit: focus("You need exactly three highest-spending customers with stable tie handling. What is required?", "ORDER BY total_spend DESC, id ASC LIMIT 3", "LIMIT 3 without ORDER BY", "ORDER BY id LIMIT 3", "LIMIT selects a slice of the specified order; a unique secondary key resolves ties.", "If the business wants all customers tied at third place, exactly three rows is a different requirement.", "Test a tie at the cutoff and confirm the agreed top-three policy."),
        aggregates: focus("A table has four rows and two NULL cities. What do COUNT(*) and COUNT(city) return?", "4 and 2", "2 and 2", "4 and 4", "COUNT(*) counts rows; COUNT(expression) counts non-NULL expression values.", "An aggregate over no qualifying rows has COUNT = 0 but SUM generally NULL.", "Test populated, all-NULL, and empty inputs; apply COALESCE only when zero is the intended meaning."),
        "group-by": focus("What is the grain after grouping orders by customer_id?", "One row per customer_id present in orders", "One row per original order", "One row per customer even without orders", "Grouping combines input rows sharing the grouping key; absent customers require a different input such as a LEFT JOIN.", "A customer with no orders is absent from an orders-only aggregation.", "Compare each customer's order count and total with its original records."),
        having: focus("Keep orders above 100, then customers whose retained total exceeds 500. Where do the conditions go?", "amount > 100 in WHERE; SUM(amount) > 500 in HAVING", "Both conditions in WHERE", "Both conditions in SELECT", "WHERE filters input rows before grouping; HAVING filters the resulting groups.", "A customer's total can fall below 500 after small orders are removed.", "Calculate totals before and after the row filter and verify the retained groups."),
        joins: focus("A customer has two orders. How many rows does a matching INNER JOIN produce for that customer?", "Two joined rows", "Exactly one customer row", "Zero unless the customer is unique in both tables", "Join cardinality follows matching pairs; one-to-many relationships expand the result.", "An unmatched customer produces no INNER JOIN row but one NULL-extended LEFT JOIN row.", "Check key uniqueness on each side and COUNT(order_id) for matched orders."),
        "subqueries-ctes": focus("Does putting a query in a CTE guarantee that it runs faster?", "No; examine the actual execution plan", "Yes; CTEs always cache their results", "Yes; a CTE creates a permanent index", "A CTE expresses named query logic; optimization and materialization behavior depend on the database and query.", "A scalar subquery returning several rows is invalid where a single value is required.", "Compare outputs first, then use EXPLAIN to inspect the chosen plan."),
        "window-functions": focus("How does SUM(amount) OVER (PARTITION BY customer_id) differ from GROUP BY customer_id?", "It repeats each customer's total on the original order rows", "It always reduces the result to one row per customer", "It removes duplicate orders automatically", "Window aggregates retain individual rows while calculating over their partitions.", "Tied amounts need a deliberate ROW_NUMBER, RANK, or DENSE_RANK policy.", "Check that input row count is retained and totals match an independent GROUP BY."),
        "null-case": focus("A row has city = NULL. Does WHERE city <> 'Delhi' retain it?", "No; the comparison is unknown", "Yes; NULL is a different city", "Yes; NULL is treated as an empty string", "WHERE retains true predicates, not unknown. Add IS NULL if missing cities should be included.", "CASE without a matching branch or ELSE returns NULL.", "Test known Delhi, another city, and a missing city separately."),
        "query-execution": focus("When a join doubles revenue, what should you investigate first?", "The grain and match cardinality of both join inputs", "Whether LIMIT can hide duplicate rows", "Whether adding DISTINCT always repairs the total", "A many-to-many match can multiply amounts before aggregation; fix the relationship or aggregate to the required grain.", "Include an unmatched customer and a duplicated join key in the review fixture.", "Reconcile row counts, distinct business keys, and revenue before and after each logical stage.")
    }, python: {
        "py-introduction": focus("A CSV amount arrives as '12.50'. What should a pipeline do before adding amounts?", "Parse and validate it as a numeric value", "Add the text values directly", "Assume the CSV reader converts every column", "CSV readers commonly return strings; explicit conversion exposes malformed values.", "Test an empty amount and a value such as 'unknown'.", "Check accepted and rejected counts and reconcile the numeric total."),
        "py-data-structures": focus("You need fast lookup by order ID and must preserve each order's attributes. Which structure fits?", "A dictionary keyed by order ID", "A list that must be scanned for every lookup", "A set of complete mutable dictionaries", "A dictionary supports key-based retrieval; define how duplicate business keys are handled.", "Two records with the same ID may contain conflicting amounts.", "Test a new key, a repeated identical record, and a conflicting duplicate."),
        "py-functions-modules": focus("A function uses rows=[] as its default and appends to it. What is the problem?", "The same default list can be reused across calls", "Python creates a fresh list for each call", "Lists cannot be function arguments", "Defaults are evaluated when the function is defined, so mutable state can leak between calls.", "Call the function twice without an argument and inspect both results.", "Use None as the default, initialize a list inside, and verify independent calls."),
        "py-files-formats": focus("How should a CSV containing quoted commas be read?", "Use csv.DictReader or a CSV parser", "Split every line on a comma", "Remove all commas before processing", "A parser respects quoting and escaping; string splitting can change field boundaries.", "Include a quoted city such as 'Washington, DC' and a missing field.", "Check parsed column count, field values, encoding, and rejected malformed records."),
        "py-error-handling": focus("A row contains an invalid numeric amount. What is a useful handling policy?", "Catch the relevant parse error and record the rejected row", "Catch every exception and silently continue", "Retry the same invalid text forever", "Data errors need a visible policy; infrastructure failures may require different recovery.", "Also test a missing key and an unavailable output path; do not classify them as the same failure.", "Assert rejected-row count, a useful log, and no false successful load."),
        "py-pandas-basics": focus("A merge unexpectedly doubles rows. What should you check?", "Key uniqueness and the intended join cardinality", "Whether changing the DataFrame index always fixes it", "Whether drop_duplicates can safely hide all extra rows", "Repeated keys on both sides create matching pairs; validate the relationship before aggregating.", "Include a duplicate key and an unmatched key on each side.", "Use merge validation where appropriate, inspect unmatched rows, and reconcile totals."),
        "py-hands-on-task": focus("Why deduplicate events before summing revenue?", "Replayed events can otherwise inflate the aggregate", "Deduplication after summing always gives the same total", "Every repeated amount is necessarily a duplicate", "Deduplication needs an agreed event identity and conflict policy before aggregation.", "Test one identical replay and one same-ID record with a changed amount.", "Reconcile unique event IDs, rejected records, and the final grouped totals."),
        "py-interview-questions": focus("How would you choose between a generator and a list for a large input?", "Consider streaming, reuse, and memory requirements", "A generator is always faster in every workload", "A list cannot be iterated more than once", "Generators yield incrementally and can be exhausted; lists retain materialized values for reuse.", "Attempt a second pass over an exhausted generator.", "Measure peak memory and verify that repeated processing does not silently see zero rows."),
        "py-quiz": focus("Why is decimal arithmetic useful for financial amounts?", "It can represent base-10 amounts without binary floating-point rounding for suitable operations", "It makes every calculation exact regardless of precision", "It removes the need for rounding rules", "Use Decimal from strings and specify precision and rounding; numeric representation does not define the business policy.", "Test 0.1 + 0.2 and a value requiring currency rounding.", "Compare results under the agreed rounding policy rather than relying on float equality."),
        "py-summary": focus("What makes a small cleaning pipeline trustworthy before scaling it?", "Known input fixtures, explicit rules, and reconciled outputs", "Only printing a success message", "Only measuring how quickly it finishes", "A correct count can still hide incorrect values; verify both structure and business results.", "Test empty input, duplicate IDs, missing amounts, and invalid types.", "Verify accepted/rejected counts, unique keys, expected totals, and a repeat run.")
    }, modeling: {
        introduction: focus("What should be stated before selecting a fact table's columns?", "What one row represents", "Which dashboard color to use", "Which vendor has the largest warehouse", "The grain defines the meaning of every row and prevents incompatible measures from being combined.", "An order with multiple lines must not repeat an order-level total on every line without an allocation rule.", "Use a multi-line order to reconcile row count and revenue against the source."),
        entities: focus("An order contains several products. How should the relationship usually be represented?", "An order-line entity linking order and product", "A comma-separated list of product IDs in one attribute", "One product_id column that discards the other products", "The junction entity stores each relationship and its attributes such as quantity.", "The same product can occur on two lines with different discounts.", "Validate the composite order/line key and referential links to orders and products."),
        keys: focus("Does a foreign key alone prevent duplicate customer rows?", "No; uniqueness requires an appropriate key or constraint", "Yes; all foreign keys are unique", "Yes; any integer column is automatically unique", "Referential integrity and row identity solve different problems.", "A required relationship may also need NOT NULL in addition to a foreign key.", "Attempt a duplicate primary key, an orphan reference, and a missing required reference."),
        cardinality: focus("A customer can place many orders. Which side normally contains the customer reference?", "The orders side", "The customers side as many order columns", "Both sides must contain arrays of IDs", "A foreign key on each order expresses the many-to-one reference to its customer.", "A customer may have zero orders while each valid order must have one customer.", "Test zero, one, and multiple orders and check mandatory participation separately."),
        "er-modeling": focus("Why label relationship optionality on an ER diagram?", "It defines whether related rows are required", "It sets the exact number of database servers", "It guarantees query performance", "Cardinality and optionality describe valid relationships, not physical capacity.", "An order may allow a guest buyer; clarify whether customer_id can be NULL.", "Translate optionality into constraints and test valid and invalid instances."),
        normalization: focus("A product name is repeated on every order line. What update anomaly can arise?", "Some copies can retain an old product name", "The database automatically updates all copies", "Normalization always removes every join", "Separating dependent product attributes gives the current product identity one authoritative location.", "If historical names are required, overwriting a current product name is insufficient.", "Change the product name and inspect both current references and the agreed historical representation."),
        denormalization: focus("When is denormalizing a model justified?", "When measured read benefits outweigh consistency and maintenance costs", "Whenever duplicate columns make a table wider", "Always, because joins are never useful", "Denormalization trades repeated information and synchronization work for selected access patterns.", "A dimension update may leave cached or repeated attributes stale.", "Measure the target query and test how every duplicated attribute is refreshed."),
        "oltp-olap": focus("Why separate high-volume analytics from a transactional checkout workload?", "Their access patterns and resource needs differ", "Analytics never needs current data", "OLTP cannot store numeric values", "Point updates and wide aggregations can contend; design freshness and replication boundaries explicitly.", "A replica or warehouse can lag behind committed source transactions.", "Compare query latency, transaction latency, and the agreed freshness target."),
        "facts-dimensions": focus("Which value is usually additive across individual sales lines?", "Line revenue", "A unit price without weighting", "A percentage conversion rate", "Additivity depends on grain and dimensions; ratios and unit prices require deliberate aggregation.", "A balance is not generally additive across time snapshots.", "Reconcile revenue by order, day, and product, and document non-additive measures."),
        "star-schema": focus("What should a fact-to-dimension key normally identify?", "Exactly one applicable dimension row", "Any number of historical dimension versions", "A dashboard title", "A correct dimensional join preserves the fact grain; multiple matching versions can inflate measures.", "An unknown dimension member needs an agreed placeholder or quarantine policy.", "Check unmatched foreign keys and that joined fact counts and totals do not multiply."),
        "snowflake-schema": focus("What trade-off comes with normalizing dimensions into a snowflake?", "Less duplicated hierarchy data but more joins", "No joins and guaranteed faster queries", "Automatic Type 2 history for every attribute", "Hierarchy normalization changes both maintenance and query paths; measure the actual workload.", "A product assigned to multiple categories changes the relationship and may need a bridge.", "Trace category joins and ensure measures follow the intended allocation policy."),
        scd: focus("A Type 2 row ends on February 1 using [start,end). Which version matches February 1?", "The new version starting February 1", "Both old and new versions", "Only the old version", "Exclusive end dates avoid overlapping matches at the change boundary.", "Late-arriving facts must resolve against the event date, not merely the current dimension row.", "Test dates before, at, and after a change and assert one matching version per fact."),
        analytics: focus("Why can averaging daily average prices be wrong?", "Daily groups can have different quantities", "Averages cannot be computed in SQL", "Every daily average has equal business weight", "Aggregate the underlying numerator and denominator when a weighted result is required.", "Compare one day with one sale to another with one hundred sales.", "Reconcile SUM(revenue) / SUM(quantity) against the intended weighted definition."),
        "interview-review": focus("A dashboard's revenue doubles after a model change. What should you inspect first?", "Grain, key uniqueness, and join cardinality", "Only the dashboard font size", "Whether DISTINCT can hide every duplicate", "A model review should trace how facts match dimensions and whether measures multiply.", "Include a duplicated dimension business key and an unmatched fact.", "Compare source totals, fact totals, and joined totals at each boundary.")
    }, spark: {
        introduction: focus("Why can a small job take longer in Spark than in local Python?", "Distributed scheduling and communication add overhead", "Spark does not support small numbers", "Executors always execute sequentially", "Parallel work must justify startup, task scheduling, and data movement costs.", "Compare a tiny input with representative production volume.", "Verify identical results, trigger an action, and compare repeated timings under documented conditions."),
        "rdd-vs-dataframe": focus("For a structured sales aggregation, which API is normally the first choice?", "DataFrame expressions that expose the query structure", "RDDs because they are always faster", "collect() followed by a driver loop for every dataset", "Structured expressions allow query optimization; custom RDD processing has different control and cost trade-offs.", "A custom object algorithm may need RDD-level behavior; do not choose only from the input file type.", "Compare equivalent outputs and inspect the DataFrame plan and task metrics."),
        "spark-sql": focus("Do Spark SQL and DataFrame expressions necessarily use separate query engines?", "No; both can use Spark's structured query engine", "Yes; SQL always runs only on the driver", "Yes; DataFrames cannot use query optimization", "Equivalent structured queries can produce comparable plans, although expressions and configurations matter.", "A Python UDF may behave differently from a built-in expression.", "Compare results and explain plans, including pushed filters and shuffle operators."),
        transformations: focus("What happens if you call df.filter(...) but discard the returned DataFrame?", "The original df remains unchanged", "The original df loses the filtered rows", "The filter automatically writes a new table", "DataFrames describe immutable transformations; assign or chain the returned value.", "A filter that matches no rows still produces a valid empty DataFrame.", "Trigger an action on the transformed variable and compare its count with the original."),
        partitioning: focus("Why can coalesce(1) make a large write slow?", "It can concentrate output work into too little parallelism", "It always adds more executors", "It automatically removes skewed keys", "Reducing partitions is a trade-off; one output partition can become a bottleneck.", "A single hot grouping key can dominate one task even with many partitions.", "Inspect task duration, bytes per partition, shuffle metrics, and output file sizes."),
        performance: focus("What evidence should guide a slow Spark query investigation?", "The execution plan and stage/task metrics", "Only the number of installed workers", "Only the duration of defining a transformation", "Identify the costly scan, shuffle, skew, or spill before changing resources.", "One unusually large partition can determine the stage duration.", "Repeat the same action with controlled cache state and compare task distributions and results."),
        "hands-on-task": focus("Why validate event IDs before deduplicating a sales pipeline?", "Repeated IDs can represent replays or conflicting records", "Identical amounts always identify the same event", "dropDuplicates always resolves conflicting updates correctly", "A duplicate policy must define identity and which version wins before aggregation.", "Include the same ID with two different amounts and an identical replay.", "Reconcile input count, accepted unique events, rejected conflicts, and revenue totals."),
        "interview-questions": focus("Why is timing only df.select(...) a poor performance comparison?", "It usually defines lazy work rather than completing it", "select always processes every row immediately", "Only SQL supports measuring queries", "Compare equivalent actions and conditions after verifying matching results.", "Cache state and warm-up can change repeated timings.", "Document input, resources, actions, cache policy, repetitions, and plan differences."),
        quiz: focus("When is broadcast joining a lookup table appropriate?", "When its usable size fits the broadcast budget and the plan supports it", "Whenever the lookup has the word small in its name", "For every join regardless of memory", "Broadcasting can avoid a large-side shuffle but consumes memory; size and execution conditions matter.", "A lookup growing unexpectedly can make a previously safe broadcast fail.", "Inspect plan selection, actual table size, memory use, and output cardinality."),
        summary: focus("Before tuning partitions, what must a pipeline establish?", "Correct output and a reproducible baseline", "Only that every task is green", "Only that it has many executors", "Optimizing an incorrect result does not make the pipeline useful.", "Test empty input, duplicate keys, missing values, and skewed groups.", "Reconcile totals and row counts, then measure the same action under repeatable conditions.")
    }, airflow: {
        introduction: focus("Does parsing an Airflow DAG execute every task body?", "No; task execution occurs in task instances for runs", "Yes; importing the DAG loads all warehouse data", "Yes; the scheduler directly performs all transformations", "DAG definition and task execution are different stages.", "Top-level network or database calls can make DAG parsing slow or unsafe.", "Keep expensive work inside tasks and inspect parse duration and task-instance logs."),
        "dags-dependencies": focus("A >> [B, C] and [B, C] >> D use all_success. When is D eligible?", "After both B and C succeed", "As soon as either B or C starts", "Immediately after A finishes", "Dependencies establish eligibility; capacity still controls when eligible tasks actually run.", "If C fails, D does not satisfy all_success.", "Trace upstream states and distinguish dependency blocking from pool or executor limits."),
        architecture: focus("A task is queued for a long time. What should you inspect?", "Executor capacity, worker health, pools, and concurrency limits", "Only the task's business SQL", "Whether the DAG has a prettier graph", "Queued work has not necessarily begun executing; separate scheduler eligibility from execution capacity.", "Healthy scheduler parsing can coexist with unavailable workers.", "Compare scheduler logs, queued timestamps, pool slots, and executor/worker health."),
        scheduling: focus("A scheduled run represents yesterday's data interval. Which dates should extraction use?", "The run's data interval boundaries", "The worker's current wall-clock date alone", "The time the DAG file was last saved", "Interval-based extraction supports consistent delayed runs and replay.", "Test delayed execution across midnight and daylight-saving boundaries where relevant.", "Log data_interval_start/end and check that the source query reads exactly that interval."),
        "catchup-backfill": focus("What makes a backfill safe for a daily partitioned sink?", "Interval-scoped writes with a deliberate rerun policy", "Appending every interval again without a key", "Using today's date for every historical run", "Historical execution must target the correct interval and avoid repeated effects.", "Rerun one completed interval and include a missing historical partition.", "Compare target partition counts and totals before and after rerunning the same interval."),
        taskflow: focus("Should a TaskFlow function return a large DataFrame through XCom?", "Usually return a storage reference instead", "Yes; XCom is the main bulk-data warehouse", "Yes; the scheduler needs every input row", "Small task metadata and external bulk storage have different responsibilities.", "A result can exceed the configured XCom backend's practical limits.", "Check the configured backend, payload size, and downstream access to the referenced object."),
        "task-lifecycle": focus("How is up_for_retry different from success?", "The attempt failed and is waiting for another eligible attempt", "The data load has already completed successfully", "The task was never scheduled and cannot run", "Task state reflects orchestration progress, not simply whether a box is green.", "A worker can disappear while external processing continues.", "Inspect attempt numbers, retry timing, logs, and actual sink effects before rerunning."),
        retries: focus("A load writes rows and then fails before returning. What must a retry handle?", "An already-applied or partly-applied side effect", "Only the next random sleep duration", "Deleting all previous successful intervals", "Retries can repeat work; use idempotent keys, transactions, or interval replacement as appropriate.", "Fail immediately after the sink commit and before the task success update.", "Rerun the same interval and assert no duplicate business effect."),
        "trigger-rules": focus("A join follows two branches, one skipped and one successful. What may fit the intended join?", "none_failed_min_one_success, if at least one successful branch is required", "all_success regardless of skipped parents", "all_failed for every branch join", "The trigger rule must reflect the allowed upstream states and business contract.", "Also test both branches skipped and one branch failed.", "Enumerate upstream state combinations and verify the downstream behavior under the chosen rule."),
        xcom: focus("What is a suitable XCom value for a large extraction?", "A small path or identifier for the extracted data", "Millions of full records by default", "The permanent copy of the source database", "XCom coordinates task metadata; bulk data normally belongs in an appropriate external store.", "A reference can point to missing or inaccessible data.", "Validate object existence, permissions, schema, and expected record count downstream."),
        sensors: focus("Why can a rescheduling or deferrable sensor improve capacity use?", "It can avoid occupying a worker slot throughout the wait", "It removes the need for any triggerer or scheduler", "It guarantees that the external file will arrive", "Waiting behavior changes resource use; timeout and external readiness still need a policy.", "The awaited object may never arrive or may arrive empty.", "Check timeout outcomes, triggerer requirements, and the readiness condition's business meaning."),
        configuration: focus("Where should production credentials normally live?", "Configured connections or an approved secrets backend", "Hardcoded in a DAG file", "Printed into every task log", "Configuration should separate deployable workflow code from sensitive environment values.", "A rotated credential can expose stale worker configuration.", "Test connection lookup under the task identity and confirm logs do not expose secrets."),
        "dynamic-mapping": focus("What controls how many mapped task instances are created?", "The runtime mapping input, subject to configured limits", "The number of browser tabs", "The number of physical database columns always", "Mapping expands work from input items; concurrency and expansion limits still apply.", "Include an empty mapping input and an unexpectedly large input list.", "Inspect expanded task count, skipped empty work, pool limits, and partial failures."),
        monitoring: focus("A DAG is successful but yesterday's output is missing. What does this show?", "Task success alone is not a data-quality check", "The output must exist because every task is green", "The scheduler always validates business completeness", "Monitor the data outcome as well as orchestration status.", "A task can query the wrong interval and still exit successfully.", "Check freshness, partition presence, accepted counts, and source-to-target reconciliation."),
        production: focus("What should a production DAG's rerun contract explain?", "How repeated or partial runs affect external outputs", "Only its schedule expression", "Only how the graph looks", "Operational readiness includes ownership, replay behavior, validation, and observable failures.", "Backfill overlaps with an active scheduled run.", "Test concurrent interval handling, idempotency, alerts, and documented recovery steps."),
        "etl-review": focus("Which boundary should stop a load after bad extraction data?", "A required validation dependency with explicit failure behavior", "A comment saying data should be valid", "An unrelated task that never blocks the load", "A dependency and validation result must actually enforce the intended quality gate.", "Test malformed input, empty-but-valid input, and unavailable sources separately.", "Trace task states and assert no publish step runs after a required validation failure.")
    }, kafka: {
        introduction: focus("Why can analytics and fraud consumers progress independently?", "They can use separate consumer groups with independent offsets", "Every topic has only one shared global consumer cursor", "Kafka deletes each record immediately after its first read", "Retention and group progress are separate; independent readers can revisit retained data.", "A consumer offline longer than retention may be unable to replay old records.", "Compare group offsets, lag, and the earliest retained offsets before planning recovery."),
        "producers-consumers-topics": focus("Does a producer send a record to a particular consumer instance?", "Normally it publishes to a topic partition", "Yes; it must know each consumer's IP address", "Yes; Kafka records can be read only once", "Producer routing and consumer assignment are separate responsibilities.", "A topic can exist with no active consumers while records are retained.", "Check record publication, partition placement, and progress for each intended consumer group."),
        "partitions-offsets": focus("Are partition 0 offset 12 and partition 1 offset 12 the same position?", "No; position includes topic, partition, and offset", "Yes; offsets are globally unique across a topic", "Yes; offset 12 means the twelfth business event everywhere", "Each partition has its own ordered log and offset namespace.", "Retention or compaction can leave gaps or remove earlier records.", "Inspect per-partition earliest/latest offsets and do not treat an offset as a global row count."),
        "brokers-cluster": focus("A broker fails. What determines whether a partition stays available?", "Replica placement, in-sync state, and election/acknowledgement policy", "Only whether the topic name exists", "Only whether a consumer has enough memory", "Partition replicas and eligible leaders matter; a cluster is not an automatic guarantee against all failures.", "Two replicas on failed infrastructure can reduce redundancy below the intended contract.", "Inspect leaders, in-sync replicas, placement, and producer errors during a controlled failure test."),
        "message-keys": focus("When can the same key move to a different partition?", "After routing rules or partition count change", "Never under any topic configuration", "Only when a consumer changes its group ID", "Key ordering assumes stable routing within a topic; plan changes and hot keys carefully.", "A single high-volume customer can create a hot partition.", "Check key bytes, partitioner behavior, per-partition throughput, and routing across changes."),
        "consumer-groups": focus("With three partitions and five ordinary group members, how many can actively own partitions?", "At most three at a time", "Always all five", "Exactly one for the entire topic", "An ordinary partition assignment gives one owner per partition within a group; extra members may be idle.", "Rebalancing can reassign unfinished work after a member disappears.", "Inspect assignment, processed offsets, lag, and duplicate-safe sink effects across a rebalance."),
        "consumer-offsets": focus("After safely processing offset 211, what offset is normally committed next?", "212", "211", "210", "The committed position identifies the next record the group intends to consume.", "Do not commit beyond a lower offset still being processed asynchronously.", "Crash before and after the commit and verify replay or resume behavior without losing effects."),
        replication: focus("What does acks=all depend on for an acknowledged write?", "The current in-sync replica set and applicable minimum ISR policy", "Every configured replica regardless of whether it is in sync", "Every consumer reading the record", "Acknowledgement, replica health, and minimum ISR jointly affect availability and durability.", "ISR falling below the required minimum can cause writes to fail.", "Monitor ISR changes and verify producer handling of insufficient-replica errors."),
        "delivery-semantics": focus("Does producer idempotence alone prevent every duplicate payment in an external database?", "No; the sink needs its own coordinated or idempotent effect policy", "Yes; any consumer side effect becomes exactly once", "Yes; business republishing can never duplicate an event", "Producer protocol retries and end-to-end business effects have different scopes.", "Crash after a payment write but before committing the consumed offset.", "Replay the event and assert a unique event ID cannot apply the payment twice."),
        "serialization-schema": focus("What should a schema change be tested against?", "Old readers and retained old records as well as new readers", "Only whether Kafka accepts the bytes", "Only the latest producer instance", "Kafka stores bytes; application compatibility is a producer/consumer contract.", "A newly required field may be absent in retained older events.", "Test compatibility in both directions using representative historical fixtures."),
        "kafka-connect": focus("Are all connectors guaranteed to share the same retry and delivery behavior?", "No; behavior depends on the connector and configuration", "Yes; every sink is automatically exactly once", "Yes; source offsets replace all database keys", "Connect supplies a framework; the plugin and target determine important integration semantics.", "A connector restart can replay records or revisit source positions.", "Read the plugin's contract and reconcile source keys, connector offsets, and sink duplicates."),
        "stream-processing": focus("Why distinguish event time from processing time in a streaming aggregation?", "Events can arrive late relative to when they occurred", "Both clocks always identify the same instant", "Processing time reconstructs every historical order automatically", "Windowing and lateness rules define whether delayed records change an aggregate.", "A record arrives after the chosen grace or lateness boundary.", "Test out-of-order timestamps and check window updates under the documented late-event policy."),
        "production-patterns": focus("What should a dead-letter policy preserve?", "The failed record's identity, failure context, and a recovery policy", "Only the word error", "A copy of every credential used by the consumer", "Quarantine should enable diagnosis and controlled replay without leaking sensitive data.", "A poison record may repeatedly fail after a replay.", "Test bounded retries, DLQ metadata, alerts, and a replay that does not repeat successful effects."),
        "architecture-review": focus("What does a Kafka architecture need beyond a topic diagram?", "Retention, keys, schema, progress, sink semantics, and recovery contracts", "Only more partitions than every possible consumer", "Only a single global ordering claim", "A practical design must explain how records survive, evolve, and cause safe downstream effects.", "Combine a delayed consumer, schema change, and repeated event in a recovery fixture.", "Trace each event from source identity through partition position to validated sink effect.")
    }, dbt: {
        "dbt-introduction": focus("Where does a typical dbt SQL model execute?", "In the configured data platform through its adapter", "Inside a new database automatically bundled with dbt", "In the browser's JavaScript runtime", "dbt manages transformation code and dependencies; the connected platform performs the SQL work.", "A valid model can still fail when its execution identity lacks permission.", "Inspect compiled SQL, adapter logs, target relation, and warehouse query results."),
        "models-ref": focus("Why use ref('stg_orders') instead of hardcoding its physical relation name?", "It expresses a model dependency and resolves the target relation", "It automatically deduplicates every order", "It imports raw files from object storage", "ref links project models and lets dbt track dependency and relation naming.", "Development and production can resolve to different schemas.", "Compile in both targets and inspect lineage and relation names."),
        sources: focus("Does declaring a source guarantee fresh data?", "No; freshness needs an appropriate check and execution", "Yes; a YAML declaration refreshes the source continuously", "Yes; source() performs ingestion automatically", "A source declaration identifies external data; ingestion and freshness evaluation are separate.", "A source may be queryable but older than the acceptable freshness threshold.", "Check the loaded-at field, source freshness result, and orchestrated check schedule."),
        lineage: focus("How should a breaking upstream model change be reviewed?", "Inspect downstream dependencies and validate affected contracts", "Only test the changed SQL file", "Rename the file and assume every consumer updates", "Lineage reveals consumers that may depend on removed columns, changed grain, or semantics.", "A downstream dashboard outside the dbt graph can still depend on the relation.", "Review tracked descendants and external consumers, then compare affected outputs."),
        tests: focus("What do failing rows from a data test provide?", "Evidence of records violating the declared rule", "An automatic explanation of every business root cause", "Proof that the warehouse is unavailable", "A test identifies a violation; inspect the data and the rule to diagnose why it failed.", "An empty source can pass some value tests while failing completeness expectations.", "Check violating keys, source counts, freshness, and whether the test matches the business rule."),
        materializations: focus("How should a model's materialization be chosen?", "From freshness, query cost, build cost, and adapter behavior", "Use table for every model without measuring", "Use ephemeral for every large reused transformation", "Views, tables, incremental models, and ephemeral models trade different execution and maintenance costs.", "A frequently reused expensive view can shift work to every consuming query.", "Compare build timing, query timing, data freshness, and adapter-supported behavior."),
        "jinja-macros": focus("When does Jinja usually shape a dbt SQL model?", "During rendering/compilation before warehouse execution", "Once per warehouse row as a Python function", "Only after the query output has been returned", "Templates generate SQL; inspect compiled SQL to understand the actual warehouse operation.", "A macro can render valid SQL in one target and invalid SQL in another.", "Compile representative variables and targets and review the generated SQL and test results."),
        incremental: focus("Why can filtering only event_time > MAX(event_time) miss data?", "Late or updated records may have older event timestamps", "It always reprocesses the entire source", "unique_key automatically widens the input filter", "The selected source window and merge identity are separate; define a late-data and update policy.", "Test a late event, an updated key, and an empty target on the first run.", "Compare incremental output with a full reference build and rerun the same selected batch."),
        "project-structure": focus("What is useful documentation for a customer mart?", "Grain, key meaning, business definitions, lineage, and tests", "Only the folder name", "Only a screenshot of a successful build", "Documentation should make the model understandable to a future user and reviewer.", "A column's business meaning can change without changing its SQL type.", "Review examples, ownership, contracts, and downstream assumptions during a model change."),
        "real-world-review": focus("How do you defend an incremental mart design in an interview?", "Explain the grain, key, input window, late-data handling, tests, and replay policy", "State only that incremental is always faster", "Promise every adapter supports the same merge behavior", "A useful answer ties materialization behavior to correctness and operational constraints.", "A backfill overlaps current incremental processing.", "Reconcile business keys and totals against a full build, then inspect cost and failure recovery.")
    }, cloud: {
        "cloud-introduction": focus("If raw data lands in object storage, what has happened to its business records?", "The objects have been stored; transformation requires a processing operation", "The storage service automatically cleaned every record", "The storage service automatically built a dashboard", "Storage, processing, analytics, and consumption have separate responsibilities.", "A successfully uploaded file can still contain malformed or duplicated records.", "Check the stored object's identity and size, then validate records in the processing stage."),
        "object-storage": focus("Why can millions of tiny objects slow analytical reads?", "Listing/opening overhead and small-file access can dominate", "Object storage cannot hold more than one file", "Every object is automatically merged into one table", "Object layout and file size affect downstream scan efficiency.", "Partitioning by a unique event ID can create excessive tiny partitions.", "Inspect object counts and sizes, scan metrics, and query pruning before changing layout."),
        "identity-security": focus("A pipeline can list a bucket but cannot read one object. What should you investigate?", "Object access policy, encryption key access, and the effective identity", "Only whether the bucket's name is short", "Assume listing proves every permission needed for reading", "Different actions and encrypted resources can require different permissions.", "A rotated secret or explicit deny can override a previously working path.", "Test the actual task identity and action, inspect denial evidence, and avoid broad admin grants."),
        "compute-serverless": focus("When might a long memory-heavy batch be a poor fit for a function runtime?", "When its duration or resource needs exceed practical runtime limits", "Whenever the input contains JSON", "Never; every function has unlimited memory and duration", "Choose compute from workload requirements, limits, startup behavior, and cost.", "A production-sized file can be much larger than the sample used in development.", "Measure peak memory and runtime with representative input and check provider-specific limits."),
        "managed-batch": focus("What remains your responsibility when using a managed Spark service?", "Data correctness, code, permissions, sizing, and monitoring", "Nothing; managed means every query is automatically correct", "Only choosing a provider logo", "Managed infrastructure reduces some operational work but does not define business correctness.", "Skewed keys can still create slow or failing tasks.", "Reconcile outputs and inspect stages, resource use, logs, and cost for the actual workload."),
        "cloud-warehouses": focus("What should you measure when a dashboard query becomes expensive?", "Data scanned, plan behavior, concurrency, and the billing model", "Only the number of SQL lines", "Only whether the warehouse is serverless", "Warehouse costs and performance depend on access patterns and provider behavior.", "A query missing a date filter may scan far more data than intended.", "Compare bytes/partitions scanned, execution statistics, latency, and the expected result."),
        lakehouse: focus("What does an open table format add beyond loose files?", "Table metadata and supported transaction/schema capabilities", "Automatic business-quality validation of every record", "A universal guarantee that every engine supports every feature", "A table format defines table-level operations; engine compatibility and correctness rules still matter.", "Concurrent writes and schema changes need supported commit and compatibility behavior.", "Verify writer/reader compatibility, snapshot results, and concurrent-write outcomes."),
        streaming: focus("Why does accepting a stream event not prove it reached the dashboard?", "Transport acceptance and downstream processing are separate boundaries", "Every accepted event is immediately visible to every consumer", "A broker always computes the final business aggregate", "Observe progress, processing, sink commit, and serving freshness separately.", "A downstream failure can leave retained input accumulating while output is stale.", "Trace event identity, consumer progress, sink counts, and end-to-end lag."),
        "orchestration-integration": focus("What should an orchestrator verify before publishing a downstream result?", "Required task completion and explicit output validation", "Only that a timer has elapsed", "Only that an upstream service exists", "Dependencies and output checks enforce readiness; orchestration does not automatically inspect every business result.", "A job can exit successfully after writing the wrong partition.", "Check interval/path, row counts, schema, freshness, and the required quality gate."),
        "networking-reliability": focus("A private warehouse connection times out. What is a useful first diagnostic split?", "Network reachability versus identity/authorization versus service health", "Immediately grant an administrator role", "Disable every security rule without inspecting evidence", "A timeout and an authorization denial point to different boundaries and remedies.", "DNS resolution can succeed while routing or a private endpoint remains misconfigured.", "Inspect DNS, route, endpoint, allowed ports, service health, and actual error details in order."),
        "cost-architecture-review": focus("What belongs in the cost of an end-to-end data pipeline?", "Storage, compute, requests, transfer, and operational trade-offs", "Only the advertised hourly instance price", "Only the amount of raw data stored", "A cheap component can increase transfer, scanning, retry, or maintenance costs elsewhere.", "Cross-region transfers and repeated full scans can dominate a low-compute design.", "Estimate cost from volume and frequency, then compare measured usage with the forecast.")
    }, system: {
        "design-framework": focus("What should you clarify before drawing a data-platform architecture?", "Consumers, freshness, scale, correctness, and failure requirements", "The logos of every available service", "Which technology has the most features", "Architecture choices should follow explicit requirements and constraints.", "Two consumers can require different freshness and access paths.", "Map each requirement to an observable outcome and defend why each component is needed."),
        "scale-estimation": focus("A daily average is 1,000 events/s but peak traffic is 5 times higher. Which rate informs peak capacity?", "5,000 events/s before additional headroom assumptions", "Exactly 1,000 events/s for every minute", "Five events per day", "Use workload peaks and explicit safety assumptions; daily averages can hide bursts.", "Payload size and retention also change storage and network estimates.", "Check units, burst duration, event size, retention, replication, and recovery capacity."),
        "ingestion-design": focus("Why retain source keys and change metadata in CDC ingestion?", "They support ordering, deduplication, deletes, and recovery", "They are only decorative log fields", "They replace all validation and monitoring", "A change stream needs enough context to apply source transitions safely.", "A delete or repeated change must not become a new inserted business row.", "Test insert, update, delete, snapshot handoff, and replay against the source state."),
        "storage-modeling": focus("How should a storage choice be justified?", "From grain, access patterns, mutation needs, scale, and retention", "Only from a service's popularity", "By putting every workload into one store without measuring", "Serving point queries and scanning large history can require different designs.", "A high-cardinality partition key can produce inefficient data layout.", "Measure target queries, write patterns, partition sizes, and correctness of the modeled grain."),
        "batch-streaming": focus("When can batch be the better architecture?", "When its completion and freshness satisfy the consumers at lower complexity", "Never; all data must be real time", "Only when the dataset has no timestamps", "Streaming adds continuous state and recovery requirements; freshness is a business requirement.", "Late events can change a previously reported period.", "Define lateness and correction policy and measure end-to-end freshness against the target."),
        "correctness-reliability": focus("Why is checkpointing before a durable sink effect risky?", "A restart can skip work whose output was never committed", "It always guarantees exactly-once output", "It merely makes dashboards prettier", "Durable progress must align with completed effects or a coordinated replay policy.", "Crash between sink commit and checkpoint: duplicates must also be handled.", "Inject failures on both sides of the commit boundary and reconcile business keys and totals."),
        "scaling-bottlenecks": focus("Adding workers does not reduce lag. What should you inspect?", "Partition parallelism, hot keys, downstream capacity, and per-stage rates", "Only the number of workers again", "Assume lag is always an object-storage problem", "Capacity is constrained by the slowest relevant boundary and how work is distributed.", "One hot key can serialize a large share of traffic.", "Compare arrival and service rates, partition skew, sink throughput, and queue growth."),
        "serving-layer": focus("Why build a serving model instead of letting every dashboard scan raw events?", "To match predictable query grain, latency, and cost needs", "Because raw data is never useful", "To avoid defining any business metrics", "Precomputed or modeled outputs can improve access, but freshness and semantic contracts remain essential.", "Different dashboards can silently use inconsistent metric definitions.", "Reconcile serving aggregates with raw inputs and measure query latency and freshness."),
        "operations-security-cost": focus("Which signal can detect a silent pipeline failure despite green jobs?", "Missing or stale output and business reconciliation checks", "Only the absence of Python exceptions", "Only whether the worker CPU is below 100%", "Process health and data health are different; monitor both.", "A valid query can select the wrong interval and return zero rows.", "Check freshness, completeness, anomaly baselines, least-privilege access, and usage costs."),
        "case-study": focus("How should a complete design explain replay and backfill?", "Trace source retention, progress, duplicate policy, and corrected output publication", "State only that retries are enabled", "Ignore history once a live dashboard works", "Recovery is part of the architecture, including how historical work coexists with live traffic.", "A large backfill can compete with live processing for sink capacity.", "Simulate overlap, failure, and repeated inputs; validate freshness and totals for both paths.")
    } };
export const studyReferences: Record<TeachingModule, {
    title: string;
    url: string;
}> = {
    sql: { title: "PostgreSQL query guide", url: "https://www.postgresql.org/docs/current/queries.html" },
    python: { title: "Python tutorial", url: "https://docs.python.org/3/tutorial/" },
    modeling: { title: "Microsoft Learn: star schemas", url: "https://learn.microsoft.com/en-us/power-bi/guidance/star-schema" },
    spark: { title: "Apache Spark 3.5.6 guide", url: "https://spark.apache.org/docs/3.5.6/sql-programming-guide.html" },
    airflow: { title: "Apache Airflow documentation", url: "https://airflow.apache.org/docs/apache-airflow/stable/" },
    kafka: { title: "Apache Kafka 4.1 design", url: "https://kafka.apache.org/41/design/design/" },
    dbt: { title: "dbt project documentation", url: "https://docs.getdbt.com/docs/build/projects" },
    cloud: { title: "AWS architecture guidance", url: "https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html" },
    system: { title: "Azure architecture fundamentals", url: "https://learn.microsoft.com/en-us/azure/architecture/guide/" }
};
export function buildStudyContent(module: TeachingModule, lesson: SparkLesson) {
    const f = studyFocus[module][lesson.id];
    const interviews = [...lesson.interview];
    if (f)
        interviews.push({ question: f.question, answer: f.answer + ". " + f.reason, followup: f.edge });
    for (const m of lesson.mistakes.slice(0, Math.max(0, 4 - interviews.length)))
        interviews.push({ question: `A teammate proposes this approach: ${m.title.toLowerCase()}. How would you review it?`, answer: m.why + " " + m.better, followup: f?.verify ?? "Explain the corrected approach using the worked example." });
    if (interviews.length < 4 && f)
        interviews.push({ question: `How would you test your ${lesson.title.toLowerCase()} solution before using it in a pipeline?`, answer: f.verify, followup: f.edge });
    if (f) {
        interviews.push({
            question: `Production review: ${f.edge} What behavior should a reviewer expect, and how would you verify it?`,
            answer: `${f.answer}. ${f.reason} The boundary to handle explicitly is: ${f.edge} Validate the policy rather than assuming the happy path still applies. ${f.verify}`,
            followup: `What evidence would convince a reviewer? ${f.verify}`
        });
        interviews.push({
            question: `Defend your decision: why is “${f.distractors[0]}” not the right answer here?`,
            answer: `The appropriate decision is: ${f.answer}. ${f.reason} The proposed alternative does not meet that requirement. Use this boundary in your explanation: ${f.edge}`,
            followup: `Explain the trade-off without relying on a product name. Then describe this check: ${f.verify}`
        });
    }
    const quiz = lesson.quiz.map(q => ({ ...q, explanation: q.explanation.length < 40 && f ? q.explanation + " " + f.reason : q.explanation }));
    if (f && !quiz.some(q => q.question === f.question)) {
        const at = lesson.id.length % 3;
        const options = [...f.distractors];
        options.splice(at, 0, f.answer);
        quiz.push({ question: f.question, options, correct: at, explanation: f.reason });
    }
    for (const m of lesson.mistakes.slice(0, Math.max(0, 4 - quiz.length))) {
        const at = m.title.length % 3;
        const options = [m.before, "Leave the original approach unchanged."];
        options.splice(at, 0, m.after);
        quiz.push({ question: `Which approach addresses: ${m.title.toLowerCase()}?`, options, correct: at, explanation: m.why + " " + m.better });
    }
    return { focus: f, interviews, quiz, reference: studyReferences[module] };
}
